java_library(
  name = "util",
  srcs = ["CompilerUtil.java"],
  deps = [
    "//src/java/com/github/jsdossier:lib",
    "//third_party/java/closure_compiler:closure_compiler",
    "//third_party/java/guava:guava",
    "//third_party/java/junit:junit",
  ],
  visibility = [
    "//test/java/com/google/javascript/jscomp/...",
  ],
)

java_test(
  name = "tests",
  srcs = glob([
      "*.java",
      "soy/*.java",
  ], excludes = ["CompilerUtil.java"]),
  resources = glob(["resources/**"]),
  deps = [
    ":util",
    "//src/java/com/github/jsdossier:lib",
    "//third_party/java/closure_compiler:closure_compiler",
    "//third_party/java/gson:gson",
    "//third_party/java/guava:guava",
    "//third_party/java/jimfs:jimfs",
    "//third_party/java/jsoup:jsoup",
    "//third_party/java/jsr305:jsr305",
    "//third_party/java/junit:junit",
    "//third_party/java/mockito:mockito",
    "//third_party/java/protobuf:protobuf",
    "//third_party/java/soy:soy",
    "//third_party/java/truth:truth",
  ],
)
