java_library(
  name = "jscomp",
  srcs = [
    "DossierCompiler.java",
    "DossierModule.java",
    "DossierModuleRegistry.java",
    "DossierProcessCommonJsModules.java",
  ],
  deps = [
    "//third_party/java/closure_compiler:closure_compiler",
    "//third_party/java/guava:guava",
    "//third_party/java/jsr305:jsr305",
  ],
  visibility = [
    "//src/main/java/com/github/jsdossier/...",
    "//src/test/java/com/github/jsdossier/...",
    "//src/test/java/com/google/javascript/jscomp/...",
  ],
)
