java_test(
  name = "tests",
  srcs = glob(["*.java"]),
  deps = [
    "//src/main/java/com/google/javascript/jscomp:jscomp",
    "//src/test/java/com/github/jleyba/dossier:util",
    "//third_party/java/closure_compiler:closure_compiler",
    "//third_party/java/guava:guava",
    "//third_party/java/junit:junit",
  ],
)
