(function(){var h,m=this;function aa(){}
function ba(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}function r(a){return"array"==ba(a)}function ca(a){var b=ba(a);return"array"==b||"object"==b&&"number"==typeof a.length}function t(a){return"string"==typeof a}function da(a){return"function"==ba(a)}function ea(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function fa(a){return a[ga]||(a[ga]=++ha)}var ga="closure_uid_"+(1E9*Math.random()>>>0),ha=0;function ia(a,b,c){return a.call.apply(a.bind,arguments)}
function ja(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function u(a,b,c){u=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ia:ja;return u.apply(null,arguments)}
function ka(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}}var w=Date.now||function(){return+new Date};function x(a,b){function c(){}c.prototype=b.prototype;a.i=b.prototype;a.prototype=new c};var la;function ma(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")}function na(a){if(!oa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(pa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(qa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(ra,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(ta,"&quot;"));return a}var pa=/&/g,qa=/</g,ra=/>/g,ta=/\"/g,oa=/[&<>\"]/;function ua(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};var y=Array.prototype,va=y.indexOf?function(a,b,c){return y.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(t(a))return t(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},z=y.forEach?function(a,b,c){y.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},wa=y.filter?function(a,b,c){return y.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=t(a)?
a.split(""):a,k=0;k<d;k++)if(k in g){var l=g[k];b.call(c,l,k,a)&&(e[f++]=l)}return e},xa=y.map?function(a,b,c){return y.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=t(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};function ya(a){a:for(var b=document.getElementsByTagName("script"),c=b.length,d=t(b)?b.split(""):b,e=0;e<c;e++)if(e in d&&a.call(void 0,d[e],e,b))break a}function za(a){return y.concat.apply(y,arguments)}
function Aa(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function Ba(a,b,c){return 2>=arguments.length?y.slice.call(a,b):y.slice.call(a,b,c)};var Ca,Da,Ea,Fa,A;function Ga(){return m.navigator?m.navigator.userAgent:null}function Ha(){return m.navigator}Fa=Ea=Da=Ca=!1;var Ia;if(Ia=Ga()){var Ja=Ha();Ca=0==Ia.lastIndexOf("Opera",0);Da=!Ca&&(-1!=Ia.indexOf("MSIE")||-1!=Ia.indexOf("Trident"));Ea=!Ca&&-1!=Ia.indexOf("WebKit");Fa=!Ca&&!Ea&&!Da&&"Gecko"==Ja.product}var B=Ca,C=Da,D=Fa,E=Ea,Ka=Ha();A=-1!=(Ka&&Ka.platform||"").indexOf("Mac");var La=!!Ha()&&-1!=(Ha().appVersion||"").indexOf("X11");
function Ma(){var a=m.document;return a?a.documentMode:void 0}var Na;a:{var Oa="",Pa;if(B&&m.opera)var Qa=m.opera.version,Oa="function"==typeof Qa?Qa():Qa;else if(D?Pa=/rv\:([^\);]+)(\)|;)/:C?Pa=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:E&&(Pa=/WebKit\/(\S+)/),Pa)var Ra=Pa.exec(Ga()),Oa=Ra?Ra[1]:"";if(C){var Sa=Ma();if(Sa>parseFloat(Oa)){Na=String(Sa);break a}}Na=Oa}var Ta={};
function F(a){var b;if(!(b=Ta[a])){b=0;for(var c=ma(String(Na)).split("."),d=ma(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",k=d[f]||"",l=RegExp("(\\d*)(\\D*)","g"),n=RegExp("(\\d*)(\\D*)","g");do{var p=l.exec(g)||["","",""],q=n.exec(k)||["","",""];if(0==p[0].length&&0==q[0].length)break;b=((0==p[1].length?0:parseInt(p[1],10))<(0==q[1].length?0:parseInt(q[1],10))?-1:(0==p[1].length?0:parseInt(p[1],10))>(0==q[1].length?0:parseInt(q[1],10))?1:0)||((0==p[2].length)<
(0==q[2].length)?-1:(0==p[2].length)>(0==q[2].length)?1:0)||(p[2]<q[2]?-1:p[2]>q[2]?1:0)}while(0==b)}b=Ta[a]=0<=b}return b}var Ua=m.document,G=Ua&&C?Ma()||("CSS1Compat"==Ua.compatMode?parseInt(Na,10):5):void 0;var Va=!C||C&&9<=G,Wa=C&&!F("9");!E||F("528");D&&F("1.9b")||C&&F("8")||B&&F("9.5")||E&&F("528");D&&!F("8")||C&&F("9");function J(){0!=Xa&&(Ya[fa(this)]=this)}var Xa=0,Ya={};J.prototype.La=!1;J.prototype.B=function(){if(!this.La&&(this.La=!0,this.e(),0!=Xa)){var a=fa(this);delete Ya[a]}};J.prototype.e=function(){if(this.Za)for(;this.Za.length;)this.Za.shift()()};function Za(a){a&&"function"==typeof a.B&&a.B()};function K(a,b){this.type=a;this.currentTarget=this.target=b}h=K.prototype;h.e=function(){};h.B=function(){};h.G=!1;h.defaultPrevented=!1;h.hb=!0;h.stopPropagation=function(){this.G=!0};h.preventDefault=function(){this.defaultPrevented=!0;this.hb=!1};function $a(a){$a[" "](a);return a}$a[" "]=aa;function L(a,b){a&&ab(this,a,b)}x(L,K);h=L.prototype;h.target=null;h.relatedTarget=null;h.offsetX=0;h.offsetY=0;h.clientX=0;h.clientY=0;h.screenX=0;h.screenY=0;h.button=0;h.keyCode=0;h.charCode=0;h.ctrlKey=!1;h.altKey=!1;h.shiftKey=!1;h.metaKey=!1;h.N=null;
function ab(a,b,c){var d=a.type=b.type;K.call(a,d);a.target=b.target||b.srcElement;a.currentTarget=c;if(c=b.relatedTarget){if(D){var e;a:{try{$a(c.nodeName);e=!0;break a}catch(f){}e=!1}e||(c=null)}}else"mouseover"==d?c=b.fromElement:"mouseout"==d&&(c=b.toElement);a.relatedTarget=c;a.offsetX=E||void 0!==b.offsetX?b.offsetX:b.layerX;a.offsetY=E||void 0!==b.offsetY?b.offsetY:b.layerY;a.clientX=void 0!==b.clientX?b.clientX:b.pageX;a.clientY=void 0!==b.clientY?b.clientY:b.pageY;a.screenX=b.screenX||0;
a.screenY=b.screenY||0;a.button=b.button;a.keyCode=b.keyCode||0;a.charCode=b.charCode||("keypress"==d?b.keyCode:0);a.ctrlKey=b.ctrlKey;a.altKey=b.altKey;a.shiftKey=b.shiftKey;a.metaKey=b.metaKey;a.state=b.state;a.N=b;b.defaultPrevented&&a.preventDefault();delete a.G}h.stopPropagation=function(){L.i.stopPropagation.call(this);this.N.stopPropagation?this.N.stopPropagation():this.N.cancelBubble=!0};
h.preventDefault=function(){L.i.preventDefault.call(this);var a=this.N;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Wa)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};h.e=function(){};var bb="closure_listenable_"+(1E6*Math.random()|0);function cb(a){try{return!(!a||!a[bb])}catch(b){return!1}}var db=0;function eb(a,b,c,d,e){this.J=a;this.la=null;this.src=b;this.type=c;this.capture=!!d;this.fa=e;this.key=++db;this.T=this.da=!1}function fb(a){a.T=!0;a.J=null;a.la=null;a.src=null;a.fa=null};function gb(a,b){for(var c in a)b.call(void 0,a[c],c,a)}function hb(){var a=ib,b;for(b in a)return!1;return!0}var jb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function kb(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<jb.length;f++)c=jb[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function M(a){this.src=a;this.l={};this.ca=0}M.prototype.add=function(a,b,c,d,e){var f=this.l[a];f||(f=this.l[a]=[],this.ca++);var g=lb(f,b,d,e);-1<g?(a=f[g],c||(a.da=!1)):(a=new eb(b,this.src,a,!!d,e),a.da=c,f.push(a));return a};M.prototype.remove=function(a,b,c,d){if(!(a in this.l))return!1;var e=this.l[a];b=lb(e,b,c,d);return-1<b?(fb(e[b]),y.splice.call(e,b,1),0==e.length&&(delete this.l[a],this.ca--),!0):!1};
function mb(a,b){var c=b.type;if(!(c in a.l))return!1;var d=a.l[c],e=va(d,b),f;(f=0<=e)&&y.splice.call(d,e,1);f&&(fb(b),0==a.l[c].length&&(delete a.l[c],a.ca--));return f}M.prototype.ma=function(a){var b=0,c;for(c in this.l)if(!a||c==a){for(var d=this.l[c],e=0;e<d.length;e++)++b,fb(d[e]);delete this.l[c];this.ca--}return b};M.prototype.X=function(a,b,c,d){a=this.l[a];var e=-1;a&&(e=lb(a,b,c,d));return-1<e?a[e]:null};
function lb(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.T&&f.J==b&&f.capture==!!c&&f.fa==d)return e}return-1};var nb="closure_lm_"+(1E6*Math.random()|0),ob={},pb=0;function N(a,b,c,d,e){if(r(b)){for(var f=0;f<b.length;f++)N(a,b[f],c,d,e);return null}c=qb(c);if(cb(a))a=a.o(b,c,d,e);else{if(!b)throw Error("Invalid event type");var f=!!d,g=rb(a);g||(a[nb]=g=new M(a));c=g.add(b,c,!1,d,e);c.la||(d=sb(),c.la=d,d.src=a,d.J=c,a.addEventListener?a.addEventListener(b,d,f):a.attachEvent(b in ob?ob[b]:ob[b]="on"+b,d),pb++);a=c}return a}
function sb(){var a=tb,b=Va?function(c){return a.call(b.src,b.J,c)}:function(c){c=a.call(b.src,b.J,c);if(!c)return c};return b}function ub(a,b,c,d,e){if(r(b))for(var f=0;f<b.length;f++)ub(a,b[f],c,d,e);else c=qb(c),cb(a)?a.s(b,c,d,e):a&&(a=rb(a))&&(b=a.X(b,c,!!d,e))&&O(b)}
function O(a){if("number"==typeof a||!a||a.T)return!1;var b=a.src;if(cb(b))return mb(b.C,a);var c=a.type,d=a.la;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent&&b.detachEvent(c in ob?ob[c]:ob[c]="on"+c,d);pb--;(c=rb(b))?(mb(c,a),0==c.ca&&(c.src=null,b[nb]=null)):fb(a);return!0}function vb(a,b,c,d){var e=1;if(a=rb(a))if(b=a.l[b])for(b=Aa(b),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.T&&(e&=!1!==wb(f,d))}return Boolean(e)}
function wb(a,b){var c=a.J,d=a.fa||a.src;a.da&&O(a);return c.call(d,b)}
function tb(a,b){if(a.T)return!0;if(!Va){var c;if(!(c=b))a:{c=["window","event"];for(var d=m,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break a}c=d}e=c;c=new L(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){a:{var f=!1;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(g){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.currentTarget;f;f=f.parentNode)e.push(f);for(var f=a.type,k=e.length-1;!c.G&&0<=k;k--)c.currentTarget=e[k],d&=vb(e[k],f,!0,c);for(k=0;!c.G&&k<e.length;k++)c.currentTarget=
e[k],d&=vb(e[k],f,!1,c)}return d}return wb(a,new L(b,this))}function rb(a){a=a[nb];return a instanceof M?a:null}var xb="__closure_events_fn_"+(1E9*Math.random()>>>0);function qb(a){return da(a)?a:a[xb]||(a[xb]=function(b){return a.handleEvent(b)})};var yb=!C||C&&9<=G;!D&&!C||C&&C&&9<=G||D&&F("1.9.1");C&&F("9");function zb(a,b){var c;c=a.className;c=t(c)&&c.match(/\S+/g)||[];for(var d=Ba(arguments,1),e=c.length+d.length,f=c,g=0;g<d.length;g++)0<=va(f,d[g])||f.push(d[g]);a.className=c.join(" ");return c.length==e};function P(a,b){this.x=void 0!==a?a:0;this.y=void 0!==b?b:0}P.prototype.W=function(){return new P(this.x,this.y)};function Ab(a,b){return new P(a.x-b.x,a.y-b.y)}P.prototype.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};function Bb(a,b){this.width=a;this.height=b}Bb.prototype.W=function(){return new Bb(this.width,this.height)};Bb.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function Q(a){return a?new Cb(R(a)):la||(la=new Cb)}function Db(a){var b=document;return t(a)?b.getElementById(a):a}function Eb(a,b){gb(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in Fb?a.setAttribute(Fb[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})}
var Fb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function Gb(a){return E||"CSS1Compat"!=a.compatMode?a.body||a.documentElement:a.documentElement}function Hb(a,b,c){return Ib(document,arguments)}
function Ib(a,b){var c=b[0],d=b[1];if(!yb&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',na(d.name),'"');if(d.type){c.push(' type="',na(d.type),'"');var e={};kb(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&(t(d)?c.className=d:r(d)?zb.apply(null,[c].concat(d)):Eb(c,d));2<b.length&&Jb(a,c,b);return c}
function Jb(a,b,c){function d(c){c&&b.appendChild(t(c)?a.createTextNode(c):c)}for(var e=2;e<c.length;e++){var f=c[e];if(!ca(f)||ea(f)&&0<f.nodeType)d(f);else{var g;a:{if(f&&"number"==typeof f.length){if(ea(f)){g="function"==typeof f.item||"string"==typeof f.item;break a}if(da(f)){g="function"==typeof f.item;break a}}g=!1}z(g?Aa(f):f,d)}}}function Kb(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}function R(a){return 9==a.nodeType?a:a.ownerDocument||a.document}
function Cb(a){this.j=a||m.document||document}h=Cb.prototype;h.Ka=function(a,b,c){return Ib(this.j,arguments)};h.createElement=function(a){return this.j.createElement(a)};h.createTextNode=function(a){return this.j.createTextNode(String(a))};function Lb(a){return"CSS1Compat"==a.j.compatMode}function Mb(a){var b=a.j;a=Gb(b);b=b.parentWindow||b.defaultView;return C&&F("10")&&b.pageYOffset!=a.scrollTop?new P(a.scrollLeft,a.scrollTop):new P(b.pageXOffset||a.scrollLeft,b.pageYOffset||a.scrollTop)}
h.appendChild=function(a,b){a.appendChild(b)};function Nb(a){for(var b;b=a.firstChild;)a.removeChild(b)}h.removeNode=Kb;h.contains=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};function S(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}S.prototype.W=function(){return new S(this.top,this.right,this.bottom,this.left)};S.prototype.contains=function(a){return this&&a?a instanceof S?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom:!1};
S.prototype.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};function T(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}T.prototype.W=function(){return new T(this.left,this.top,this.width,this.height)};T.prototype.contains=function(a){return a instanceof T?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};
T.prototype.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function U(a,b){var c=R(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,null))?c[b]||c.getPropertyValue(b)||"":""}function V(a,b){return U(a,b)||(a.currentStyle?a.currentStyle[b]:null)||a.style&&a.style[b]}
function Ob(a){var b;try{b=a.getBoundingClientRect()}catch(c){return{left:0,top:0,right:0,bottom:0}}C&&a.ownerDocument.body&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b}
function Pb(a){if(C&&!(C&&8<=G))return a.offsetParent;var b=R(a),c=V(a,"position"),d="fixed"==c||"absolute"==c;for(a=a.parentNode;a&&a!=b;a=a.parentNode)if(c=V(a,"position"),d=d&&"static"==c&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==c||"absolute"==c||"relative"==c))return a;return null}
function Qb(a){for(var b=new S(0,Infinity,Infinity,0),c=Q(a),d=c.j.body,e=c.j.documentElement,f=Gb(c.j);a=Pb(a);)if(!(C&&0==a.clientWidth||E&&0==a.clientHeight&&a==d||a==d||a==e||"visible"==V(a,"overflow"))){var g=W(a),k;k=a;if(D&&!F("1.9")){var l=parseFloat(U(k,"borderLeftWidth"));if(Rb(k))var n=k.offsetWidth-k.clientWidth-l-parseFloat(U(k,"borderRightWidth")),l=l+n;k=new P(l,parseFloat(U(k,"borderTopWidth")))}else k=new P(k.clientLeft,k.clientTop);g.x+=k.x;g.y+=k.y;b.top=Math.max(b.top,g.y);b.right=
Math.min(b.right,g.x+a.clientWidth);b.bottom=Math.min(b.bottom,g.y+a.clientHeight);b.left=Math.max(b.left,g.x)}d=f.scrollLeft;f=f.scrollTop;b.left=Math.max(b.left,d);b.top=Math.max(b.top,f);c=(c.j.parentWindow||c.j.defaultView||window).document;c="CSS1Compat"==c.compatMode?c.documentElement:c.body;c=new Bb(c.clientWidth,c.clientHeight);b.right=Math.min(b.right,d+c.width);b.bottom=Math.min(b.bottom,f+c.height);return 0<=b.top&&0<=b.left&&b.bottom>b.top&&b.right>b.left?b:null}
function W(a){var b,c=R(a),d=V(a,"position"),e=D&&c.getBoxObjectFor&&!a.getBoundingClientRect&&"absolute"==d&&(b=c.getBoxObjectFor(a))&&(0>b.screenX||0>b.screenY),f=new P(0,0),g;b=c?R(c):document;g=!C||C&&9<=G||Lb(Q(b))?b.documentElement:b.body;if(a==g)return f;if(a.getBoundingClientRect)b=Ob(a),a=Mb(Q(c)),f.x=b.left+a.x,f.y=b.top+a.y;else if(c.getBoxObjectFor&&!e)b=c.getBoxObjectFor(a),a=c.getBoxObjectFor(g),f.x=b.screenX-a.screenX,f.y=b.screenY-a.screenY;else{b=a;do{f.x+=b.offsetLeft;f.y+=b.offsetTop;
b!=a&&(f.x+=b.clientLeft||0,f.y+=b.clientTop||0);if(E&&"fixed"==V(b,"position")){f.x+=c.body.scrollLeft;f.y+=c.body.scrollTop;break}b=b.offsetParent}while(b&&b!=a);if(B||E&&"absolute"==d)f.y-=c.body.offsetTop;for(b=a;(b=Pb(b))&&b!=c.body&&b!=g;)f.x-=b.scrollLeft,B&&"TR"==b.tagName||(f.y-=b.scrollTop)}return f}function Sb(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a}
function Tb(a){var b=Ub;if("none"!=V(a,"display"))return b(a);var c=a.style,d=c.display,e=c.visibility,f=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";a=b(a);c.display=d;c.position=f;c.visibility=e;return a}function Ub(a){var b=a.offsetWidth,c=a.offsetHeight,d=E&&!b&&!c;return(void 0===b||d)&&a.getBoundingClientRect?(a=Ob(a),new Bb(a.right-a.left,a.bottom-a.top)):new Bb(b,c)}function Rb(a){return"rtl"==V(a,"direction")}var Vb=D?"MozUserSelect":E?"WebkitUserSelect":null;
function Wb(a){var b=a.getElementsByTagName("*");if(Vb){var c="none";a.style[Vb]=c;if(b){a=0;for(var d;d=b[a];a++)d.style[Vb]=c}}else if(C||B)if(c="on",a.setAttribute("unselectable",c),b)for(a=0;d=b[a];a++)d.setAttribute("unselectable",c)}function Xb(a,b){if(/^\d+px?$/.test(b))return parseInt(b,10);var c=a.style.left,d=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=b;var e=a.style.pixelLeft;a.style.left=c;a.runtimeStyle.left=d;return e}
function Yb(a,b){var c=a.currentStyle?a.currentStyle[b]:null;return c?Xb(a,c):0}var Zb={thin:2,medium:4,thick:6};function $b(a,b){if("none"==(a.currentStyle?a.currentStyle[b+"Style"]:null))return 0;var c=a.currentStyle?a.currentStyle[b+"Width"]:null;return c in Zb?Zb[c]:Xb(a,c)}
function ac(a){if(C&&!(C&&9<=G)){var b=$b(a,"borderLeft"),c=$b(a,"borderRight"),d=$b(a,"borderTop");a=$b(a,"borderBottom");return new S(d,c,a,b)}b=U(a,"borderLeftWidth");c=U(a,"borderRightWidth");d=U(a,"borderTopWidth");a=U(a,"borderBottomWidth");return new S(parseFloat(d),parseFloat(c),parseFloat(a),parseFloat(b))}var bc=/[^\d]+$/,cc={cm:1,"in":1,mm:1,pc:1,pt:1},dc={em:1,ex:1};
function ec(){var a=document.documentElement,b=V(a,"fontSize"),c;c=(c=b.match(bc))&&c[0]||null;if(b&&"px"==c)return parseInt(b,10);if(C){if(c in cc)return Xb(a,b);if(a.parentNode&&1==a.parentNode.nodeType&&c in dc)return a=a.parentNode,c=V(a,"fontSize"),Xb(a,b==c?"1em":b)}c=Hb("span",{style:"visibility:hidden;position:absolute;line-height:0;padding:0;margin:0;border:0;height:1em;"});a.appendChild(c);b=c.offsetHeight;Kb(c);return b}var fc=/matrix\([0-9\.\-]+, [0-9\.\-]+, [0-9\.\-]+, [0-9\.\-]+, ([0-9\.\-]+)p?x?, ([0-9\.\-]+)p?x?\)/;function gc(a){this.c=a||[];this.Ob=!0}function hc(a,b,c){var d=[];if(""!=a){a=ua(a);a=RegExp("(^|\\W+)"+a,"i");for(var e=0;e<c.length&&d.length<b;e++){var f=c[e];String(f).match(a)&&d.push(f)}}return d}
function ic(a,b,c){for(var d=[],e=0;e<c.length;e++){var f=c[e],g=a.toLowerCase(),k=String(f).toLowerCase(),l=0;if(-1!=k.indexOf(g))l=parseInt((k.indexOf(g)/4).toString(),10);else for(var n=g.split(""),p=-1,q=10,H=0,s;s=n[H];H++)s=k.indexOf(s),s>p?(p=s-p-1,p>q-5&&(p=q-5),l+=p,p=s):(l+=q,q+=5);l<6*g.length&&d.push({Lb:f,ib:l,index:e})}d.sort(function(a,b){var c=a.ib-b.ib;return 0!=c?c:a.index-b.index});a=[];for(H=0;H<b&&H<d.length;H++)a.push(d[H].Lb);return a};function X(){J.call(this);this.C=new M(this);this.ob=this}x(X,J);X.prototype[bb]=!0;h=X.prototype;h.Ca=null;h.addEventListener=function(a,b,c,d){N(this,a,b,c,d)};h.removeEventListener=function(a,b,c,d){ub(this,a,b,c,d)};
h.dispatchEvent=function(a){var b,c=this.Ca;if(c)for(b=[];c;c=c.Ca)b.push(c);var c=this.ob,d=a.type||a;if(t(a))a=new K(a,c);else if(a instanceof K)a.target=a.target||c;else{var e=a;a=new K(d,c);kb(a,e)}var e=!0,f;if(b)for(var g=b.length-1;!a.G&&0<=g;g--)f=a.currentTarget=b[g],e=jc(f,d,!0,a)&&e;a.G||(f=a.currentTarget=c,e=jc(f,d,!0,a)&&e,a.G||(e=jc(f,d,!1,a)&&e));if(b)for(g=0;!a.G&&g<b.length;g++)f=a.currentTarget=b[g],e=jc(f,d,!1,a)&&e;return e};
h.e=function(){X.i.e.call(this);this.C&&this.C.ma(void 0);this.Ca=null};h.o=function(a,b,c,d){return this.C.add(a,b,!1,c,d)};h.s=function(a,b,c,d){return this.C.remove(a,b,c,d)};function jc(a,b,c,d){b=a.C.l[b];if(!b)return!0;b=Aa(b);for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.T&&g.capture==c){var k=g.J,l=g.fa||g.src;g.da&&mb(a.C,g);e=!1!==k.call(l,d)&&e}}return e&&!1!=d.hb}h.X=function(a,b,c,d){return this.C.X(a,b,c,d)};function kc(a,b,c){X.call(this);this.Q=a;this.$=c;this.p=b;N(b,[lc,mc,nc,oc],this.handleEvent,!1,this);this.q=null;this.c=[];this.D=-1;this.k=0;this.I=this.g=null;this.Sa={}}x(kc,X);h=kc.prototype;h.Xa=10;h.qb=!0;h.Ja=!1;h.nb=!1;h.kb=!1;var lc="hilite",mc="select",oc="dismiss",nc="canceldismiss";h=kc.prototype;
h.handleEvent=function(a){if(a.target==this.p)switch(a.type){case lc:this.A(a.U);break;case mc:a=a.U;var b=this.c[pc(this,a)],c=!!b&&this.Q.wa&&this.Q.wa(b);a&&b&&!c&&this.D!=a&&this.A(a);c||qc(this);break;case nc:rc(this);break;case oc:sc(this)}};function tc(a){a.Xa=100}function uc(a){for(var b=a.k+a.c.length-1,c=a.D,d=0;d<a.c.length;d++){if(c>=a.k&&c<b)c++;else if(-1==c)c=a.k;else if(a.Ja&&c==b){a.A(-1);break}else if(a.nb&&c==b)c=a.k;else break;if(a.A(c))break}}
function vc(a){for(var b=a.k+a.c.length-1,c=a.D,d=0;d<a.c.length;d++){if(c>a.k)c--;else if(a.Ja&&c==a.k){a.A(-1);break}else if(!a.nb||-1!=c&&c!=a.k)break;else c=b;if(a.A(c))break}}h.A=function(a){var b=pc(this,a),c=this.c[b];return c&&this.Q.wa&&this.Q.wa(c)?!1:(this.D=a,this.p.A(a),-1!=b)};
function qc(a){var b=pc(a,a.D);if(-1!=b){var b=a.c[b],c=a.$,d=b.toString();if(c.R){var e=wc(c,c.a.value,xc(c.a)),f=yc(c,c.a.value);c.Ib.test(d)||(d=d.replace(/[\s\xa0]+$/,"")+c.sb);c.Qb&&(0==e||/^[\s\xa0]*$/.test(f[e-1])||(d=" "+d),e==f.length-1&&(d+=" "));if(d!=f[e]){f[e]=d;d=c.a;(D||C&&F("9"))&&d.blur();d.value=f.join("");for(var g=0,k=0;k<=e;k++)g+=f[k].length;d.focus();e=g;f=c.a;d=e;zc(f)?f.selectionStart=d:C&&(g=Ac(f),k=g[0],k.inRange(g[1])&&(d=Bc(f,d),k.collapse(!0),k.move("character",d),k.select()));
f=c.a;zc(f)?f.selectionEnd=e:C&&(g=Ac(f),d=g[1],g[0].inRange(d)&&(e=Bc(f,e),f=Bc(f,xc(f)),d.collapse(!0),d.moveEnd("character",e-f),d.select()))}}else c.a.value=d;c.Ga=!0;a.kb?(a.q=null,sc(a)):a.u();a.dispatchEvent({type:"update",U:b});a.kb&&a.$.update(!0);return!0}a.u();a.dispatchEvent({type:"update",U:null});return!1}h.u=function(){this.D=-1;this.q=null;this.k+=this.c.length;this.c=[];window.clearTimeout(this.I);this.I=null;this.p.u();this.dispatchEvent("suggestionsupdate");this.dispatchEvent(oc)};
function sc(a){a.I||(a.I=window.setTimeout(u(a.u,a),100))}h.Ra=function(){return this.I?(window.clearTimeout(this.I),this.I=null,!0):!1};function rc(a){a.Ra()||window.setTimeout(u(a.Ra,a),10)}h.e=function(){kc.i.e.call(this);delete this.Sa;this.p.B();this.$.B();this.Q=null};h.Cb=function(a,b,c){this.q==a&&this.Ea(b,c)};
h.Ea=function(a,b){var c="object"==ba(b)&&b,d=(c?c.Sb():b)?pc(this,this.D):-1;this.k+=this.c.length;this.c=a;for(var e=[],f=0;f<a.length;++f)e.push({id:this.k+f,data:a[f]});f=null;this.g&&(f=this.Sa[fa(this.g)]||this.g);this.p.pb=f;this.p.Ea(e,this.q,this.g);f=this.qb;c&&void 0!==c.wb()&&(f=c.wb());this.D=-1;(f||0<=d)&&0!=e.length&&this.q&&(0<=d?this.A(this.k+d):uc(this));this.dispatchEvent("suggestionsupdate")};function pc(a,b){var c=b-a.k;return 0>c||c>=a.c.length?-1:c}
h.sa=function(a){var b=this.$;b.sa.apply(b,arguments)};h.update=function(a){this.$.update(a)};function Cc(a,b){X.call(this);this.P=a||1;this.V=b||m;this.ta=u(this.Mb,this);this.za=w()}x(Cc,X);h=Cc.prototype;h.enabled=!1;h.f=null;h.Mb=function(){if(this.enabled){var a=w()-this.za;0<a&&a<0.8*this.P?this.f=this.V.setTimeout(this.ta,this.P-a):(this.f&&(this.V.clearTimeout(this.f),this.f=null),this.dispatchEvent(Dc),this.enabled&&(this.f=this.V.setTimeout(this.ta,this.P),this.za=w()))}};h.start=function(){this.enabled=!0;this.f||(this.f=this.V.setTimeout(this.ta,this.P),this.za=w())};
h.stop=function(){this.enabled=!1;this.f&&(this.V.clearTimeout(this.f),this.f=null)};h.e=function(){Cc.i.e.call(this);this.stop();delete this.V};var Dc="tick";var Ec;function Fc(a,b){b?a.setAttribute("role",b):a.removeAttribute("role")}function Gc(a,b,c){ca(c)&&(c=c.join(" "));var d="aria-"+b;""===c||void 0==c?(Ec||(Ec={atomic:!1,autocomplete:"none",dropeffect:"none",haspopup:!1,live:"off",multiline:!1,multiselectable:!1,orientation:"vertical",readonly:!1,relevant:"additions text",required:!1,sort:"none",busy:!1,disabled:!1,hidden:!1,invalid:"false"}),c=Ec,b in c?a.setAttribute(d,c[b]):a.removeAttribute(d)):a.setAttribute(d,c)}
function Hc(a,b){var c="";b&&(c=b.id);Gc(a,"activedescendant",c)};function xc(a){var b;a:{var c=0,d=0;if(zc(a))c=a.selectionStart,d=-1;else if(C){var e=Ac(a);b=e[0];e=e[1];if(b.inRange(e)){b.setEndPoint("EndToStart",e);if("textarea"==a.type){e.duplicate();c=a=b.text;for(d=!1;!d;)0==b.compareEndPoints("StartToEnd",b)?d=!0:(b.moveEnd("character",-1),b.text==a?c+="\r\n":d=!0);b=[c.length,-1];break a}c=b.text.length;d=-1}}b=[c,d]}return b[0]}
function Ac(a){var b=a.ownerDocument||a.document,c=b.selection.createRange();"textarea"==a.type?(b=b.body.createTextRange(),b.moveToElementText(a)):b=a.createTextRange();return[b,c]}function Bc(a,b){"textarea"==a.type&&(b=a.value.substring(0,b).replace(/(\r\n|\r|\n)/g,"\n").length);return b}function zc(a){try{return"number"==typeof a.selectionStart}catch(b){return!1}};function Ic(a){J.call(this);this.Y=a;this.ja={}}x(Ic,J);var Jc=[];h=Ic.prototype;h.o=function(a,b,c,d,e){r(b)||(Jc[0]=b,b=Jc);for(var f=0;f<b.length;f++){var g=N(a,b[f],c||this,d||!1,e||this.Y||this);if(!g)break;this.ja[g.key]=g}return this};h.s=function(a,b,c,d,e){if(r(b))for(var f=0;f<b.length;f++)this.s(a,b[f],c,d,e);else e=e||this.Y||this,c=qb(c||this),d=!!d,b=cb(a)?a.X(b,c,d,e):a?(a=rb(a))?a.X(b,c,d,e):null:null,b&&(O(b),delete this.ja[b.key]);return this};
h.ma=function(){gb(this.ja,O);this.ja={}};h.e=function(){Ic.i.e.call(this);this.ma()};h.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function Kc(a,b,c,d,e){if(!(C||E&&F("525")))return!0;if(A&&e)return Lc(a);if(e&&!d||!c&&(17==b||18==b||A&&91==b))return!1;if(E&&d&&c)switch(a){case 220:case 219:case 221:case 192:case 186:case 189:case 187:case 188:case 190:case 191:case 192:case 222:return!1}if(C&&d&&b==a)return!1;switch(a){case 13:return!(C&&C&&9<=G);case 27:return!E}return Lc(a)}
function Lc(a){if(48<=a&&57>=a||96<=a&&106>=a||65<=a&&90>=a||E&&0==a)return!0;switch(a){case 32:case 63:case 107:case 109:case 110:case 111:case 186:case 59:case 189:case 187:case 61:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:return!0;default:return!1}}function Mc(a){switch(a){case 61:return 187;case 59:return 186;case 173:return 189;case 224:return 91;case 0:return 224;default:return a}};function Nc(a,b){X.call(this);a&&Oc(this,a,b)}x(Nc,X);h=Nc.prototype;h.b=null;h.ha=null;h.xa=null;h.ia=null;h.m=-1;h.F=-1;h.ra=!1;
var Pc={3:13,12:144,63232:38,63233:40,63234:37,63235:39,63236:112,63237:113,63238:114,63239:115,63240:116,63241:117,63242:118,63243:119,63244:120,63245:121,63246:122,63247:123,63248:44,63272:46,63273:36,63275:35,63276:33,63277:34,63289:144,63302:45},Qc={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},Rc=C||E&&F("525"),Sc=A&&D;h=Nc.prototype;
h.yb=function(a){E&&(17==this.m&&!a.ctrlKey||18==this.m&&!a.altKey||A&&91==this.m&&!a.metaKey)&&(this.F=this.m=-1);-1==this.m&&(a.ctrlKey&&17!=a.keyCode?this.m=17:a.altKey&&18!=a.keyCode?this.m=18:a.metaKey&&91!=a.keyCode&&(this.m=91));Rc&&!Kc(a.keyCode,this.m,a.shiftKey,a.ctrlKey,a.altKey)?this.handleEvent(a):(this.F=D?Mc(a.keyCode):a.keyCode,Sc&&(this.ra=a.altKey))};h.Ab=function(a){this.F=this.m=-1;this.ra=a.altKey};
h.handleEvent=function(a){var b=a.N,c,d,e=b.altKey;C&&"keypress"==a.type?(c=this.F,d=13!=c&&27!=c?b.keyCode:0):E&&"keypress"==a.type?(c=this.F,d=0<=b.charCode&&63232>b.charCode&&Lc(c)?b.charCode:0):B?(c=this.F,d=Lc(c)?b.keyCode:0):(c=b.keyCode||this.F,d=b.charCode||0,Sc&&(e=this.ra),A&&63==d&&224==c&&(c=191));var f=c,g=b.keyIdentifier;c?63232<=c&&c in Pc?f=Pc[c]:25==c&&a.shiftKey&&(f=9):g&&g in Qc&&(f=Qc[g]);a=f==this.m;this.m=f;b=new Tc(f,d,a,b);b.altKey=e;this.dispatchEvent(b)};
function Oc(a,b,c){a.ia&&a.detach();a.b=b;a.ha=N(a.b,"keypress",a,c);a.xa=N(a.b,"keydown",a.yb,c,a);a.ia=N(a.b,"keyup",a.Ab,c,a)}h.detach=function(){this.ha&&(O(this.ha),O(this.xa),O(this.ia),this.ia=this.xa=this.ha=null);this.b=null;this.F=this.m=-1};h.e=function(){Nc.i.e.call(this);this.detach()};function Tc(a,b,c,d){d&&ab(this,d,void 0);this.type="key";this.keyCode=a;this.charCode=b;this.repeat=c}x(Tc,L);var Uc,Vc;Vc=Uc=!1;var Wc=Ga();Wc&&(-1!=Wc.indexOf("Firefox")||-1!=Wc.indexOf("Camino")||(-1!=Wc.indexOf("iPhone")||-1!=Wc.indexOf("iPod")?Uc=!0:-1!=Wc.indexOf("iPad")&&(Vc=!0)));var Xc=Uc,Yc=Vc;function Zc(a,b,c,d){J.call(this);d=d||150;this.R=null!=c?c:!0;this.aa=a||",;";this.sb=this.aa.substring(0,1);a=this.R?"[\\s"+this.aa+"]+":"[\\s]+";this.lb=RegExp("^"+a+"|"+a+"$","g");this.Ib=RegExp("\\s*["+this.aa+"]$");this.Wa=b||"";this.Fb=this.R;this.f=0<d?new Cc(d):null;this.h=new Ic(this);this.pa=new Ic(this);this.Z=new Nc;this.Ua=-1}x(Zc,J);var $c=(Xc||Yc)&&!F("533.17.9");h=Zc.prototype;h.Qb=!0;h.vb=!0;h.mb=!1;h.Kb=!0;h.Jb=!0;h.qa=null;h.a=null;h.ya="";h.H=!1;h.Ga=!1;h.Nb=!0;
h.sa=function(a){for(var b=0;b<arguments.length;b++){var c=arguments[b];ea(c)&&1==c.nodeType&&Gc(c,"haspopup",!0);this.h.o(c,"focus",this.Oa);this.h.o(c,"blur",this.xb);if(!this.a&&(this.pa.o(c,"keydown",this.Eb),ea(c)&&1==c.nodeType)){var d;a:{var e=R(c);try{d=e&&e.activeElement;break a}catch(f){}d=null}d==c&&ad(this,c)}}};h.e=function(){Zc.i.e.call(this);null!=this.qa&&window.clearTimeout(this.qa);this.h.B();delete this.h;this.pa.B();this.Z.B();Za(this.f)};
function bd(a,b){switch(b.keyCode){case 40:if(a.d.p.t){a.mb?vc(a.d):uc(a.d);b.preventDefault();return}if(!a.R){a.update(!0);b.preventDefault();return}break;case 38:if(a.d.p.t){a.mb?uc(a.d):vc(a.d);b.preventDefault();return}break;case 9:if(a.d.p.t&&!b.shiftKey){if(a.update(),qc(a.d)&&a.Fb){b.preventDefault();return}}else a.d.u();break;case 13:if(a.d.p.t){if(a.update(),qc(a.d)){b.preventDefault();b.stopPropagation();return}}else a.d.u();break;case 27:if(a.d.p.t){a.d.u();b.preventDefault();b.stopPropagation();
return}break;case 229:if(!a.H){a.H||(a.h.o(a.a,"keyup",a.bb),a.h.o(a.a,"keypress",a.ab),a.H=!0);return}break;default:a.f&&!a.Nb&&(a.f.stop(),a.f.start())}cd(a,b)}function cd(a,b){var c=a.R&&b.charCode&&-1!=a.aa.indexOf(String.fromCharCode(b.charCode));a.Kb&&c&&a.update();a.Jb&&c&&qc(a.d)&&b.preventDefault()}h.zb=function(){return!1};h.Oa=function(a){ad(this,a.target||null)};
function ad(a,b){a.pa.ma();a.d&&rc(a.d);b!=a.a&&(a.a=b,a.f&&(a.f.start(),a.h.o(a.f,Dc,a.fb)),a.ya=a.a.value,Oc(a.Z,a.a),a.h.o(a.Z,"key",a.cb),a.h.o(a.a,"mousedown",a.eb),C&&a.h.o(a.a,"keypress",a.$a))}h.xb=function(){$c?this.qa=window.setTimeout(u(this.gb,this),0):this.gb()};
h.gb=function(){this.a&&(this.h.s(this.Z,"key",this.cb),this.Z.detach(),this.h.s(this.a,"keyup",this.zb),this.h.s(this.a,"mousedown",this.eb),C&&this.h.s(this.a,"keypress",this.$a),this.H&&dd(this),this.a=null,this.f&&(this.f.stop(),this.h.s(this.f,Dc,this.fb)),this.d&&sc(this.d))};h.fb=function(){this.update()};h.Eb=function(a){this.Oa(a)};h.cb=function(a){this.Ua=a.keyCode;this.d&&bd(this,a)};h.ab=function(){this.H&&229!=this.Ua&&dd(this)};
h.bb=function(a){this.H&&(13==a.keyCode||77==a.keyCode&&a.ctrlKey)&&dd(this)};h.eb=function(){};function dd(a){a.H&&(a.H=!1,a.h.s(a.a,"keypress",a.ab),a.h.s(a.a,"keyup",a.bb))}h.$a=function(a){cd(this,a)};
h.update=function(a){if(this.a&&(a||this.a.value!=this.ya)){if(a||!this.Ga){var b;a=xc(this.a);b=this.a.value;a=yc(this,b)[wc(this,b,a)];b=this.lb?String(a).replace(this.lb,""):a;if(this.d&&(this.d.g=this.a,a=this.d,a.q!=b)){a.q=b;var c=a.Q;b=a.q;var d=a.Xa,e=u(a.Cb,a);if(c.Ob){var c=c.c,f=hc(b,d,c);0==f.length&&(f=ic(b,d,c));d=f}else d=hc(b,d,c.c);e(b,d);rc(a)}}this.ya=this.a.value}this.Ga=!1};
function wc(a,b,c){a=yc(a,b);if(c==b.length)return a.length-1;for(var d=b=0,e=0;d<a.length&&e<=c;d++)e+=a[d].length,b=d;return b}function yc(a,b){if(!a.R)return[b];for(var c=String(b).split(""),d=[],e=[],f=0,g=!1;f<c.length;f++)a.Wa&&-1!=a.Wa.indexOf(c[f])?(a.vb&&!g&&(d.push(e.join("")),e.length=0),e.push(c[f]),g=!g):g||-1==a.aa.indexOf(c[f])?e.push(c[f]):(e.push(c[f]),d.push(e.join("")),e.length=0);d.push(e.join(""));return d};var ed=!!m.DOMTokenList,fd=ed?function(a){return a.classList}:function(a){a=a.className;return t(a)&&a.match(/\S+/g)||[]},gd=ed?function(a,b){return a.classList.contains(b)}:function(a,b){var c=fd(a);return 0<=va(c,b)},hd=ed?function(a,b){a.classList.add(b)}:function(a,b){gd(a,b)||(a.className+=0<a.className.length?" "+b:b)},id=ed?function(a,b){z(b,function(b){hd(a,b)})}:function(a,b){var c={};z(fd(a),function(a){c[a]=!0});z(b,function(a){c[a]=!0});a.className="";for(var d in c)a.className+=0<a.className.length?
" "+d:d},jd=ed?function(a,b){a.classList.remove(b)}:function(a,b){gd(a,b)&&(a.className=wa(fd(a),function(a){return a!=b}).join(" "))},kd=ed?function(a,b){z(b,function(b){jd(a,b)})}:function(a,b){a.className=wa(fd(a),function(a){return!(0<=va(b,a))}).join(" ")};function ld(){X.call(this);this.r=md;this.Ma=this.startTime=null}x(ld,X);var md=0;ld.prototype.K=function(){this.v("begin")};ld.prototype.S=function(){this.v("end")};ld.prototype.v=function(a){this.dispatchEvent(a)};function nd(a,b,c){J.call(this);this.Aa=a;this.P=b||0;this.Y=c;this.rb=u(this.tb,this)}x(nd,J);h=nd.prototype;h.O=0;h.e=function(){nd.i.e.call(this);this.stop();delete this.Aa;delete this.Y};h.start=function(a){this.stop();var b=this.rb;a=void 0!==a?a:this.P;if(!da(b))if(b&&"function"==typeof b.handleEvent)b=u(b.handleEvent,b);else throw Error("Invalid listener argument");this.O=2147483647<a?-1:m.setTimeout(b,a||0)};h.stop=function(){0!=this.O&&m.clearTimeout(this.O);this.O=0};
h.tb=function(){this.O=0;this.Aa&&this.Aa.call(this.Y)};var ib={},od=null;function pd(a){a=fa(a);delete ib[a];hb()&&od&&od.stop()}function qd(){od||(od=new nd(function(){rd()},20));var a=od;0!=a.O||a.start()}function rd(){var a=w();gb(ib,function(b){sd(b,a)});hb()||qd()};function td(a,b,c,d){ld.call(this);if(!r(a)||!r(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.ba=a;this.ub=b;this.duration=c;this.Ha=d;this.coords=[]}x(td,ld);h=td.prototype;h.n=0;
h.play=function(a){if(a||this.r==md)this.n=0,this.coords=this.ba;else if(1==this.r)return!1;pd(this);this.startTime=a=w();-1==this.r&&(this.startTime-=this.duration*this.n);this.Ma=this.startTime+this.duration;this.n||this.K();this.v("play");-1==this.r&&this.v("resume");this.r=1;var b=fa(this);b in ib||(ib[b]=this);qd();sd(this,a);return!0};h.stop=function(a){pd(this);this.r=md;a&&(this.n=1);ud(this,this.n);this.v("stop");this.S()};h.e=function(){this.r==md||this.stop(!1);this.v("destroy");td.i.e.call(this)};
function sd(a,b){a.n=(b-a.startTime)/(a.Ma-a.startTime);1<=a.n&&(a.n=1);ud(a,a.n);1==a.n?(a.r=md,pd(a),a.v("finish"),a.S()):1==a.r&&a.Ba()}function ud(a,b){da(a.Ha)&&(b=a.Ha(b));a.coords=Array(a.ba.length);for(var c=0;c<a.ba.length;c++)a.coords[c]=(a.ub[c]-a.ba[c])*b+a.ba[c]}h.Ba=function(){this.v("animate")};h.v=function(a){this.dispatchEvent(new vd(a,this))};
function vd(a,b){K.call(this,a);this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.n=b.n;this.state=b.r}x(vd,K);function Y(a,b,c,d,e){td.call(this,b,c,d,e);this.element=a}x(Y,td);Y.prototype.oa=aa;Y.prototype.Ba=function(){this.oa();Y.i.Ba.call(this)};Y.prototype.S=function(){this.oa();Y.i.S.call(this)};Y.prototype.K=function(){this.oa();Y.i.K.call(this)};function wd(a,b,c,d,e){"number"==typeof b&&(b=[b]);"number"==typeof c&&(c=[c]);Y.call(this,a,b,c,d,e);if(1!=b.length||1!=c.length)throw Error("Start and end points must be 1D");}x(wd,Y);
wd.prototype.oa=function(){var a=this.coords[0],b=this.element.style;"opacity"in b?b.opacity=a:"MozOpacity"in b?b.MozOpacity=a:"filter"in b&&(b.filter=""===a?"":"alpha(opacity="+100*a+")")};wd.prototype.show=function(){this.element.style.display=""};function xd(a,b,c){wd.call(this,a,1,0,b,c)}x(xd,wd);xd.prototype.K=function(){this.show();xd.i.K.call(this)};xd.prototype.S=function(){this.element.style.display="none";xd.i.S.call(this)};function yd(a,b,c){wd.call(this,a,0,1,b,c)}x(yd,wd);
yd.prototype.K=function(){this.show();yd.i.K.call(this)};function Z(){}Z.ua=function(){return Z.Ta?Z.Ta:Z.Ta=new Z};Z.prototype.Ya=0;Z.ua();function zd(a,b,c,d){X.call(this);this.Da=a||document.body;this.w=Q(this.Da);this.Gb=!a;this.b=null;this.q="";this.c=[];this.L=[];this.jb=this.ga=-1;this.t=!1;this.className="ac-renderer";this.Fa="ac-row";this.Va="active";this.Ia="ac-active";this.Bb="ac-highlighted";this.ea=b||null;this.Pb=null!=d?d:!0;this.Db=!0;this.va=!1;this.Hb=!!c;this.na=!1;this.ka=0}x(zd,X);h=zd.prototype;h.Ea=function(a,b,c){this.q=b;this.c=a;this.ga=-1;this.jb=w();this.g=c;this.L=[];Ad(this)};
h.u=function(){this.g&&Hc(this.g,null);this.t&&(this.t=!1,this.g&&Gc(this.g,"haspopup",!1),0<this.ka?(Za(this.M),this.M=new xd(this.b,this.ka),this.M.play()):this.b.style.display="none")};h.show=function(){this.t||(this.t=!0,this.g&&(Fc(this.g,"combobox"),Gc(this.g,"autocomplete","list"),Gc(this.g,"haspopup",!0)),0<this.ka?(Za(this.M),this.M=new yd(this.b,this.ka),this.M.play()):this.b.style.display="")};
function Bd(a,b){var c=0<=b&&b<a.c.length?a.c[b]:void 0,d=0<=b&&b<a.L.length?a.L[b]:void 0;if(a.dispatchEvent({type:"rowhilite",Vb:d,U:c?c.data:null})&&(0<=a.ga&&kd(a.L[a.ga],[a.Ia,a.Va]),a.ga=b,d)){id(d,[a.Ia,a.Va]);a.g&&Hc(a.g,d);var c=a.b,e=W(d),f=W(c),g=ac(c),k=e.x-f.x-g.left,e=e.y-f.y-g.top,f=c.clientHeight-d.offsetHeight,g=c.scrollLeft,l=c.scrollTop,g=g+Math.min(k,Math.max(k-(c.clientWidth-d.offsetWidth),0)),l=l+Math.min(e,Math.max(e-f,0)),d=new P(g,l);c.scrollLeft=d.x;c.scrollTop=d.y}}
h.A=function(a){if(-1==a)Bd(this,-1);else for(var b=0;b<this.c.length;b++)if(this.c[b].id==a){Bd(this,b);break}};function Cd(a){if(!a.b){var b=a.w.Ka("div",{style:"display:none"});a.b=b;id(b,ma(a.className).split(" "));Fc(b,"listbox");b.id=":"+(Z.ua().Ya++).toString(36);a.w.appendChild(a.Da,b);N(b,"click",a.Na,!1,a);N(b,"mousedown",a.Pa,!1,a);N(b,"mouseover",a.Qa,!1,a)}}
function Ad(a){Cd(a);a.na&&(a.b.style.visibility="hidden");a.Rb&&(a.b.style.minWidth=a.Rb.clientWidth+"px");a.L.length=0;Nb(a.b);if(!a.ea||!a.ea.Tb){var b=null;z(a.c,function(a){var d=this.q,e=this.w.Ka("div",{className:this.Fa,id:":"+(Z.ua().Ya++).toString(36)});Fc(e,"option");this.ea&&this.ea.Ub||(e.innerHTML=na(a.data.toString()));d&&this.Pb&&Dd(this,e,d);hd(e,this.Fa);this.L.push(e);a=e;this.na?this.b.insertBefore(a,b):this.w.appendChild(this.b,a);b=a},a)}0==a.c.length?a.u():(a.show(),Ed(a),Wb(a.b))}
function Ed(a){if(a.g&&a.Gb){var b,c=a.Hb?3:1;a.na&&(c^=1);b=c;var d=a.pb||a.g,c=a.b,e=b^1,f,g;if(f=c.offsetParent){var k="HTML"==f.tagName||"BODY"==f.tagName;k&&"static"==V(f,"position")||(g=W(f),k||(k=(k=Rb(f))&&D?-f.scrollLeft:!k||C&&F("8")||"visible"==V(f,"overflowX")?f.scrollLeft:f.scrollWidth-f.clientWidth-f.scrollLeft,g=Ab(g,new P(k,f.scrollTop))))}f=g||new P;g=W(d);k=Tb(d);g=new T(g.x,g.y,k.width,k.height);if(k=Qb(d)){var l=new T(k.left,k.top,k.right-k.left,k.bottom-k.top),k=Math.max(g.left,
l.left),n=Math.min(g.left+g.width,l.left+l.width);if(k<=n){var p=Math.max(g.top,l.top),l=Math.min(g.top+g.height,l.top+l.height);p<=l&&(g.left=k,g.top=p,g.width=n-k,g.height=l-p)}}k=Q(d);p=Q(c);if(k.j!=p.j){var n=k.j.body,p=p.j.parentWindow||p.j.defaultView,l=new P(0,0),q=R(n)?R(n).parentWindow||R(n).defaultView:window,H=n;do{var s;if(q==p)s=W(H);else{s=H;var I=void 0;if(s.getBoundingClientRect)I=Ob(s),I=new P(I.left,I.top);else var I=Mb(Q(s)),v=W(s),I=new P(v.x-I.x,v.y-I.y);v=void 0;if(D&&!F(12)){v=
void 0;v=void 0;C?v="-ms-transform":E?v="-webkit-transform":B?v="-o-transform":D&&(v="-moz-transform");var sa=void 0;v&&(sa=V(s,v));sa||(sa=V(s,"transform"));v=sa?(s=sa.match(fc))?new P(parseFloat(s[1]),parseFloat(s[2])):new P(0,0):new P(0,0);v=new P(I.x+v.x,I.y+v.y)}else v=I;s=v}l.x+=s.x;l.y+=s.y}while(q&&q!=p&&(H=q.frameElement)&&(q=q.parent));n=Ab(l,W(n));C&&!Lb(k)&&(n=Ab(n,Mb(k)));g.left+=n.x;g.top+=n.y}b=(b&4&&Rb(d)?b^2:b)&-5;b=new P(b&2?g.left+g.width:g.left,b&1?g.top+g.height:g.top);b=Ab(b,
f);if(d=Qb(c))d.top-=f.y,d.right-=f.x,d.bottom-=f.y,d.left-=f.x;f=b.W();g=(e&4&&Rb(c)?e^2:e)&-5;b=Tb(c);e=b.W();0!=g&&(g&2&&(f.x-=e.width+0),g&1&&(f.y-=e.height+0));d?(g=f,k=65,n=0,65==(k&65)&&(g.x<d.left||g.x>=d.right)&&(k&=-2),132==(k&132)&&(g.y<d.top||g.y>=d.bottom)&&(k&=-5),g.x<d.left&&k&1&&(g.x=d.left,n|=1),g.x<d.left&&g.x+e.width>d.right&&k&16&&(e.width=Math.max(e.width-(g.x+e.width-d.right),0),n|=4),g.x+e.width>d.right&&k&1&&(g.x=Math.max(d.right-e.width,d.left),n|=1),k&2&&(n=n|(g.x<d.left?
16:0)|(g.x+e.width>d.right?32:0)),g.y<d.top&&k&4&&(g.y=d.top,n|=2),g.y<=d.top&&g.y+e.height<d.bottom&&k&32&&(e.height=Math.max(e.height-(d.top-g.y),0),g.y=d.top,n|=8),g.y>=d.top&&g.y+e.height>d.bottom&&k&32&&(e.height=Math.max(e.height-(g.y+e.height-d.bottom),0),n|=8),g.y+e.height>d.bottom&&k&4&&(g.y=Math.max(d.bottom-e.height,d.top),n|=2),k&8&&(n=n|(g.y<d.top?64:0)|(g.y+e.height>d.bottom?128:0)),d=n):d=256;d&496||(g=f,f=D&&(A||La)&&F("1.9"),g instanceof P?(d=g.x,g=g.y):(d=g,g=void 0),c.style.left=
Sb(d,f),c.style.top=Sb(g,f),b==e||b&&e&&b.width==e.width&&b.height==e.height||(d=Lb(Q(R(c))),!C||d&&F("8")?(c=c.style,D?c.MozBoxSizing="border-box":E?c.WebkitBoxSizing="border-box":c.boxSizing="border-box",c.width=Math.max(e.width,0)+"px",c.height=Math.max(e.height,0)+"px"):(b=c.style,d?(C?(d=Yb(c,"paddingLeft"),f=Yb(c,"paddingRight"),g=Yb(c,"paddingTop"),k=Yb(c,"paddingBottom"),d=new S(g,f,k,d)):(d=U(c,"paddingLeft"),f=U(c,"paddingRight"),g=U(c,"paddingTop"),k=U(c,"paddingBottom"),d=new S(parseFloat(g),
parseFloat(f),parseFloat(k),parseFloat(d))),c=ac(c),b.pixelWidth=e.width-c.left-d.left-d.right-c.right,b.pixelHeight=e.height-c.top-d.top-d.bottom-c.bottom):(b.pixelWidth=e.width,b.pixelHeight=e.height))));a.na&&(a.b.style.visibility="visible")}}h.e=function(){this.b&&(ub(this.b,"click",this.Na,!1,this),ub(this.b,"mousedown",this.Pa,!1,this),ub(this.b,"mouseover",this.Qa,!1,this),this.w.removeNode(this.b),this.b=null,this.t=!1);Za(this.M);this.Da=null;zd.i.e.call(this)};
function Dd(a,b,c){if(3==b.nodeType){var d=null;r(c)&&1<c.length&&!a.va&&(d=Ba(c,1));c=Fd(a,c);if(0!=c.length){var e=b.nodeValue,f=a.Db?RegExp("\\b(?:"+c+")","gi"):RegExp(c,"gi");c=[];for(var g=0,k=f.exec(e),l=0;k;)l++,c.push(e.substring(g,k.index)),c.push(e.substring(k.index,f.lastIndex)),g=f.lastIndex,k=f.exec(e);c.push(e.substring(g));if(1<c.length){d=a.va?l:1;for(e=0;e<d;e++)f=2*e,b.nodeValue=c[f],g=a.w.createElement("b"),g.className=a.Bb,a.w.appendChild(g,a.w.createTextNode(c[f+1])),g=b.parentNode.insertBefore(g,
b.nextSibling),b.parentNode.insertBefore(a.w.createTextNode(""),g.nextSibling),b=g.nextSibling;a=Ba(c,2*d);b.nodeValue=a.join("")}else d&&Dd(a,b,d)}}else for(b=b.firstChild;b;)d=b.nextSibling,Dd(a,b,c),b=d}
function Fd(a,b){var c="";if(!b)return c;r(b)&&(b=wa(b,function(a){return!/^[\s\xa0]*$/.test(null==a?"":String(a))}));a.va?r(b)?c=xa(b,ua).join("|"):(c=b.replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,""),c=ua(c),c=c.replace(/ /g,"|")):r(b)?c=0<b.length?ua(b[0]):"":/^\W/.test(b)||(c=ua(b));return c}function Gd(a,b){for(;b&&b!=a.b&&!gd(b,a.Fa);)b=b.parentNode;return b?va(a.L,b):-1}h.Na=function(a){var b=Gd(this,a.target);0<=b&&this.dispatchEvent({type:mc,U:this.c[b].id});a.stopPropagation()};
h.Pa=function(a){a.stopPropagation();a.preventDefault()};h.Qa=function(a){a=Gd(this,a.target);0<=a&&!(300>w()-this.jb)&&this.dispatchEvent({type:lc,U:this.c[a].id})};function Hd(a,b){var c=new gc(a),d=new zd,e=new Zc(null,null,!1),c=new kc(c,d,e);e.d=c;e.sa(b);return c};/*
 Copyright 2013 Jason Leyba

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/
function Id(){var a=m.TYPES;Jd(a);setTimeout(ka(Kd,a),0);setTimeout(Ld,0)}var Md=["init"],$=m;Md[0]in $||!$.execScript||$.execScript("var "+Md[0]);for(var Nd;Md.length&&(Nd=Md.shift());)Md.length||void 0===Id?$=$[Nd]?$[Nd]:$[Nd]={}:$[Nd]=Id;var Od=function(){var a="./";ya(function(b){b=b.src;var c=b.length;return"dossier.js"===b.substr(c-10)?(a=b.substr(0,c-10),!0):!1});return a}();
function Kd(a){function b(a){c[a.name]=a.href;return a.name}var c={};a=za(xa(a.files,b),xa(a.types,b));var d=Db("searchbox"),e=d.getElementsByTagName("input")[0];tc(Hd(a,e));N(d,"submit",function(a){a.preventDefault();a.stopPropagation();if(a=c[e.value])window.location.href=Od+a;return!1})}
function Jd(a){if(Db("sidenav")){var b=Db("sidenav-types-ctrl"),c=Pd("sidenav-types",a.types),d=Db("sidenav-files-ctrl"),e=Pd("sidenav-files",a.files);a=ec();var f=Tb(c).height/a+"rem",g=Tb(e).height/a+"rem";c.style.height=Sb(0,!0);e.style.height=Sb(0,!0);N(b,"change",function(){c.style.height=Sb(b.checked?f:0,!0)});N(d,"change",function(){e.style.height=Sb(d.checked?g:0,!0)})}}
function Pd(a,b){var c=Db(a),d=c.querySelector("i");if(!b.length)return d;Kb(d);var e=document.createElement("UL");z(b,function(a){if(!a.isTypedef){var b=a.name;a.isInterface&&(b=Hb("I",null,b));a=Hb("LI",null,Hb("A",{href:Od+a.href},b));e.appendChild(a)}});c.appendChild(e);return e}
function Ld(){var a=document.getElementsByTagName("DETAILS");a.length&&!a[0].hasOwnProperty("open")&&z(a,function(a){function c(){(d=!d)?a.setAttribute("open",""):a.removeAttribute("open");z(a.childNodes,function(a){1===a.nodeType&&"SUMMARY"!==a.tagName.toUpperCase()&&(a.style.display=d?"":"none")})}var d=!0;a.setAttribute("open","");N(a,"click",c);c()})};;init();})();
