(function(){var h,m=this;function aa(){}
function ba(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}function r(a){return"array"==ba(a)}function ca(a){var b=ba(a);return"array"==b||"object"==b&&"number"==typeof a.length}function s(a){return"string"==typeof a}function da(a){return"function"==ba(a)}function ea(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function fa(a){return a[ga]||(a[ga]=++ha)}var ga="closure_uid_"+(1E9*Math.random()>>>0),ha=0;function ia(a,b,c){return a.call.apply(a.bind,arguments)}
function ja(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function u(a,b,c){u=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ia:ja;return u.apply(null,arguments)}var w=Date.now||function(){return+new Date};
function x(a,b){function c(){}c.prototype=b.prototype;a.j=b.prototype;a.prototype=new c};function ka(a){if(!la.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(ma,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(na,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(oa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(qa,"&quot;"));return a}var ma=/&/g,na=/</g,oa=/>/g,qa=/\"/g,la=/[&<>\"]/;function ra(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};var y=Array.prototype,z=y.indexOf?function(a,b,c){return y.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(s(a))return s(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},sa=y.forEach?function(a,b,c){y.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=s(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},ta=y.filter?function(a,b,c){return y.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=s(a)?
a.split(""):a,k=0;k<d;k++)if(k in g){var l=g[k];b.call(c,l,k,a)&&(e[f++]=l)}return e},ua=y.map?function(a,b,c){return y.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=s(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};function va(a){a:for(var b=document.getElementsByTagName("script"),c=b.length,d=s(b)?b.split(""):b,e=0;e<c;e++)if(e in d&&a.call(void 0,d[e],e,b))break a}function wa(a,b){return 0<=z(a,b)}function xa(a){return y.concat.apply(y,arguments)}
function ya(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function za(a,b,c){return 2>=arguments.length?y.slice.call(a,b):y.slice.call(a,b,c)};var Aa,Ba,Ca,Da,A;function Ea(){return m.navigator?m.navigator.userAgent:null}function Fa(){return m.navigator}Da=Ca=Ba=Aa=!1;var Ga;if(Ga=Ea()){var Ha=Fa();Aa=0==Ga.lastIndexOf("Opera",0);Ba=!Aa&&(-1!=Ga.indexOf("MSIE")||-1!=Ga.indexOf("Trident"));Ca=!Aa&&-1!=Ga.indexOf("WebKit");Da=!Aa&&!Ca&&!Ba&&"Gecko"==Ha.product}var B=Aa,C=Ba,D=Da,E=Ca,Ia=Fa();A=-1!=(Ia&&Ia.platform||"").indexOf("Mac");var Ja=!!Fa()&&-1!=(Fa().appVersion||"").indexOf("X11");
function Ka(){var a=m.document;return a?a.documentMode:void 0}var La;a:{var Ma="",Na;if(B&&m.opera)var Oa=m.opera.version,Ma="function"==typeof Oa?Oa():Oa;else if(D?Na=/rv\:([^\);]+)(\)|;)/:C?Na=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:E&&(Na=/WebKit\/(\S+)/),Na)var Pa=Na.exec(Ea()),Ma=Pa?Pa[1]:"";if(C){var Qa=Ka();if(Qa>parseFloat(Ma)){La=String(Qa);break a}}La=Ma}var Ra={};
function F(a){var b;if(!(b=Ra[a])){b=0;for(var c=String(La).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",k=d[f]||"",l=RegExp("(\\d*)(\\D*)","g"),n=RegExp("(\\d*)(\\D*)","g");do{var p=l.exec(g)||["","",""],q=n.exec(k)||["","",""];if(0==p[0].length&&0==q[0].length)break;b=((0==p[1].length?0:parseInt(p[1],10))<(0==q[1].length?0:parseInt(q[1],10))?-1:(0==p[1].length?0:parseInt(p[1],
10))>(0==q[1].length?0:parseInt(q[1],10))?1:0)||((0==p[2].length)<(0==q[2].length)?-1:(0==p[2].length)>(0==q[2].length)?1:0)||(p[2]<q[2]?-1:p[2]>q[2]?1:0)}while(0==b)}b=Ra[a]=0<=b}return b}var Sa=m.document,G=Sa&&C?Ka()||("CSS1Compat"==Sa.compatMode?parseInt(La,10):5):void 0;var Ta=!C||C&&9<=G,Ua=C&&!F("9");!E||F("528");D&&F("1.9b")||C&&F("8")||B&&F("9.5")||E&&F("528");D&&!F("8")||C&&F("9");function J(){0!=Va&&(Wa[fa(this)]=this)}var Va=0,Wa={};J.prototype.La=!1;J.prototype.B=function(){if(!this.La&&(this.La=!0,this.e(),0!=Va)){var a=fa(this);delete Wa[a]}};J.prototype.e=function(){if(this.Ya)for(;this.Ya.length;)this.Ya.shift()()};function Xa(a){a&&"function"==typeof a.B&&a.B()};function K(a,b){this.type=a;this.currentTarget=this.target=b}h=K.prototype;h.e=function(){};h.B=function(){};h.G=!1;h.defaultPrevented=!1;h.gb=!0;h.stopPropagation=function(){this.G=!0};h.preventDefault=function(){this.defaultPrevented=!0;this.gb=!1};function Ya(a){Ya[" "](a);return a}Ya[" "]=aa;function L(a,b){a&&Za(this,a,b)}x(L,K);h=L.prototype;h.target=null;h.relatedTarget=null;h.offsetX=0;h.offsetY=0;h.clientX=0;h.clientY=0;h.screenX=0;h.screenY=0;h.button=0;h.keyCode=0;h.charCode=0;h.ctrlKey=!1;h.altKey=!1;h.shiftKey=!1;h.metaKey=!1;h.N=null;
function Za(a,b,c){var d=a.type=b.type;K.call(a,d);a.target=b.target||b.srcElement;a.currentTarget=c;if(c=b.relatedTarget){if(D){var e;a:{try{Ya(c.nodeName);e=!0;break a}catch(f){}e=!1}e||(c=null)}}else"mouseover"==d?c=b.fromElement:"mouseout"==d&&(c=b.toElement);a.relatedTarget=c;a.offsetX=E||void 0!==b.offsetX?b.offsetX:b.layerX;a.offsetY=E||void 0!==b.offsetY?b.offsetY:b.layerY;a.clientX=void 0!==b.clientX?b.clientX:b.pageX;a.clientY=void 0!==b.clientY?b.clientY:b.pageY;a.screenX=b.screenX||0;
a.screenY=b.screenY||0;a.button=b.button;a.keyCode=b.keyCode||0;a.charCode=b.charCode||("keypress"==d?b.keyCode:0);a.ctrlKey=b.ctrlKey;a.altKey=b.altKey;a.shiftKey=b.shiftKey;a.metaKey=b.metaKey;a.state=b.state;a.N=b;b.defaultPrevented&&a.preventDefault();delete a.G}h.stopPropagation=function(){L.j.stopPropagation.call(this);this.N.stopPropagation?this.N.stopPropagation():this.N.cancelBubble=!0};
h.preventDefault=function(){L.j.preventDefault.call(this);var a=this.N;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Ua)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};h.e=function(){};var $a="closure_listenable_"+(1E6*Math.random()|0);function ab(a){try{return!(!a||!a[$a])}catch(b){return!1}}var bb=0;function cb(a,b,c,d,e){this.J=a;this.la=null;this.src=b;this.type=c;this.capture=!!d;this.fa=e;this.key=++bb;this.T=this.da=!1}function db(a){a.T=!0;a.J=null;a.la=null;a.src=null;a.fa=null};function eb(a,b){for(var c in a)b.call(void 0,a[c],c,a)}function fb(){var a=gb,b;for(b in a)return!1;return!0}var hb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function ib(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<hb.length;f++)c=hb[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function M(a){this.src=a;this.l={};this.ca=0}M.prototype.add=function(a,b,c,d,e){var f=this.l[a];f||(f=this.l[a]=[],this.ca++);var g=jb(f,b,d,e);-1<g?(a=f[g],c||(a.da=!1)):(a=new cb(b,this.src,a,!!d,e),a.da=c,f.push(a));return a};M.prototype.remove=function(a,b,c,d){if(!(a in this.l))return!1;var e=this.l[a];b=jb(e,b,c,d);return-1<b?(db(e[b]),y.splice.call(e,b,1),0==e.length&&(delete this.l[a],this.ca--),!0):!1};
function kb(a,b){var c=b.type;if(!(c in a.l))return!1;var d=a.l[c],e=z(d,b),f;(f=0<=e)&&y.splice.call(d,e,1);f&&(db(b),0==a.l[c].length&&(delete a.l[c],a.ca--));return f}M.prototype.ma=function(a){var b=0,c;for(c in this.l)if(!a||c==a){for(var d=this.l[c],e=0;e<d.length;e++)++b,db(d[e]);delete this.l[c];this.ca--}return b};M.prototype.X=function(a,b,c,d){a=this.l[a];var e=-1;a&&(e=jb(a,b,c,d));return-1<e?a[e]:null};
function jb(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.T&&f.J==b&&f.capture==!!c&&f.fa==d)return e}return-1};var lb="closure_lm_"+(1E6*Math.random()|0),mb={},nb=0;function N(a,b,c,d,e){if(r(b)){for(var f=0;f<b.length;f++)N(a,b[f],c,d,e);return null}c=ob(c);if(ab(a))a=a.o(b,c,d,e);else{if(!b)throw Error("Invalid event type");var f=!!d,g=pb(a);g||(a[lb]=g=new M(a));c=g.add(b,c,!1,d,e);c.la||(d=qb(),c.la=d,d.src=a,d.J=c,a.addEventListener?a.addEventListener(b,d,f):a.attachEvent(b in mb?mb[b]:mb[b]="on"+b,d),nb++);a=c}return a}
function qb(){var a=rb,b=Ta?function(c){return a.call(b.src,b.J,c)}:function(c){c=a.call(b.src,b.J,c);if(!c)return c};return b}function sb(a,b,c,d,e){if(r(b))for(var f=0;f<b.length;f++)sb(a,b[f],c,d,e);else c=ob(c),ab(a)?a.t(b,c,d,e):a&&(a=pb(a))&&(b=a.X(b,c,!!d,e))&&O(b)}
function O(a){if("number"==typeof a||!a||a.T)return!1;var b=a.src;if(ab(b))return kb(b.C,a);var c=a.type,d=a.la;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent&&b.detachEvent(c in mb?mb[c]:mb[c]="on"+c,d);nb--;(c=pb(b))?(kb(c,a),0==c.ca&&(c.src=null,b[lb]=null)):db(a);return!0}function tb(a,b,c,d){var e=1;if(a=pb(a))if(b=a.l[b])for(b=ya(b),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.T&&(e&=!1!==ub(f,d))}return Boolean(e)}
function ub(a,b){var c=a.J,d=a.fa||a.src;a.da&&O(a);return c.call(d,b)}
function rb(a,b){if(a.T)return!0;if(!Ta){var c;if(!(c=b))a:{c=["window","event"];for(var d=m,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break a}c=d}e=c;c=new L(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){a:{var f=!1;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(g){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.currentTarget;f;f=f.parentNode)e.push(f);for(var f=a.type,k=e.length-1;!c.G&&0<=k;k--)c.currentTarget=e[k],d&=tb(e[k],f,!0,c);for(k=0;!c.G&&k<e.length;k++)c.currentTarget=
e[k],d&=tb(e[k],f,!1,c)}return d}return ub(a,new L(b,this))}function pb(a){a=a[lb];return a instanceof M?a:null}var vb="__closure_events_fn_"+(1E9*Math.random()>>>0);function ob(a){return da(a)?a:a[vb]||(a[vb]=function(b){return a.handleEvent(b)})};var wb,xb=!C||C&&9<=G;!D&&!C||C&&C&&9<=G||D&&F("1.9.1");C&&F("9");function yb(a){a=a.className;return s(a)&&a.match(/\S+/g)||[]}function zb(a,b){for(var c=yb(a),d=za(arguments,1),e=c.length+d.length,f=c,g=0;g<d.length;g++)wa(f,d[g])||f.push(d[g]);a.className=c.join(" ");return c.length==e}function Ab(a,b){var c=yb(a),d=za(arguments,1),c=Bb(c,d);a.className=c.join(" ")}function Bb(a,b){return ta(a,function(a){return!wa(b,a)})};function P(a,b){this.x=void 0!==a?a:0;this.y=void 0!==b?b:0}P.prototype.W=function(){return new P(this.x,this.y)};function Cb(a,b){return new P(a.x-b.x,a.y-b.y)}P.prototype.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};function Db(a,b){this.width=a;this.height=b}Db.prototype.W=function(){return new Db(this.width,this.height)};Db.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function Q(a){return a?new Eb(R(a)):wb||(wb=new Eb)}function Fb(a){var b=document;return s(a)?b.getElementById(a):a}function Gb(a,b){eb(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in Hb?a.setAttribute(Hb[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})}
var Hb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function Ib(a,b,c){return Jb(document,arguments)}
function Jb(a,b){var c=b[0],d=b[1];if(!xb&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',ka(d.name),'"');if(d.type){c.push(' type="',ka(d.type),'"');var e={};ib(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&(s(d)?c.className=d:r(d)?zb.apply(null,[c].concat(d)):Gb(c,d));2<b.length&&Kb(a,c,b);return c}
function Kb(a,b,c){function d(c){c&&b.appendChild(s(c)?a.createTextNode(c):c)}for(var e=2;e<c.length;e++){var f=c[e];if(!ca(f)||ea(f)&&0<f.nodeType)d(f);else{var g;a:{if(f&&"number"==typeof f.length){if(ea(f)){g="function"==typeof f.item||"string"==typeof f.item;break a}if(da(f)){g="function"==typeof f.item;break a}}g=!1}sa(g?ya(f):f,d)}}}function Lb(a){for(var b;b=a.firstChild;)a.removeChild(b)}function R(a){return 9==a.nodeType?a:a.ownerDocument||a.document}
function Eb(a){this.h=a||m.document||document}h=Eb.prototype;h.Ka=function(a,b,c){return Jb(this.h,arguments)};h.createElement=function(a){return this.h.createElement(a)};h.createTextNode=function(a){return this.h.createTextNode(String(a))};function Mb(a){return"CSS1Compat"==a.h.compatMode}
function Nb(a){var b=a.h;a=E||"CSS1Compat"!=b.compatMode?b.body:b.documentElement;b=b.parentWindow||b.defaultView;return C&&F("10")&&b.pageYOffset!=a.scrollTop?new P(a.scrollLeft,a.scrollTop):new P(b.pageXOffset||a.scrollLeft,b.pageYOffset||a.scrollTop)}h.appendChild=function(a,b){a.appendChild(b)};h.Gb=Lb;h.removeNode=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null};function S(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}S.prototype.W=function(){return new S(this.top,this.right,this.bottom,this.left)};S.prototype.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};function Ob(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}Ob.prototype.W=function(){return new Ob(this.left,this.top,this.width,this.height)};Ob.prototype.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function T(a,b){var c=R(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,null))?c[b]||c.getPropertyValue(b)||"":""}function U(a,b){return T(a,b)||(a.currentStyle?a.currentStyle[b]:null)||a.style&&a.style[b]}
function Pb(a){var b;try{b=a.getBoundingClientRect()}catch(c){return{left:0,top:0,right:0,bottom:0}}C&&a.ownerDocument.body&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b}
function Qb(a){if(C&&!(C&&8<=G))return a.offsetParent;var b=R(a),c=U(a,"position"),d="fixed"==c||"absolute"==c;for(a=a.parentNode;a&&a!=b;a=a.parentNode)if(c=U(a,"position"),d=d&&"static"==c&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==c||"absolute"==c||"relative"==c))return a;return null}
function Rb(a){for(var b=new S(0,Infinity,Infinity,0),c=Q(a),d=c.h.body,e=c.h.documentElement,f=E||"CSS1Compat"!=c.h.compatMode?c.h.body:c.h.documentElement;a=Qb(a);)if(!(C&&0==a.clientWidth||E&&0==a.clientHeight&&a==d||a==d||a==e||"visible"==U(a,"overflow"))){var g=V(a),k;k=a;if(D&&!F("1.9")){var l=parseFloat(T(k,"borderLeftWidth"));if(Sb(k))var n=k.offsetWidth-k.clientWidth-l-parseFloat(T(k,"borderRightWidth")),l=l+n;k=new P(l,parseFloat(T(k,"borderTopWidth")))}else k=new P(k.clientLeft,k.clientTop);
g.x+=k.x;g.y+=k.y;b.top=Math.max(b.top,g.y);b.right=Math.min(b.right,g.x+a.clientWidth);b.bottom=Math.min(b.bottom,g.y+a.clientHeight);b.left=Math.max(b.left,g.x)}d=f.scrollLeft;f=f.scrollTop;b.left=Math.max(b.left,d);b.top=Math.max(b.top,f);c=(c.h.parentWindow||c.h.defaultView||window).document;c="CSS1Compat"==c.compatMode?c.documentElement:c.body;c=new Db(c.clientWidth,c.clientHeight);b.right=Math.min(b.right,d+c.width);b.bottom=Math.min(b.bottom,f+c.height);return 0<=b.top&&0<=b.left&&b.bottom>
b.top&&b.right>b.left?b:null}
function V(a){var b,c=R(a),d=U(a,"position"),e=D&&c.getBoxObjectFor&&!a.getBoundingClientRect&&"absolute"==d&&(b=c.getBoxObjectFor(a))&&(0>b.screenX||0>b.screenY),f=new P(0,0),g;b=c?R(c):document;g=!C||C&&9<=G||Mb(Q(b))?b.documentElement:b.body;if(a==g)return f;if(a.getBoundingClientRect)b=Pb(a),a=Nb(Q(c)),f.x=b.left+a.x,f.y=b.top+a.y;else if(c.getBoxObjectFor&&!e)b=c.getBoxObjectFor(a),a=c.getBoxObjectFor(g),f.x=b.screenX-a.screenX,f.y=b.screenY-a.screenY;else{b=a;do{f.x+=b.offsetLeft;f.y+=b.offsetTop;
b!=a&&(f.x+=b.clientLeft||0,f.y+=b.clientTop||0);if(E&&"fixed"==U(b,"position")){f.x+=c.body.scrollLeft;f.y+=c.body.scrollTop;break}b=b.offsetParent}while(b&&b!=a);if(B||E&&"absolute"==d)f.y-=c.body.offsetTop;for(b=a;(b=Qb(b))&&b!=c.body&&b!=g;)f.x-=b.scrollLeft,B&&"TR"==b.tagName||(f.y-=b.scrollTop)}return f}function Tb(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a}
function Ub(a){var b=Vb;if("none"!=U(a,"display"))return b(a);var c=a.style,d=c.display,e=c.visibility,f=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";a=b(a);c.display=d;c.position=f;c.visibility=e;return a}function Vb(a){var b=a.offsetWidth,c=a.offsetHeight,d=E&&!b&&!c;return(void 0===b||d)&&a.getBoundingClientRect?(a=Pb(a),new Db(a.right-a.left,a.bottom-a.top)):new Db(b,c)}function Sb(a){return"rtl"==U(a,"direction")}var Wb=D?"MozUserSelect":E?"WebkitUserSelect":null;
function Xb(a){var b=a.getElementsByTagName("*");if(Wb){var c="none";a.style[Wb]=c;if(b){a=0;for(var d;d=b[a];a++)d.style[Wb]=c}}else if(C||B)if(c="on",a.setAttribute("unselectable",c),b)for(a=0;d=b[a];a++)d.setAttribute("unselectable",c)}function Yb(a,b){if(/^\d+px?$/.test(b))return parseInt(b,10);var c=a.style.left,d=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=b;var e=a.style.pixelLeft;a.style.left=c;a.runtimeStyle.left=d;return e}
function Zb(a,b){var c=a.currentStyle?a.currentStyle[b]:null;return c?Yb(a,c):0}var $b={thin:2,medium:4,thick:6};function ac(a,b){if("none"==(a.currentStyle?a.currentStyle[b+"Style"]:null))return 0;var c=a.currentStyle?a.currentStyle[b+"Width"]:null;return c in $b?$b[c]:Yb(a,c)}
function bc(a){if(C&&!(C&&9<=G)){var b=ac(a,"borderLeft"),c=ac(a,"borderRight"),d=ac(a,"borderTop");a=ac(a,"borderBottom");return new S(d,c,a,b)}b=T(a,"borderLeftWidth");c=T(a,"borderRightWidth");d=T(a,"borderTopWidth");a=T(a,"borderBottomWidth");return new S(parseFloat(d),parseFloat(c),parseFloat(a),parseFloat(b))}var cc=/matrix\([0-9\.\-]+, [0-9\.\-]+, [0-9\.\-]+, [0-9\.\-]+, ([0-9\.\-]+)p?x?, ([0-9\.\-]+)p?x?\)/;function dc(a){this.c=a||[];this.Pb=!0}function ec(a,b,c){var d=[];if(""!=a){a=ra(a);a=RegExp("(^|\\W+)"+a,"i");for(var e=0;e<c.length&&d.length<b;e++){var f=c[e];String(f).match(a)&&d.push(f)}}return d}
function fc(a,b,c){for(var d=[],e=0;e<c.length;e++){var f=c[e],g=a.toLowerCase(),k=String(f).toLowerCase(),l=0;if(-1!=k.indexOf(g))l=parseInt((k.indexOf(g)/4).toString(),10);else for(var n=g.split(""),p=-1,q=10,H=0,t;t=n[H];H++)t=k.indexOf(t),t>p?(p=t-p-1,p>q-5&&(p=q-5),l+=p,p=t):(l+=q,q+=5);l<6*g.length&&d.push({Mb:f,hb:l,index:e})}d.sort(function(a,b){var c=a.hb-b.hb;return 0!=c?c:a.index-b.index});a=[];for(H=0;H<b&&H<d.length;H++)a.push(d[H].Mb);return a};function W(){J.call(this);this.C=new M(this);this.nb=this}x(W,J);W.prototype[$a]=!0;h=W.prototype;h.Ca=null;h.addEventListener=function(a,b,c,d){N(this,a,b,c,d)};h.removeEventListener=function(a,b,c,d){sb(this,a,b,c,d)};
h.dispatchEvent=function(a){var b,c=this.Ca;if(c)for(b=[];c;c=c.Ca)b.push(c);var c=this.nb,d=a.type||a;if(s(a))a=new K(a,c);else if(a instanceof K)a.target=a.target||c;else{var e=a;a=new K(d,c);ib(a,e)}var e=!0,f;if(b)for(var g=b.length-1;!a.G&&0<=g;g--)f=a.currentTarget=b[g],e=gc(f,d,!0,a)&&e;a.G||(f=a.currentTarget=c,e=gc(f,d,!0,a)&&e,a.G||(e=gc(f,d,!1,a)&&e));if(b)for(g=0;!a.G&&g<b.length;g++)f=a.currentTarget=b[g],e=gc(f,d,!1,a)&&e;return e};
h.e=function(){W.j.e.call(this);this.C&&this.C.ma(void 0);this.Ca=null};h.o=function(a,b,c,d){return this.C.add(a,b,!1,c,d)};h.t=function(a,b,c,d){return this.C.remove(a,b,c,d)};function gc(a,b,c,d){b=a.C.l[b];if(!b)return!0;b=ya(b);for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.T&&g.capture==c){var k=g.J,l=g.fa||g.src;g.da&&kb(a.C,g);e=!1!==k.call(l,d)&&e}}return e&&!1!=d.gb}h.X=function(a,b,c,d){return this.C.X(a,b,c,d)};function hc(a,b,c){W.call(this);this.Q=a;this.$=c;this.p=b;N(b,[ic,jc,kc,lc],this.handleEvent,!1,this);this.q=null;this.c=[];this.D=-1;this.k=0;this.I=this.g=null;this.Sa={}}x(hc,W);h=hc.prototype;h.Db=10;h.pb=!0;h.Ja=!1;h.mb=!1;h.jb=!1;var ic="hilite",jc="select",lc="dismiss",kc="canceldismiss";h=hc.prototype;
h.handleEvent=function(a){if(a.target==this.p)switch(a.type){case ic:this.A(a.U);break;case jc:a=a.U;var b=this.c[mc(this,a)],c=!!b&&this.Q.wa&&this.Q.wa(b);a&&b&&!c&&this.D!=a&&this.A(a);c||nc(this);break;case kc:oc(this);break;case lc:pc(this)}};function qc(a){for(var b=a.k+a.c.length-1,c=a.D,d=0;d<a.c.length;d++){if(c>=a.k&&c<b)c++;else if(-1==c)c=a.k;else if(a.Ja&&c==b){a.A(-1);break}else if(a.mb&&c==b)c=a.k;else break;if(a.A(c))break}}
function rc(a){for(var b=a.k+a.c.length-1,c=a.D,d=0;d<a.c.length;d++){if(c>a.k)c--;else if(a.Ja&&c==a.k){a.A(-1);break}else if(!a.mb||-1!=c&&c!=a.k)break;else c=b;if(a.A(c))break}}h.A=function(a){var b=mc(this,a),c=this.c[b];return c&&this.Q.wa&&this.Q.wa(c)?!1:(this.D=a,this.p.A(a),-1!=b)};
function nc(a){var b=mc(a,a.D);if(-1!=b){var b=a.c[b],c=a.$,d=b.toString();if(c.R){var e=sc(c,c.a.value,tc(c.a)),f=uc(c,c.a.value);c.Jb.test(d)||(d=d.replace(/[\s\xa0]+$/,"")+c.rb);c.Rb&&(0==e||/^[\s\xa0]*$/.test(f[e-1])||(d=" "+d),e==f.length-1&&(d+=" "));if(d!=f[e]){f[e]=d;d=c.a;(D||C&&F("9"))&&d.blur();d.value=f.join("");for(var g=0,k=0;k<=e;k++)g+=f[k].length;d.focus();e=g;f=c.a;d=e;vc(f)?f.selectionStart=d:C&&(g=wc(f),k=g[0],k.inRange(g[1])&&(d=xc(f,d),k.collapse(!0),k.move("character",d),k.select()));
f=c.a;vc(f)?f.selectionEnd=e:C&&(g=wc(f),d=g[1],g[0].inRange(d)&&(e=xc(f,e),f=xc(f,tc(f)),d.collapse(!0),d.moveEnd("character",e-f),d.select()))}}else c.a.value=d;c.Ga=!0;a.jb?(a.q=null,pc(a)):a.v();a.dispatchEvent({type:"update",U:b});a.jb&&a.$.update(!0);return!0}a.v();a.dispatchEvent({type:"update",U:null});return!1}h.v=function(){this.D=-1;this.q=null;this.k+=this.c.length;this.c=[];window.clearTimeout(this.I);this.I=null;this.p.v();this.dispatchEvent("suggestionsupdate");this.dispatchEvent(lc)};
function pc(a){a.I||(a.I=window.setTimeout(u(a.v,a),100))}h.Ra=function(){return this.I?(window.clearTimeout(this.I),this.I=null,!0):!1};function oc(a){a.Ra()||window.setTimeout(u(a.Ra,a),10)}h.e=function(){hc.j.e.call(this);delete this.Sa;this.p.B();this.$.B();this.Q=null};h.Bb=function(a,b,c){this.q==a&&this.Ea(b,c)};
h.Ea=function(a,b){var c="object"==ba(b)&&b,d=(c?c.Tb():b)?mc(this,this.D):-1;this.k+=this.c.length;this.c=a;for(var e=[],f=0;f<a.length;++f)e.push({id:this.k+f,data:a[f]});f=null;this.g&&(f=this.Sa[fa(this.g)]||this.g);this.p.ob=f;this.p.Ea(e,this.q,this.g);f=this.pb;c&&void 0!==c.vb()&&(f=c.vb());this.D=-1;(f||0<=d)&&0!=e.length&&this.q&&(0<=d?this.A(this.k+d):qc(this));this.dispatchEvent("suggestionsupdate")};function mc(a,b){var c=b-a.k;return 0>c||c>=a.c.length?-1:c}
h.sa=function(a){var b=this.$;b.sa.apply(b,arguments)};h.update=function(a){this.$.update(a)};function yc(a,b){W.call(this);this.P=a||1;this.V=b||m;this.ta=u(this.Nb,this);this.za=w()}x(yc,W);h=yc.prototype;h.enabled=!1;h.f=null;h.Nb=function(){if(this.enabled){var a=w()-this.za;0<a&&a<0.8*this.P?this.f=this.V.setTimeout(this.ta,this.P-a):(this.f&&(this.V.clearTimeout(this.f),this.f=null),this.dispatchEvent(zc),this.enabled&&(this.f=this.V.setTimeout(this.ta,this.P),this.za=w()))}};h.start=function(){this.enabled=!0;this.f||(this.f=this.V.setTimeout(this.ta,this.P),this.za=w())};
h.stop=function(){this.enabled=!1;this.f&&(this.V.clearTimeout(this.f),this.f=null)};h.e=function(){yc.j.e.call(this);this.stop();delete this.V};var zc="tick";var Ac;function Bc(a,b){b?a.setAttribute("role",b):a.removeAttribute("role")}function Cc(a,b,c){ca(c)&&(c=c.join(" "));var d="aria-"+b;""===c||void 0==c?(Ac||(Ac={atomic:!1,autocomplete:"none",dropeffect:"none",haspopup:!1,live:"off",multiline:!1,multiselectable:!1,orientation:"vertical",readonly:!1,relevant:"additions text",required:!1,sort:"none",busy:!1,disabled:!1,hidden:!1,invalid:"false"}),c=Ac,b in c?a.setAttribute(d,c[b]):a.removeAttribute(d)):a.setAttribute(d,c)}
function Dc(a,b){var c="";b&&(c=b.id);Cc(a,"activedescendant",c)};function tc(a){var b;a:{var c=0,d=0;if(vc(a))c=a.selectionStart,d=-1;else if(C){var e=wc(a);b=e[0];e=e[1];if(b.inRange(e)){b.setEndPoint("EndToStart",e);if("textarea"==a.type){e.duplicate();c=a=b.text;for(d=!1;!d;)0==b.compareEndPoints("StartToEnd",b)?d=!0:(b.moveEnd("character",-1),b.text==a?c+="\r\n":d=!0);b=[c.length,-1];break a}c=b.text.length;d=-1}}b=[c,d]}return b[0]}
function wc(a){var b=a.ownerDocument||a.document,c=b.selection.createRange();"textarea"==a.type?(b=b.body.createTextRange(),b.moveToElementText(a)):b=a.createTextRange();return[b,c]}function xc(a,b){"textarea"==a.type&&(b=a.value.substring(0,b).replace(/(\r\n|\r|\n)/g,"\n").length);return b}function vc(a){try{return"number"==typeof a.selectionStart}catch(b){return!1}};function Ec(a){J.call(this);this.Y=a;this.ja={}}x(Ec,J);var Fc=[];h=Ec.prototype;h.o=function(a,b,c,d,e){r(b)||(Fc[0]=b,b=Fc);for(var f=0;f<b.length;f++){var g=N(a,b[f],c||this,d||!1,e||this.Y||this);if(!g)break;this.ja[g.key]=g}return this};h.t=function(a,b,c,d,e){if(r(b))for(var f=0;f<b.length;f++)this.t(a,b[f],c,d,e);else e=e||this.Y||this,c=ob(c||this),d=!!d,b=ab(a)?a.X(b,c,d,e):a?(a=pb(a))?a.X(b,c,d,e):null:null,b&&(O(b),delete this.ja[b.key]);return this};
h.ma=function(){eb(this.ja,O);this.ja={}};h.e=function(){Ec.j.e.call(this);this.ma()};h.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function Gc(a,b,c,d,e){if(!(C||E&&F("525")))return!0;if(A&&e)return Hc(a);if(e&&!d||!c&&(17==b||18==b||A&&91==b))return!1;if(E&&d&&c)switch(a){case 220:case 219:case 221:case 192:case 186:case 189:case 187:case 188:case 190:case 191:case 192:case 222:return!1}if(C&&d&&b==a)return!1;switch(a){case 13:return!(C&&C&&9<=G);case 27:return!E}return Hc(a)}
function Hc(a){if(48<=a&&57>=a||96<=a&&106>=a||65<=a&&90>=a||E&&0==a)return!0;switch(a){case 32:case 63:case 107:case 109:case 110:case 111:case 186:case 59:case 189:case 187:case 61:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:return!0;default:return!1}}function Ic(a){switch(a){case 61:return 187;case 59:return 186;case 173:return 189;case 224:return 91;case 0:return 224;default:return a}};function Jc(a,b){W.call(this);a&&Kc(this,a,b)}x(Jc,W);h=Jc.prototype;h.b=null;h.ha=null;h.xa=null;h.ia=null;h.m=-1;h.F=-1;h.ra=!1;
var Lc={3:13,12:144,63232:38,63233:40,63234:37,63235:39,63236:112,63237:113,63238:114,63239:115,63240:116,63241:117,63242:118,63243:119,63244:120,63245:121,63246:122,63247:123,63248:44,63272:46,63273:36,63275:35,63276:33,63277:34,63289:144,63302:45},Mc={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},Nc=C||E&&F("525"),Oc=A&&D;h=Jc.prototype;
h.xb=function(a){E&&(17==this.m&&!a.ctrlKey||18==this.m&&!a.altKey||A&&91==this.m&&!a.metaKey)&&(this.F=this.m=-1);-1==this.m&&(a.ctrlKey&&17!=a.keyCode?this.m=17:a.altKey&&18!=a.keyCode?this.m=18:a.metaKey&&91!=a.keyCode&&(this.m=91));Nc&&!Gc(a.keyCode,this.m,a.shiftKey,a.ctrlKey,a.altKey)?this.handleEvent(a):(this.F=D?Ic(a.keyCode):a.keyCode,Oc&&(this.ra=a.altKey))};h.zb=function(a){this.F=this.m=-1;this.ra=a.altKey};
h.handleEvent=function(a){var b=a.N,c,d,e=b.altKey;C&&"keypress"==a.type?(c=this.F,d=13!=c&&27!=c?b.keyCode:0):E&&"keypress"==a.type?(c=this.F,d=0<=b.charCode&&63232>b.charCode&&Hc(c)?b.charCode:0):B?(c=this.F,d=Hc(c)?b.keyCode:0):(c=b.keyCode||this.F,d=b.charCode||0,Oc&&(e=this.ra),A&&63==d&&224==c&&(c=191));var f=c,g=b.keyIdentifier;c?63232<=c&&c in Lc?f=Lc[c]:25==c&&a.shiftKey&&(f=9):g&&g in Mc&&(f=Mc[g]);a=f==this.m;this.m=f;b=new Pc(f,d,a,b);b.altKey=e;this.dispatchEvent(b)};
function Kc(a,b,c){a.ia&&a.detach();a.b=b;a.ha=N(a.b,"keypress",a,c);a.xa=N(a.b,"keydown",a.xb,c,a);a.ia=N(a.b,"keyup",a.zb,c,a)}h.detach=function(){this.ha&&(O(this.ha),O(this.xa),O(this.ia),this.ia=this.xa=this.ha=null);this.b=null;this.F=this.m=-1};h.e=function(){Jc.j.e.call(this);this.detach()};function Pc(a,b,c,d){d&&Za(this,d,void 0);this.type="key";this.keyCode=a;this.charCode=b;this.repeat=c}x(Pc,L);var Qc,Rc;Rc=Qc=!1;var Sc=Ea();Sc&&(-1!=Sc.indexOf("Firefox")||-1!=Sc.indexOf("Camino")||(-1!=Sc.indexOf("iPhone")||-1!=Sc.indexOf("iPod")?Qc=!0:-1!=Sc.indexOf("iPad")&&(Rc=!0)));var Tc=Qc,Uc=Rc;function Vc(a,b,c,d){J.call(this);d=d||150;this.R=null!=c?c:!0;this.aa=a||",;";this.rb=this.aa.substring(0,1);a=this.R?"[\\s"+this.aa+"]+":"[\\s]+";this.kb=RegExp("^"+a+"|"+a+"$","g");this.Jb=RegExp("\\s*["+this.aa+"]$");this.Wa=b||"";this.Fb=this.R;this.f=0<d?new yc(d):null;this.i=new Ec(this);this.pa=new Ec(this);this.Z=new Jc;this.Ua=-1}x(Vc,J);var Wc=(Tc||Uc)&&!F("533.17.9");h=Vc.prototype;h.Rb=!0;h.ub=!0;h.lb=!1;h.Lb=!0;h.Kb=!0;h.qa=null;h.a=null;h.ya="";h.H=!1;h.Ga=!1;h.Ob=!0;
h.sa=function(a){for(var b=0;b<arguments.length;b++){var c=arguments[b];ea(c)&&1==c.nodeType&&Cc(c,"haspopup",!0);this.i.o(c,"focus",this.Oa);this.i.o(c,"blur",this.wb);if(!this.a&&(this.pa.o(c,"keydown",this.Eb),ea(c)&&1==c.nodeType)){var d;a:{var e=R(c);try{d=e&&e.activeElement;break a}catch(f){}d=null}d==c&&Xc(this,c)}}};h.e=function(){Vc.j.e.call(this);null!=this.qa&&window.clearTimeout(this.qa);this.i.B();delete this.i;this.pa.B();this.Z.B();Xa(this.f)};
function Yc(a,b){switch(b.keyCode){case 40:if(a.d.p.u){a.lb?rc(a.d):qc(a.d);b.preventDefault();return}if(!a.R){a.update(!0);b.preventDefault();return}break;case 38:if(a.d.p.u){a.lb?qc(a.d):rc(a.d);b.preventDefault();return}break;case 9:if(a.d.p.u&&!b.shiftKey){if(a.update(),nc(a.d)&&a.Fb){b.preventDefault();return}}else a.d.v();break;case 13:if(a.d.p.u){if(a.update(),nc(a.d)){b.preventDefault();b.stopPropagation();return}}else a.d.v();break;case 27:if(a.d.p.u){a.d.v();b.preventDefault();b.stopPropagation();
return}break;case 229:if(!a.H){a.H||(a.i.o(a.a,"keyup",a.ab),a.i.o(a.a,"keypress",a.$a),a.H=!0);return}break;default:a.f&&!a.Ob&&(a.f.stop(),a.f.start())}Zc(a,b)}function Zc(a,b){var c=a.R&&b.charCode&&-1!=a.aa.indexOf(String.fromCharCode(b.charCode));a.Lb&&c&&a.update();a.Kb&&c&&nc(a.d)&&b.preventDefault()}h.yb=function(){return!1};h.Oa=function(a){Xc(this,a.target||null)};
function Xc(a,b){a.pa.ma();a.d&&oc(a.d);b!=a.a&&(a.a=b,a.f&&(a.f.start(),a.i.o(a.f,zc,a.eb)),a.ya=a.a.value,Kc(a.Z,a.a),a.i.o(a.Z,"key",a.bb),a.i.o(a.a,"mousedown",a.cb),C&&a.i.o(a.a,"keypress",a.Za))}h.wb=function(){Wc?this.qa=window.setTimeout(u(this.fb,this),0):this.fb()};
h.fb=function(){this.a&&(this.i.t(this.Z,"key",this.bb),this.Z.detach(),this.i.t(this.a,"keyup",this.yb),this.i.t(this.a,"mousedown",this.cb),C&&this.i.t(this.a,"keypress",this.Za),this.H&&$c(this),this.a=null,this.f&&(this.f.stop(),this.i.t(this.f,zc,this.eb)),this.d&&pc(this.d))};h.eb=function(){this.update()};h.Eb=function(a){this.Oa(a)};h.bb=function(a){this.Ua=a.keyCode;this.d&&Yc(this,a)};h.$a=function(){this.H&&229!=this.Ua&&$c(this)};
h.ab=function(a){this.H&&(13==a.keyCode||77==a.keyCode&&a.ctrlKey)&&$c(this)};h.cb=function(){};function $c(a){a.H&&(a.H=!1,a.i.t(a.a,"keypress",a.$a),a.i.t(a.a,"keyup",a.ab))}h.Za=function(a){Zc(this,a)};
h.update=function(a){if(this.a&&(a||this.a.value!=this.ya)){if(a||!this.Ga){var b;a=tc(this.a);b=this.a.value;a=uc(this,b)[sc(this,b,a)];b=this.kb?String(a).replace(this.kb,""):a;if(this.d&&(this.d.g=this.a,a=this.d,a.q!=b)){a.q=b;var c=a.Q;b=a.q;var d=a.Db,e=u(a.Bb,a);if(c.Pb){var c=c.c,f=ec(b,d,c);0==f.length&&(f=fc(b,d,c));d=f}else d=ec(b,d,c.c);e(b,d);oc(a)}}this.ya=this.a.value}this.Ga=!1};
function sc(a,b,c){a=uc(a,b);if(c==b.length)return a.length-1;for(var d=b=0,e=0;d<a.length&&e<=c;d++)e+=a[d].length,b=d;return b}function uc(a,b){if(!a.R)return[b];for(var c=String(b).split(""),d=[],e=[],f=0,g=!1;f<c.length;f++)a.Wa&&-1!=a.Wa.indexOf(c[f])?(a.ub&&!g&&(d.push(e.join("")),e.length=0),e.push(c[f]),g=!g):g||-1==a.aa.indexOf(c[f])?e.push(c[f]):(e.push(c[f]),d.push(e.join("")),e.length=0);d.push(e.join(""));return d};function ad(){W.call(this);this.s=bd;this.Ma=this.startTime=null}x(ad,W);var bd=0;ad.prototype.K=function(){this.w("begin")};ad.prototype.S=function(){this.w("end")};ad.prototype.w=function(a){this.dispatchEvent(a)};function cd(a,b,c){J.call(this);this.Aa=a;this.P=b||0;this.Y=c;this.qb=u(this.sb,this)}x(cd,J);h=cd.prototype;h.O=0;h.e=function(){cd.j.e.call(this);this.stop();delete this.Aa;delete this.Y};h.start=function(a){this.stop();var b=this.qb;a=void 0!==a?a:this.P;if(!da(b))if(b&&"function"==typeof b.handleEvent)b=u(b.handleEvent,b);else throw Error("Invalid listener argument");this.O=2147483647<a?-1:m.setTimeout(b,a||0)};h.stop=function(){0!=this.O&&m.clearTimeout(this.O);this.O=0};
h.sb=function(){this.O=0;this.Aa&&this.Aa.call(this.Y)};var gb={},dd=null;function ed(a){a=fa(a);delete gb[a];fb()&&dd&&dd.stop()}function fd(){dd||(dd=new cd(function(){gd()},20));var a=dd;0!=a.O||a.start()}function gd(){var a=w();eb(gb,function(b){hd(b,a)});fb()||fd()};function id(a,b,c,d){ad.call(this);if(!r(a)||!r(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.ba=a;this.tb=b;this.duration=c;this.Ha=d;this.coords=[]}x(id,ad);h=id.prototype;h.n=0;
h.play=function(a){if(a||this.s==bd)this.n=0,this.coords=this.ba;else if(1==this.s)return!1;ed(this);this.startTime=a=w();-1==this.s&&(this.startTime-=this.duration*this.n);this.Ma=this.startTime+this.duration;this.n||this.K();this.w("play");-1==this.s&&this.w("resume");this.s=1;var b=fa(this);b in gb||(gb[b]=this);fd();hd(this,a);return!0};h.stop=function(a){ed(this);this.s=bd;a&&(this.n=1);jd(this,this.n);this.w("stop");this.S()};h.e=function(){this.s==bd||this.stop(!1);this.w("destroy");id.j.e.call(this)};
function hd(a,b){a.n=(b-a.startTime)/(a.Ma-a.startTime);1<=a.n&&(a.n=1);jd(a,a.n);1==a.n?(a.s=bd,ed(a),a.w("finish"),a.S()):1==a.s&&a.Ba()}function jd(a,b){da(a.Ha)&&(b=a.Ha(b));a.coords=Array(a.ba.length);for(var c=0;c<a.ba.length;c++)a.coords[c]=(a.tb[c]-a.ba[c])*b+a.ba[c]}h.Ba=function(){this.w("animate")};h.w=function(a){this.dispatchEvent(new kd(a,this))};
function kd(a,b){K.call(this,a);this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.n=b.n;this.state=b.s}x(kd,K);function X(a,b,c,d,e){id.call(this,b,c,d,e);this.element=a}x(X,id);X.prototype.oa=aa;X.prototype.Ba=function(){this.oa();X.j.Ba.call(this)};X.prototype.S=function(){this.oa();X.j.S.call(this)};X.prototype.K=function(){this.oa();X.j.K.call(this)};function Y(a,b,c,d,e){"number"==typeof b&&(b=[b]);"number"==typeof c&&(c=[c]);X.call(this,a,b,c,d,e);if(1!=b.length||1!=c.length)throw Error("Start and end points must be 1D");}x(Y,X);
Y.prototype.oa=function(){var a=this.coords[0],b=this.element.style;"opacity"in b?b.opacity=a:"MozOpacity"in b?b.MozOpacity=a:"filter"in b&&(b.filter=""===a?"":"alpha(opacity="+100*a+")")};Y.prototype.show=function(){this.element.style.display=""};function ld(a,b,c){Y.call(this,a,1,0,b,c)}x(ld,Y);ld.prototype.K=function(){this.show();ld.j.K.call(this)};ld.prototype.S=function(){this.element.style.display="none";ld.j.S.call(this)};function md(a,b,c){Y.call(this,a,0,1,b,c)}x(md,Y);
md.prototype.K=function(){this.show();md.j.K.call(this)};function Z(){}Z.ua=function(){return Z.Ta?Z.Ta:Z.Ta=new Z};Z.prototype.Xa=0;Z.ua();function nd(a,b,c,d){W.call(this);this.Da=a||document.body;this.r=Q(this.Da);this.Hb=!a;this.b=null;this.q="";this.c=[];this.L=[];this.ib=this.ga=-1;this.u=!1;this.className="ac-renderer";this.Fa="ac-row";this.Va="active";this.Ia="ac-active";this.Ab="ac-highlighted";this.ea=b||null;this.Qb=null!=d?d:!0;this.Cb=!0;this.va=!1;this.Ib=!!c;this.na=!1;this.ka=0}x(nd,W);h=nd.prototype;h.Ea=function(a,b,c){this.q=b;this.c=a;this.ga=-1;this.ib=w();this.g=c;this.L=[];od(this)};
h.v=function(){this.g&&Dc(this.g,null);this.u&&(this.u=!1,this.g&&Cc(this.g,"haspopup",!1),0<this.ka?(Xa(this.M),this.M=new ld(this.b,this.ka),this.M.play()):this.b.style.display="none")};h.show=function(){this.u||(this.u=!0,this.g&&(Bc(this.g,"combobox"),Cc(this.g,"autocomplete","list"),Cc(this.g,"haspopup",!0)),0<this.ka?(Xa(this.M),this.M=new md(this.b,this.ka),this.M.play()):this.b.style.display="")};
function pd(a,b){var c=0<=b&&b<a.c.length?a.c[b]:void 0,d=0<=b&&b<a.L.length?a.L[b]:void 0;if(a.dispatchEvent({type:"rowhilite",Wb:d,U:c?c.data:null})&&(0<=a.ga&&Ab(a.L[a.ga],a.Ia,a.Va),a.ga=b,d)){zb(d,a.Ia,a.Va);a.g&&Dc(a.g,d);var c=a.b,e=V(d),f=V(c),g=bc(c),k=e.x-f.x-g.left,e=e.y-f.y-g.top,f=c.clientHeight-d.offsetHeight,g=c.scrollLeft,l=c.scrollTop,g=g+Math.min(k,Math.max(k-(c.clientWidth-d.offsetWidth),0)),l=l+Math.min(e,Math.max(e-f,0)),d=new P(g,l);c.scrollLeft=d.x;c.scrollTop=d.y}}
h.A=function(a){if(-1==a)pd(this,-1);else for(var b=0;b<this.c.length;b++)if(this.c[b].id==a){pd(this,b);break}};function qd(a){if(!a.b){var b=a.r.Ka("div",{style:"display:none"});a.b=b;zb(b,a.className);Bc(b,"listbox");b.id=":"+(Z.ua().Xa++).toString(36);a.r.appendChild(a.Da,b);N(b,"click",a.Na,!1,a);N(b,"mousedown",a.Pa,!1,a);N(b,"mouseover",a.Qa,!1,a)}}
function od(a){qd(a);a.na&&(a.b.style.visibility="hidden");a.Sb&&(a.b.style.minWidth=a.Sb.clientWidth+"px");a.L.length=0;a.r.Gb(a.b);if(!a.ea||!a.ea.Ub){var b=null;sa(a.c,function(a){var d=this.q,e=this.r.Ka("div",{className:this.Fa,id:":"+(Z.ua().Xa++).toString(36)});Bc(e,"option");this.ea&&this.ea.Vb||(e.innerHTML=ka(a.data.toString()));d&&this.Qb&&rd(this,e,d);zb(e,this.Fa);this.L.push(e);a=e;this.na?this.b.insertBefore(a,b):this.r.appendChild(this.b,a);b=a},a)}0==a.c.length?a.v():(a.show(),sd(a),
Xb(a.b))}
function sd(a){if(a.g&&a.Hb){var b,c=a.Ib?3:1;a.na&&(c^=1);b=c;var d=a.ob||a.g,c=a.b,e=b^1,f,g;if(f=c.offsetParent){var k="HTML"==f.tagName||"BODY"==f.tagName;k&&"static"==U(f,"position")||(g=V(f),k||(k=(k=Sb(f))&&D?-f.scrollLeft:!k||C&&F("8")||"visible"==U(f,"overflowX")?f.scrollLeft:f.scrollWidth-f.clientWidth-f.scrollLeft,g=Cb(g,new P(k,f.scrollTop))))}f=g||new P;g=V(d);k=Ub(d);g=new Ob(g.x,g.y,k.width,k.height);if(k=Rb(d)){var l=new Ob(k.left,k.top,k.right-k.left,k.bottom-k.top),k=Math.max(g.left,l.left),
n=Math.min(g.left+g.width,l.left+l.width);if(k<=n){var p=Math.max(g.top,l.top),l=Math.min(g.top+g.height,l.top+l.height);p<=l&&(g.left=k,g.top=p,g.width=n-k,g.height=l-p)}}k=Q(d);p=Q(c);if(k.h!=p.h){var n=k.h.body,p=p.h.parentWindow||p.h.defaultView,l=new P(0,0),q=R(n)?R(n).parentWindow||R(n).defaultView:window,H=n;do{var t;if(q==p)t=V(H);else{t=H;var I=void 0;if(t.getBoundingClientRect)I=Pb(t),I=new P(I.left,I.top);else var I=Nb(Q(t)),v=V(t),I=new P(v.x-I.x,v.y-I.y);v=void 0;if(D&&!F(12)){v=void 0;
v=void 0;C?v="-ms-transform":E?v="-webkit-transform":B?v="-o-transform":D&&(v="-moz-transform");var pa=void 0;v&&(pa=U(t,v));pa||(pa=U(t,"transform"));v=pa?(t=pa.match(cc))?new P(parseFloat(t[1]),parseFloat(t[2])):new P(0,0):new P(0,0);v=new P(I.x+v.x,I.y+v.y)}else v=I;t=v}l.x+=t.x;l.y+=t.y}while(q&&q!=p&&(H=q.frameElement)&&(q=q.parent));n=Cb(l,V(n));C&&!Mb(k)&&(n=Cb(n,Nb(k)));g.left+=n.x;g.top+=n.y}b=(b&4&&Sb(d)?b^2:b)&-5;b=new P(b&2?g.left+g.width:g.left,b&1?g.top+g.height:g.top);b=Cb(b,f);if(d=
Rb(c))d.top-=f.y,d.right-=f.x,d.bottom-=f.y,d.left-=f.x;f=b.W();g=(e&4&&Sb(c)?e^2:e)&-5;b=Ub(c);e=b.W();0!=g&&(g&2&&(f.x-=e.width+0),g&1&&(f.y-=e.height+0));d?(g=f,k=65,n=0,65==(k&65)&&(g.x<d.left||g.x>=d.right)&&(k&=-2),132==(k&132)&&(g.y<d.top||g.y>=d.bottom)&&(k&=-5),g.x<d.left&&k&1&&(g.x=d.left,n|=1),g.x<d.left&&g.x+e.width>d.right&&k&16&&(e.width=Math.max(e.width-(g.x+e.width-d.right),0),n|=4),g.x+e.width>d.right&&k&1&&(g.x=Math.max(d.right-e.width,d.left),n|=1),k&2&&(n=n|(g.x<d.left?16:0)|(g.x+
e.width>d.right?32:0)),g.y<d.top&&k&4&&(g.y=d.top,n|=2),g.y<=d.top&&g.y+e.height<d.bottom&&k&32&&(e.height=Math.max(e.height-(d.top-g.y),0),g.y=d.top,n|=8),g.y>=d.top&&g.y+e.height>d.bottom&&k&32&&(e.height=Math.max(e.height-(g.y+e.height-d.bottom),0),n|=8),g.y+e.height>d.bottom&&k&4&&(g.y=Math.max(d.bottom-e.height,d.top),n|=2),k&8&&(n=n|(g.y<d.top?64:0)|(g.y+e.height>d.bottom?128:0)),d=n):d=256;d&496||(g=f,f=D&&(A||Ja)&&F("1.9"),g instanceof P?(d=g.x,g=g.y):(d=g,g=void 0),c.style.left=Tb(d,f),c.style.top=
Tb(g,f),b==e||b&&e&&b.width==e.width&&b.height==e.height||(d=Mb(Q(R(c))),!C||d&&F("8")?(c=c.style,D?c.MozBoxSizing="border-box":E?c.WebkitBoxSizing="border-box":c.boxSizing="border-box",c.width=Math.max(e.width,0)+"px",c.height=Math.max(e.height,0)+"px"):(b=c.style,d?(C?(d=Zb(c,"paddingLeft"),f=Zb(c,"paddingRight"),g=Zb(c,"paddingTop"),k=Zb(c,"paddingBottom"),d=new S(g,f,k,d)):(d=T(c,"paddingLeft"),f=T(c,"paddingRight"),g=T(c,"paddingTop"),k=T(c,"paddingBottom"),d=new S(parseFloat(g),parseFloat(f),
parseFloat(k),parseFloat(d))),c=bc(c),b.pixelWidth=e.width-c.left-d.left-d.right-c.right,b.pixelHeight=e.height-c.top-d.top-d.bottom-c.bottom):(b.pixelWidth=e.width,b.pixelHeight=e.height))));a.na&&(a.b.style.visibility="visible")}}h.e=function(){this.b&&(sb(this.b,"click",this.Na,!1,this),sb(this.b,"mousedown",this.Pa,!1,this),sb(this.b,"mouseover",this.Qa,!1,this),this.r.removeNode(this.b),this.b=null,this.u=!1);Xa(this.M);this.Da=null;nd.j.e.call(this)};
function rd(a,b,c){if(3==b.nodeType){var d=null;r(c)&&1<c.length&&!a.va&&(d=za(c,1));c=td(a,c);if(0!=c.length){var e=b.nodeValue,f=a.Cb?RegExp("\\b(?:"+c+")","gi"):RegExp(c,"gi");c=[];for(var g=0,k=f.exec(e),l=0;k;)l++,c.push(e.substring(g,k.index)),c.push(e.substring(k.index,f.lastIndex)),g=f.lastIndex,k=f.exec(e);c.push(e.substring(g));if(1<c.length){d=a.va?l:1;for(e=0;e<d;e++)f=2*e,b.nodeValue=c[f],g=a.r.createElement("b"),g.className=a.Ab,a.r.appendChild(g,a.r.createTextNode(c[f+1])),g=b.parentNode.insertBefore(g,
b.nextSibling),b.parentNode.insertBefore(a.r.createTextNode(""),g.nextSibling),b=g.nextSibling;a=za(c,2*d);b.nodeValue=a.join("")}else d&&rd(a,b,d)}}else for(b=b.firstChild;b;)d=b.nextSibling,rd(a,b,c),b=d}
function td(a,b){var c="";if(!b)return c;r(b)&&(b=ta(b,function(a){return!/^[\s\xa0]*$/.test(null==a?"":String(a))}));a.va?r(b)?c=ua(b,ra).join("|"):(c=b.replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,""),c=ra(c),c=c.replace(/ /g,"|")):r(b)?c=0<b.length?ra(b[0]):"":/^\W/.test(b)||(c=ra(b));return c}function ud(a,b){for(;b&&b!=a.b&&!wa(yb(b),a.Fa);)b=b.parentNode;return b?z(a.L,b):-1}h.Na=function(a){var b=ud(this,a.target);0<=b&&this.dispatchEvent({type:jc,U:this.c[b].id});a.stopPropagation()};
h.Pa=function(a){a.stopPropagation();a.preventDefault()};h.Qa=function(a){a=ud(this,a.target);0<=a&&!(300>w()-this.ib)&&this.dispatchEvent({type:ic,U:this.c[a].id})};function vd(a,b){var c=new dc(a),d=new nd,e=new Vc(null,null,!1),c=new hc(c,d,e);e.d=c;e.sa(b)};function wd(){var a=m.TYPES;xd(a);setTimeout(function(){yd(a);setTimeout(zd,0)},0)}var Ad=["init"],$=m;Ad[0]in $||!$.execScript||$.execScript("var "+Ad[0]);for(var Bd;Ad.length&&(Bd=Ad.shift());)Ad.length||void 0===wd?$=$[Bd]?$[Bd]:$[Bd]={}:$[Bd]=wd;var Cd=function(){var a="./";va(function(b){b=b.src;var c=b.length;return"dossier.js"===b.substr(c-10)?(a=b.substr(0,c-10),!0):!1});return a}();
function yd(a){var b=Fb("searchbox"),c=b.getElementsByTagName("input")[0];vd(xa(a.classes,a.enums,a.interfaces,a.namespaces),c);N(b,"submit",function(b){b.preventDefault();b.stopPropagation();b=c.value;var e;0<=z(a.classes,b)?e="class_":0<=z(a.enums,b)?e="enum_":0<=z(a.interfaces,b)?e="interface_":0<=z(a.namespaces,b)&&(e="namespace_");e&&(window.location.href=Cd+e+b.replace(/\./g,"_")+".html");return!1})}
function xd(a){var b=Fb("left");if(b){var c=[];a.classes.length&&c.push(Dd("Classes","class_",a.classes));a.enums.length&&c.push(Dd("Enums","enum_",a.enums));a.interfaces.length&&c.push(Dd("Interfaces","interface_",a.interfaces));a.namespaces.length&&c.push(Dd("Namespaces","namespace_",a.namespaces));Lb(b);sa(c,function(a){b.appendChild(a)})}}
function Dd(a,b,c){a=Ib("DETAILS",null,Ib("SUMMARY",null,a));var d=document.createElement("UL");a.appendChild(d);sa(c,function(a){a=Ib("LI",null,Ib("A",{href:Cd+b+a.replace(/\./g,"_")+".html"},a));d.appendChild(a)});return a}
function zd(){var a=document.getElementsByTagName("DETAILS");a.length&&!a[0].hasOwnProperty("open")&&sa(a,function(a){function c(){(d=!d)?a.setAttribute("open",""):a.removeAttribute("open");sa(a.childNodes,function(a){1===a.nodeType&&"SUMMARY"!==a.tagName.toUpperCase()&&(a.style.display=d?"":"none")})}var d=!0;a.setAttribute("open","");N(a,"click",c);c()})};;init();})();
