java_library(
    name = "jscomp",
    srcs = glob(["*.java"]),
    visibility = ["//src/java/com/github/jsdossier/jscomp:__pkg__"],
    deps = [
        "//src/java/com/github/jsdossier/annotations",
        "//third_party/java/auto:factory",
        "//third_party/java/auto:value",
        "//third_party/java/closure_compiler",
        "//third_party/java/guava",
        "//third_party/java/guice",
        "//third_party/java/jsr305_annotations",
        "//third_party/java/jsr330_inject",
    ],
)
