// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dossier.proto

package com.github.jsdossier.proto;

/**
 * Protobuf type {@code dossier.BaseProperty}
 *
 * <pre>
 * Describes the basic properties for a documented JavaScript property.
 * </pre>
 */
public  final class BaseProperty extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:dossier.BaseProperty)
    BasePropertyOrBuilder {
  // Use BaseProperty.newBuilder() to construct.
  private BaseProperty(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private BaseProperty() {
    name_ = "";
    visibility_ = 0;
    specifiedBy_ = java.util.Collections.emptyList();
    seeAlso_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private BaseProperty(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            com.github.jsdossier.proto.SourceLink.Builder subBuilder = null;
            if (source_ != null) {
              subBuilder = source_.toBuilder();
            }
            source_ = input.readMessage(com.github.jsdossier.proto.SourceLink.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(source_);
              source_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.github.jsdossier.proto.Comment.Builder subBuilder = null;
            if (description_ != null) {
              subBuilder = description_.toBuilder();
            }
            description_ = input.readMessage(com.github.jsdossier.proto.Comment.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(description_);
              description_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.github.jsdossier.proto.Comment.Builder subBuilder = null;
            if (deprecation_ != null) {
              subBuilder = deprecation_.toBuilder();
            }
            deprecation_ = input.readMessage(com.github.jsdossier.proto.Comment.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(deprecation_);
              deprecation_ = subBuilder.buildPartial();
            }

            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            visibility_ = rawValue;
            break;
          }
          case 50: {
            com.github.jsdossier.proto.Tags.Builder subBuilder = null;
            if (tags_ != null) {
              subBuilder = tags_.toBuilder();
            }
            tags_ = input.readMessage(com.github.jsdossier.proto.Tags.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(tags_);
              tags_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            com.github.jsdossier.proto.NamedType.Builder subBuilder = null;
            if (definedBy_ != null) {
              subBuilder = definedBy_.toBuilder();
            }
            definedBy_ = input.readMessage(com.github.jsdossier.proto.NamedType.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(definedBy_);
              definedBy_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            com.github.jsdossier.proto.NamedType.Builder subBuilder = null;
            if (overrides_ != null) {
              subBuilder = overrides_.toBuilder();
            }
            overrides_ = input.readMessage(com.github.jsdossier.proto.NamedType.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(overrides_);
              overrides_ = subBuilder.buildPartial();
            }

            break;
          }
          case 74: {
            if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
              specifiedBy_ = new java.util.ArrayList<com.github.jsdossier.proto.NamedType>();
              mutable_bitField0_ |= 0x00000100;
            }
            specifiedBy_.add(input.readMessage(com.github.jsdossier.proto.NamedType.parser(), extensionRegistry));
            break;
          }
          case 82: {
            if (!((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
              seeAlso_ = new java.util.ArrayList<com.github.jsdossier.proto.Comment>();
              mutable_bitField0_ |= 0x00000200;
            }
            seeAlso_.add(input.readMessage(com.github.jsdossier.proto.Comment.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
        specifiedBy_ = java.util.Collections.unmodifiableList(specifiedBy_);
      }
      if (((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
        seeAlso_ = java.util.Collections.unmodifiableList(seeAlso_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.jsdossier.proto.Dossier.internal_static_dossier_BaseProperty_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.jsdossier.proto.Dossier.internal_static_dossier_BaseProperty_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.jsdossier.proto.BaseProperty.class, com.github.jsdossier.proto.BaseProperty.Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>optional string name = 1;</code>
   *
   * <pre>
   * The property's name; this should not be the fully qualified name.
   * </pre>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>optional string name = 1;</code>
   *
   * <pre>
   * The property's name; this should not be the fully qualified name.
   * </pre>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCE_FIELD_NUMBER = 2;
  private com.github.jsdossier.proto.SourceLink source_;
  /**
   * <code>optional .dossier.SourceLink source = 2;</code>
   *
   * <pre>
   * Link to the location in the source file where this property is defined.
   * </pre>
   */
  public boolean hasSource() {
    return source_ != null;
  }
  /**
   * <code>optional .dossier.SourceLink source = 2;</code>
   *
   * <pre>
   * Link to the location in the source file where this property is defined.
   * </pre>
   */
  public com.github.jsdossier.proto.SourceLink getSource() {
    return source_ == null ? com.github.jsdossier.proto.SourceLink.getDefaultInstance() : source_;
  }
  /**
   * <code>optional .dossier.SourceLink source = 2;</code>
   *
   * <pre>
   * Link to the location in the source file where this property is defined.
   * </pre>
   */
  public com.github.jsdossier.proto.SourceLinkOrBuilder getSourceOrBuilder() {
    return getSource();
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 3;
  private com.github.jsdossier.proto.Comment description_;
  /**
   * <code>optional .dossier.Comment description = 3;</code>
   *
   * <pre>
   * The property's block comment.
   * </pre>
   */
  public boolean hasDescription() {
    return description_ != null;
  }
  /**
   * <code>optional .dossier.Comment description = 3;</code>
   *
   * <pre>
   * The property's block comment.
   * </pre>
   */
  public com.github.jsdossier.proto.Comment getDescription() {
    return description_ == null ? com.github.jsdossier.proto.Comment.getDefaultInstance() : description_;
  }
  /**
   * <code>optional .dossier.Comment description = 3;</code>
   *
   * <pre>
   * The property's block comment.
   * </pre>
   */
  public com.github.jsdossier.proto.CommentOrBuilder getDescriptionOrBuilder() {
    return getDescription();
  }

  public static final int DEPRECATION_FIELD_NUMBER = 4;
  private com.github.jsdossier.proto.Comment deprecation_;
  /**
   * <code>optional .dossier.Comment deprecation = 4;</code>
   *
   * <pre>
   * Whether this property is deprecated.
   * </pre>
   */
  public boolean hasDeprecation() {
    return deprecation_ != null;
  }
  /**
   * <code>optional .dossier.Comment deprecation = 4;</code>
   *
   * <pre>
   * Whether this property is deprecated.
   * </pre>
   */
  public com.github.jsdossier.proto.Comment getDeprecation() {
    return deprecation_ == null ? com.github.jsdossier.proto.Comment.getDefaultInstance() : deprecation_;
  }
  /**
   * <code>optional .dossier.Comment deprecation = 4;</code>
   *
   * <pre>
   * Whether this property is deprecated.
   * </pre>
   */
  public com.github.jsdossier.proto.CommentOrBuilder getDeprecationOrBuilder() {
    return getDeprecation();
  }

  public static final int VISIBILITY_FIELD_NUMBER = 5;
  private int visibility_;
  /**
   * <code>optional .dossier.Visibility visibility = 5;</code>
   */
  public int getVisibilityValue() {
    return visibility_;
  }
  /**
   * <code>optional .dossier.Visibility visibility = 5;</code>
   */
  public com.github.jsdossier.proto.Visibility getVisibility() {
    com.github.jsdossier.proto.Visibility result = com.github.jsdossier.proto.Visibility.valueOf(visibility_);
    return result == null ? com.github.jsdossier.proto.Visibility.UNRECOGNIZED : result;
  }

  public static final int TAGS_FIELD_NUMBER = 6;
  private com.github.jsdossier.proto.Tags tags_;
  /**
   * <code>optional .dossier.Tags tags = 6;</code>
   */
  public boolean hasTags() {
    return tags_ != null;
  }
  /**
   * <code>optional .dossier.Tags tags = 6;</code>
   */
  public com.github.jsdossier.proto.Tags getTags() {
    return tags_ == null ? com.github.jsdossier.proto.Tags.getDefaultInstance() : tags_;
  }
  /**
   * <code>optional .dossier.Tags tags = 6;</code>
   */
  public com.github.jsdossier.proto.TagsOrBuilder getTagsOrBuilder() {
    return getTags();
  }

  public static final int DEFINED_BY_FIELD_NUMBER = 7;
  private com.github.jsdossier.proto.NamedType definedBy_;
  /**
   * <code>optional .dossier.expression.NamedType defined_by = 7;</code>
   *
   * <pre>
   * The class or interface that defines this property.
   * </pre>
   */
  public boolean hasDefinedBy() {
    return definedBy_ != null;
  }
  /**
   * <code>optional .dossier.expression.NamedType defined_by = 7;</code>
   *
   * <pre>
   * The class or interface that defines this property.
   * </pre>
   */
  public com.github.jsdossier.proto.NamedType getDefinedBy() {
    return definedBy_ == null ? com.github.jsdossier.proto.NamedType.getDefaultInstance() : definedBy_;
  }
  /**
   * <code>optional .dossier.expression.NamedType defined_by = 7;</code>
   *
   * <pre>
   * The class or interface that defines this property.
   * </pre>
   */
  public com.github.jsdossier.proto.NamedTypeOrBuilder getDefinedByOrBuilder() {
    return getDefinedBy();
  }

  public static final int OVERRIDES_FIELD_NUMBER = 8;
  private com.github.jsdossier.proto.NamedType overrides_;
  /**
   * <code>optional .dossier.expression.NamedType overrides = 8;</code>
   *
   * <pre>
   * Parent class that defines this property.
   * </pre>
   */
  public boolean hasOverrides() {
    return overrides_ != null;
  }
  /**
   * <code>optional .dossier.expression.NamedType overrides = 8;</code>
   *
   * <pre>
   * Parent class that defines this property.
   * </pre>
   */
  public com.github.jsdossier.proto.NamedType getOverrides() {
    return overrides_ == null ? com.github.jsdossier.proto.NamedType.getDefaultInstance() : overrides_;
  }
  /**
   * <code>optional .dossier.expression.NamedType overrides = 8;</code>
   *
   * <pre>
   * Parent class that defines this property.
   * </pre>
   */
  public com.github.jsdossier.proto.NamedTypeOrBuilder getOverridesOrBuilder() {
    return getOverrides();
  }

  public static final int SPECIFIED_BY_FIELD_NUMBER = 9;
  private java.util.List<com.github.jsdossier.proto.NamedType> specifiedBy_;
  /**
   * <code>repeated .dossier.expression.NamedType specified_by = 9;</code>
   *
   * <pre>
   * Interfaces that define this property.
   * </pre>
   */
  public java.util.List<com.github.jsdossier.proto.NamedType> getSpecifiedByList() {
    return specifiedBy_;
  }
  /**
   * <code>repeated .dossier.expression.NamedType specified_by = 9;</code>
   *
   * <pre>
   * Interfaces that define this property.
   * </pre>
   */
  public java.util.List<? extends com.github.jsdossier.proto.NamedTypeOrBuilder> 
      getSpecifiedByOrBuilderList() {
    return specifiedBy_;
  }
  /**
   * <code>repeated .dossier.expression.NamedType specified_by = 9;</code>
   *
   * <pre>
   * Interfaces that define this property.
   * </pre>
   */
  public int getSpecifiedByCount() {
    return specifiedBy_.size();
  }
  /**
   * <code>repeated .dossier.expression.NamedType specified_by = 9;</code>
   *
   * <pre>
   * Interfaces that define this property.
   * </pre>
   */
  public com.github.jsdossier.proto.NamedType getSpecifiedBy(int index) {
    return specifiedBy_.get(index);
  }
  /**
   * <code>repeated .dossier.expression.NamedType specified_by = 9;</code>
   *
   * <pre>
   * Interfaces that define this property.
   * </pre>
   */
  public com.github.jsdossier.proto.NamedTypeOrBuilder getSpecifiedByOrBuilder(
      int index) {
    return specifiedBy_.get(index);
  }

  public static final int SEE_ALSO_FIELD_NUMBER = 10;
  private java.util.List<com.github.jsdossier.proto.Comment> seeAlso_;
  /**
   * <code>repeated .dossier.Comment see_also = 10;</code>
   */
  public java.util.List<com.github.jsdossier.proto.Comment> getSeeAlsoList() {
    return seeAlso_;
  }
  /**
   * <code>repeated .dossier.Comment see_also = 10;</code>
   */
  public java.util.List<? extends com.github.jsdossier.proto.CommentOrBuilder> 
      getSeeAlsoOrBuilderList() {
    return seeAlso_;
  }
  /**
   * <code>repeated .dossier.Comment see_also = 10;</code>
   */
  public int getSeeAlsoCount() {
    return seeAlso_.size();
  }
  /**
   * <code>repeated .dossier.Comment see_also = 10;</code>
   */
  public com.github.jsdossier.proto.Comment getSeeAlso(int index) {
    return seeAlso_.get(index);
  }
  /**
   * <code>repeated .dossier.Comment see_also = 10;</code>
   */
  public com.github.jsdossier.proto.CommentOrBuilder getSeeAlsoOrBuilder(
      int index) {
    return seeAlso_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
    }
    if (source_ != null) {
      output.writeMessage(2, getSource());
    }
    if (description_ != null) {
      output.writeMessage(3, getDescription());
    }
    if (deprecation_ != null) {
      output.writeMessage(4, getDeprecation());
    }
    if (visibility_ != com.github.jsdossier.proto.Visibility.PUBLIC.getNumber()) {
      output.writeEnum(5, visibility_);
    }
    if (tags_ != null) {
      output.writeMessage(6, getTags());
    }
    if (definedBy_ != null) {
      output.writeMessage(7, getDefinedBy());
    }
    if (overrides_ != null) {
      output.writeMessage(8, getOverrides());
    }
    for (int i = 0; i < specifiedBy_.size(); i++) {
      output.writeMessage(9, specifiedBy_.get(i));
    }
    for (int i = 0; i < seeAlso_.size(); i++) {
      output.writeMessage(10, seeAlso_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
    }
    if (source_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getSource());
    }
    if (description_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getDescription());
    }
    if (deprecation_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getDeprecation());
    }
    if (visibility_ != com.github.jsdossier.proto.Visibility.PUBLIC.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, visibility_);
    }
    if (tags_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getTags());
    }
    if (definedBy_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getDefinedBy());
    }
    if (overrides_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getOverrides());
    }
    for (int i = 0; i < specifiedBy_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, specifiedBy_.get(i));
    }
    for (int i = 0; i < seeAlso_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, seeAlso_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static com.github.jsdossier.proto.BaseProperty parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.jsdossier.proto.BaseProperty parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.jsdossier.proto.BaseProperty parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.jsdossier.proto.BaseProperty parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.jsdossier.proto.BaseProperty parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.github.jsdossier.proto.BaseProperty parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.github.jsdossier.proto.BaseProperty parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.github.jsdossier.proto.BaseProperty parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.github.jsdossier.proto.BaseProperty parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.github.jsdossier.proto.BaseProperty parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.jsdossier.proto.BaseProperty prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dossier.BaseProperty}
   *
   * <pre>
   * Describes the basic properties for a documented JavaScript property.
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dossier.BaseProperty)
      com.github.jsdossier.proto.BasePropertyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.jsdossier.proto.Dossier.internal_static_dossier_BaseProperty_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.jsdossier.proto.Dossier.internal_static_dossier_BaseProperty_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.jsdossier.proto.BaseProperty.class, com.github.jsdossier.proto.BaseProperty.Builder.class);
    }

    // Construct using com.github.jsdossier.proto.BaseProperty.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getSpecifiedByFieldBuilder();
        getSeeAlsoFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      name_ = "";

      if (sourceBuilder_ == null) {
        source_ = null;
      } else {
        source_ = null;
        sourceBuilder_ = null;
      }
      if (descriptionBuilder_ == null) {
        description_ = null;
      } else {
        description_ = null;
        descriptionBuilder_ = null;
      }
      if (deprecationBuilder_ == null) {
        deprecation_ = null;
      } else {
        deprecation_ = null;
        deprecationBuilder_ = null;
      }
      visibility_ = 0;

      if (tagsBuilder_ == null) {
        tags_ = null;
      } else {
        tags_ = null;
        tagsBuilder_ = null;
      }
      if (definedByBuilder_ == null) {
        definedBy_ = null;
      } else {
        definedBy_ = null;
        definedByBuilder_ = null;
      }
      if (overridesBuilder_ == null) {
        overrides_ = null;
      } else {
        overrides_ = null;
        overridesBuilder_ = null;
      }
      if (specifiedByBuilder_ == null) {
        specifiedBy_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000100);
      } else {
        specifiedByBuilder_.clear();
      }
      if (seeAlsoBuilder_ == null) {
        seeAlso_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000200);
      } else {
        seeAlsoBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.jsdossier.proto.Dossier.internal_static_dossier_BaseProperty_descriptor;
    }

    public com.github.jsdossier.proto.BaseProperty getDefaultInstanceForType() {
      return com.github.jsdossier.proto.BaseProperty.getDefaultInstance();
    }

    public com.github.jsdossier.proto.BaseProperty build() {
      com.github.jsdossier.proto.BaseProperty result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.github.jsdossier.proto.BaseProperty buildPartial() {
      com.github.jsdossier.proto.BaseProperty result = new com.github.jsdossier.proto.BaseProperty(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.name_ = name_;
      if (sourceBuilder_ == null) {
        result.source_ = source_;
      } else {
        result.source_ = sourceBuilder_.build();
      }
      if (descriptionBuilder_ == null) {
        result.description_ = description_;
      } else {
        result.description_ = descriptionBuilder_.build();
      }
      if (deprecationBuilder_ == null) {
        result.deprecation_ = deprecation_;
      } else {
        result.deprecation_ = deprecationBuilder_.build();
      }
      result.visibility_ = visibility_;
      if (tagsBuilder_ == null) {
        result.tags_ = tags_;
      } else {
        result.tags_ = tagsBuilder_.build();
      }
      if (definedByBuilder_ == null) {
        result.definedBy_ = definedBy_;
      } else {
        result.definedBy_ = definedByBuilder_.build();
      }
      if (overridesBuilder_ == null) {
        result.overrides_ = overrides_;
      } else {
        result.overrides_ = overridesBuilder_.build();
      }
      if (specifiedByBuilder_ == null) {
        if (((bitField0_ & 0x00000100) == 0x00000100)) {
          specifiedBy_ = java.util.Collections.unmodifiableList(specifiedBy_);
          bitField0_ = (bitField0_ & ~0x00000100);
        }
        result.specifiedBy_ = specifiedBy_;
      } else {
        result.specifiedBy_ = specifiedByBuilder_.build();
      }
      if (seeAlsoBuilder_ == null) {
        if (((bitField0_ & 0x00000200) == 0x00000200)) {
          seeAlso_ = java.util.Collections.unmodifiableList(seeAlso_);
          bitField0_ = (bitField0_ & ~0x00000200);
        }
        result.seeAlso_ = seeAlso_;
      } else {
        result.seeAlso_ = seeAlsoBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.jsdossier.proto.BaseProperty) {
        return mergeFrom((com.github.jsdossier.proto.BaseProperty)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.jsdossier.proto.BaseProperty other) {
      if (other == com.github.jsdossier.proto.BaseProperty.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.hasSource()) {
        mergeSource(other.getSource());
      }
      if (other.hasDescription()) {
        mergeDescription(other.getDescription());
      }
      if (other.hasDeprecation()) {
        mergeDeprecation(other.getDeprecation());
      }
      if (other.visibility_ != 0) {
        setVisibilityValue(other.getVisibilityValue());
      }
      if (other.hasTags()) {
        mergeTags(other.getTags());
      }
      if (other.hasDefinedBy()) {
        mergeDefinedBy(other.getDefinedBy());
      }
      if (other.hasOverrides()) {
        mergeOverrides(other.getOverrides());
      }
      if (specifiedByBuilder_ == null) {
        if (!other.specifiedBy_.isEmpty()) {
          if (specifiedBy_.isEmpty()) {
            specifiedBy_ = other.specifiedBy_;
            bitField0_ = (bitField0_ & ~0x00000100);
          } else {
            ensureSpecifiedByIsMutable();
            specifiedBy_.addAll(other.specifiedBy_);
          }
          onChanged();
        }
      } else {
        if (!other.specifiedBy_.isEmpty()) {
          if (specifiedByBuilder_.isEmpty()) {
            specifiedByBuilder_.dispose();
            specifiedByBuilder_ = null;
            specifiedBy_ = other.specifiedBy_;
            bitField0_ = (bitField0_ & ~0x00000100);
            specifiedByBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getSpecifiedByFieldBuilder() : null;
          } else {
            specifiedByBuilder_.addAllMessages(other.specifiedBy_);
          }
        }
      }
      if (seeAlsoBuilder_ == null) {
        if (!other.seeAlso_.isEmpty()) {
          if (seeAlso_.isEmpty()) {
            seeAlso_ = other.seeAlso_;
            bitField0_ = (bitField0_ & ~0x00000200);
          } else {
            ensureSeeAlsoIsMutable();
            seeAlso_.addAll(other.seeAlso_);
          }
          onChanged();
        }
      } else {
        if (!other.seeAlso_.isEmpty()) {
          if (seeAlsoBuilder_.isEmpty()) {
            seeAlsoBuilder_.dispose();
            seeAlsoBuilder_ = null;
            seeAlso_ = other.seeAlso_;
            bitField0_ = (bitField0_ & ~0x00000200);
            seeAlsoBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getSeeAlsoFieldBuilder() : null;
          } else {
            seeAlsoBuilder_.addAllMessages(other.seeAlso_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.jsdossier.proto.BaseProperty parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.jsdossier.proto.BaseProperty) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     * The property's name; this should not be the fully qualified name.
     * </pre>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     * The property's name; this should not be the fully qualified name.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     * The property's name; this should not be the fully qualified name.
     * </pre>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     * The property's name; this should not be the fully qualified name.
     * </pre>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     * The property's name; this should not be the fully qualified name.
     * </pre>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private com.github.jsdossier.proto.SourceLink source_ = null;
    private com.google.protobuf.SingleFieldBuilder<
        com.github.jsdossier.proto.SourceLink, com.github.jsdossier.proto.SourceLink.Builder, com.github.jsdossier.proto.SourceLinkOrBuilder> sourceBuilder_;
    /**
     * <code>optional .dossier.SourceLink source = 2;</code>
     *
     * <pre>
     * Link to the location in the source file where this property is defined.
     * </pre>
     */
    public boolean hasSource() {
      return sourceBuilder_ != null || source_ != null;
    }
    /**
     * <code>optional .dossier.SourceLink source = 2;</code>
     *
     * <pre>
     * Link to the location in the source file where this property is defined.
     * </pre>
     */
    public com.github.jsdossier.proto.SourceLink getSource() {
      if (sourceBuilder_ == null) {
        return source_ == null ? com.github.jsdossier.proto.SourceLink.getDefaultInstance() : source_;
      } else {
        return sourceBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .dossier.SourceLink source = 2;</code>
     *
     * <pre>
     * Link to the location in the source file where this property is defined.
     * </pre>
     */
    public Builder setSource(com.github.jsdossier.proto.SourceLink value) {
      if (sourceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        source_ = value;
        onChanged();
      } else {
        sourceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .dossier.SourceLink source = 2;</code>
     *
     * <pre>
     * Link to the location in the source file where this property is defined.
     * </pre>
     */
    public Builder setSource(
        com.github.jsdossier.proto.SourceLink.Builder builderForValue) {
      if (sourceBuilder_ == null) {
        source_ = builderForValue.build();
        onChanged();
      } else {
        sourceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .dossier.SourceLink source = 2;</code>
     *
     * <pre>
     * Link to the location in the source file where this property is defined.
     * </pre>
     */
    public Builder mergeSource(com.github.jsdossier.proto.SourceLink value) {
      if (sourceBuilder_ == null) {
        if (source_ != null) {
          source_ =
            com.github.jsdossier.proto.SourceLink.newBuilder(source_).mergeFrom(value).buildPartial();
        } else {
          source_ = value;
        }
        onChanged();
      } else {
        sourceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .dossier.SourceLink source = 2;</code>
     *
     * <pre>
     * Link to the location in the source file where this property is defined.
     * </pre>
     */
    public Builder clearSource() {
      if (sourceBuilder_ == null) {
        source_ = null;
        onChanged();
      } else {
        source_ = null;
        sourceBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .dossier.SourceLink source = 2;</code>
     *
     * <pre>
     * Link to the location in the source file where this property is defined.
     * </pre>
     */
    public com.github.jsdossier.proto.SourceLink.Builder getSourceBuilder() {
      
      onChanged();
      return getSourceFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .dossier.SourceLink source = 2;</code>
     *
     * <pre>
     * Link to the location in the source file where this property is defined.
     * </pre>
     */
    public com.github.jsdossier.proto.SourceLinkOrBuilder getSourceOrBuilder() {
      if (sourceBuilder_ != null) {
        return sourceBuilder_.getMessageOrBuilder();
      } else {
        return source_ == null ?
            com.github.jsdossier.proto.SourceLink.getDefaultInstance() : source_;
      }
    }
    /**
     * <code>optional .dossier.SourceLink source = 2;</code>
     *
     * <pre>
     * Link to the location in the source file where this property is defined.
     * </pre>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.github.jsdossier.proto.SourceLink, com.github.jsdossier.proto.SourceLink.Builder, com.github.jsdossier.proto.SourceLinkOrBuilder> 
        getSourceFieldBuilder() {
      if (sourceBuilder_ == null) {
        sourceBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.github.jsdossier.proto.SourceLink, com.github.jsdossier.proto.SourceLink.Builder, com.github.jsdossier.proto.SourceLinkOrBuilder>(
                getSource(),
                getParentForChildren(),
                isClean());
        source_ = null;
      }
      return sourceBuilder_;
    }

    private com.github.jsdossier.proto.Comment description_ = null;
    private com.google.protobuf.SingleFieldBuilder<
        com.github.jsdossier.proto.Comment, com.github.jsdossier.proto.Comment.Builder, com.github.jsdossier.proto.CommentOrBuilder> descriptionBuilder_;
    /**
     * <code>optional .dossier.Comment description = 3;</code>
     *
     * <pre>
     * The property's block comment.
     * </pre>
     */
    public boolean hasDescription() {
      return descriptionBuilder_ != null || description_ != null;
    }
    /**
     * <code>optional .dossier.Comment description = 3;</code>
     *
     * <pre>
     * The property's block comment.
     * </pre>
     */
    public com.github.jsdossier.proto.Comment getDescription() {
      if (descriptionBuilder_ == null) {
        return description_ == null ? com.github.jsdossier.proto.Comment.getDefaultInstance() : description_;
      } else {
        return descriptionBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .dossier.Comment description = 3;</code>
     *
     * <pre>
     * The property's block comment.
     * </pre>
     */
    public Builder setDescription(com.github.jsdossier.proto.Comment value) {
      if (descriptionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        description_ = value;
        onChanged();
      } else {
        descriptionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .dossier.Comment description = 3;</code>
     *
     * <pre>
     * The property's block comment.
     * </pre>
     */
    public Builder setDescription(
        com.github.jsdossier.proto.Comment.Builder builderForValue) {
      if (descriptionBuilder_ == null) {
        description_ = builderForValue.build();
        onChanged();
      } else {
        descriptionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .dossier.Comment description = 3;</code>
     *
     * <pre>
     * The property's block comment.
     * </pre>
     */
    public Builder mergeDescription(com.github.jsdossier.proto.Comment value) {
      if (descriptionBuilder_ == null) {
        if (description_ != null) {
          description_ =
            com.github.jsdossier.proto.Comment.newBuilder(description_).mergeFrom(value).buildPartial();
        } else {
          description_ = value;
        }
        onChanged();
      } else {
        descriptionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .dossier.Comment description = 3;</code>
     *
     * <pre>
     * The property's block comment.
     * </pre>
     */
    public Builder clearDescription() {
      if (descriptionBuilder_ == null) {
        description_ = null;
        onChanged();
      } else {
        description_ = null;
        descriptionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .dossier.Comment description = 3;</code>
     *
     * <pre>
     * The property's block comment.
     * </pre>
     */
    public com.github.jsdossier.proto.Comment.Builder getDescriptionBuilder() {
      
      onChanged();
      return getDescriptionFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .dossier.Comment description = 3;</code>
     *
     * <pre>
     * The property's block comment.
     * </pre>
     */
    public com.github.jsdossier.proto.CommentOrBuilder getDescriptionOrBuilder() {
      if (descriptionBuilder_ != null) {
        return descriptionBuilder_.getMessageOrBuilder();
      } else {
        return description_ == null ?
            com.github.jsdossier.proto.Comment.getDefaultInstance() : description_;
      }
    }
    /**
     * <code>optional .dossier.Comment description = 3;</code>
     *
     * <pre>
     * The property's block comment.
     * </pre>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.github.jsdossier.proto.Comment, com.github.jsdossier.proto.Comment.Builder, com.github.jsdossier.proto.CommentOrBuilder> 
        getDescriptionFieldBuilder() {
      if (descriptionBuilder_ == null) {
        descriptionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.github.jsdossier.proto.Comment, com.github.jsdossier.proto.Comment.Builder, com.github.jsdossier.proto.CommentOrBuilder>(
                getDescription(),
                getParentForChildren(),
                isClean());
        description_ = null;
      }
      return descriptionBuilder_;
    }

    private com.github.jsdossier.proto.Comment deprecation_ = null;
    private com.google.protobuf.SingleFieldBuilder<
        com.github.jsdossier.proto.Comment, com.github.jsdossier.proto.Comment.Builder, com.github.jsdossier.proto.CommentOrBuilder> deprecationBuilder_;
    /**
     * <code>optional .dossier.Comment deprecation = 4;</code>
     *
     * <pre>
     * Whether this property is deprecated.
     * </pre>
     */
    public boolean hasDeprecation() {
      return deprecationBuilder_ != null || deprecation_ != null;
    }
    /**
     * <code>optional .dossier.Comment deprecation = 4;</code>
     *
     * <pre>
     * Whether this property is deprecated.
     * </pre>
     */
    public com.github.jsdossier.proto.Comment getDeprecation() {
      if (deprecationBuilder_ == null) {
        return deprecation_ == null ? com.github.jsdossier.proto.Comment.getDefaultInstance() : deprecation_;
      } else {
        return deprecationBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .dossier.Comment deprecation = 4;</code>
     *
     * <pre>
     * Whether this property is deprecated.
     * </pre>
     */
    public Builder setDeprecation(com.github.jsdossier.proto.Comment value) {
      if (deprecationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        deprecation_ = value;
        onChanged();
      } else {
        deprecationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .dossier.Comment deprecation = 4;</code>
     *
     * <pre>
     * Whether this property is deprecated.
     * </pre>
     */
    public Builder setDeprecation(
        com.github.jsdossier.proto.Comment.Builder builderForValue) {
      if (deprecationBuilder_ == null) {
        deprecation_ = builderForValue.build();
        onChanged();
      } else {
        deprecationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .dossier.Comment deprecation = 4;</code>
     *
     * <pre>
     * Whether this property is deprecated.
     * </pre>
     */
    public Builder mergeDeprecation(com.github.jsdossier.proto.Comment value) {
      if (deprecationBuilder_ == null) {
        if (deprecation_ != null) {
          deprecation_ =
            com.github.jsdossier.proto.Comment.newBuilder(deprecation_).mergeFrom(value).buildPartial();
        } else {
          deprecation_ = value;
        }
        onChanged();
      } else {
        deprecationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .dossier.Comment deprecation = 4;</code>
     *
     * <pre>
     * Whether this property is deprecated.
     * </pre>
     */
    public Builder clearDeprecation() {
      if (deprecationBuilder_ == null) {
        deprecation_ = null;
        onChanged();
      } else {
        deprecation_ = null;
        deprecationBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .dossier.Comment deprecation = 4;</code>
     *
     * <pre>
     * Whether this property is deprecated.
     * </pre>
     */
    public com.github.jsdossier.proto.Comment.Builder getDeprecationBuilder() {
      
      onChanged();
      return getDeprecationFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .dossier.Comment deprecation = 4;</code>
     *
     * <pre>
     * Whether this property is deprecated.
     * </pre>
     */
    public com.github.jsdossier.proto.CommentOrBuilder getDeprecationOrBuilder() {
      if (deprecationBuilder_ != null) {
        return deprecationBuilder_.getMessageOrBuilder();
      } else {
        return deprecation_ == null ?
            com.github.jsdossier.proto.Comment.getDefaultInstance() : deprecation_;
      }
    }
    /**
     * <code>optional .dossier.Comment deprecation = 4;</code>
     *
     * <pre>
     * Whether this property is deprecated.
     * </pre>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.github.jsdossier.proto.Comment, com.github.jsdossier.proto.Comment.Builder, com.github.jsdossier.proto.CommentOrBuilder> 
        getDeprecationFieldBuilder() {
      if (deprecationBuilder_ == null) {
        deprecationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.github.jsdossier.proto.Comment, com.github.jsdossier.proto.Comment.Builder, com.github.jsdossier.proto.CommentOrBuilder>(
                getDeprecation(),
                getParentForChildren(),
                isClean());
        deprecation_ = null;
      }
      return deprecationBuilder_;
    }

    private int visibility_ = 0;
    /**
     * <code>optional .dossier.Visibility visibility = 5;</code>
     */
    public int getVisibilityValue() {
      return visibility_;
    }
    /**
     * <code>optional .dossier.Visibility visibility = 5;</code>
     */
    public Builder setVisibilityValue(int value) {
      visibility_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .dossier.Visibility visibility = 5;</code>
     */
    public com.github.jsdossier.proto.Visibility getVisibility() {
      com.github.jsdossier.proto.Visibility result = com.github.jsdossier.proto.Visibility.valueOf(visibility_);
      return result == null ? com.github.jsdossier.proto.Visibility.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .dossier.Visibility visibility = 5;</code>
     */
    public Builder setVisibility(com.github.jsdossier.proto.Visibility value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      visibility_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .dossier.Visibility visibility = 5;</code>
     */
    public Builder clearVisibility() {
      
      visibility_ = 0;
      onChanged();
      return this;
    }

    private com.github.jsdossier.proto.Tags tags_ = null;
    private com.google.protobuf.SingleFieldBuilder<
        com.github.jsdossier.proto.Tags, com.github.jsdossier.proto.Tags.Builder, com.github.jsdossier.proto.TagsOrBuilder> tagsBuilder_;
    /**
     * <code>optional .dossier.Tags tags = 6;</code>
     */
    public boolean hasTags() {
      return tagsBuilder_ != null || tags_ != null;
    }
    /**
     * <code>optional .dossier.Tags tags = 6;</code>
     */
    public com.github.jsdossier.proto.Tags getTags() {
      if (tagsBuilder_ == null) {
        return tags_ == null ? com.github.jsdossier.proto.Tags.getDefaultInstance() : tags_;
      } else {
        return tagsBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .dossier.Tags tags = 6;</code>
     */
    public Builder setTags(com.github.jsdossier.proto.Tags value) {
      if (tagsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        tags_ = value;
        onChanged();
      } else {
        tagsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .dossier.Tags tags = 6;</code>
     */
    public Builder setTags(
        com.github.jsdossier.proto.Tags.Builder builderForValue) {
      if (tagsBuilder_ == null) {
        tags_ = builderForValue.build();
        onChanged();
      } else {
        tagsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .dossier.Tags tags = 6;</code>
     */
    public Builder mergeTags(com.github.jsdossier.proto.Tags value) {
      if (tagsBuilder_ == null) {
        if (tags_ != null) {
          tags_ =
            com.github.jsdossier.proto.Tags.newBuilder(tags_).mergeFrom(value).buildPartial();
        } else {
          tags_ = value;
        }
        onChanged();
      } else {
        tagsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .dossier.Tags tags = 6;</code>
     */
    public Builder clearTags() {
      if (tagsBuilder_ == null) {
        tags_ = null;
        onChanged();
      } else {
        tags_ = null;
        tagsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .dossier.Tags tags = 6;</code>
     */
    public com.github.jsdossier.proto.Tags.Builder getTagsBuilder() {
      
      onChanged();
      return getTagsFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .dossier.Tags tags = 6;</code>
     */
    public com.github.jsdossier.proto.TagsOrBuilder getTagsOrBuilder() {
      if (tagsBuilder_ != null) {
        return tagsBuilder_.getMessageOrBuilder();
      } else {
        return tags_ == null ?
            com.github.jsdossier.proto.Tags.getDefaultInstance() : tags_;
      }
    }
    /**
     * <code>optional .dossier.Tags tags = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.github.jsdossier.proto.Tags, com.github.jsdossier.proto.Tags.Builder, com.github.jsdossier.proto.TagsOrBuilder> 
        getTagsFieldBuilder() {
      if (tagsBuilder_ == null) {
        tagsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.github.jsdossier.proto.Tags, com.github.jsdossier.proto.Tags.Builder, com.github.jsdossier.proto.TagsOrBuilder>(
                getTags(),
                getParentForChildren(),
                isClean());
        tags_ = null;
      }
      return tagsBuilder_;
    }

    private com.github.jsdossier.proto.NamedType definedBy_ = null;
    private com.google.protobuf.SingleFieldBuilder<
        com.github.jsdossier.proto.NamedType, com.github.jsdossier.proto.NamedType.Builder, com.github.jsdossier.proto.NamedTypeOrBuilder> definedByBuilder_;
    /**
     * <code>optional .dossier.expression.NamedType defined_by = 7;</code>
     *
     * <pre>
     * The class or interface that defines this property.
     * </pre>
     */
    public boolean hasDefinedBy() {
      return definedByBuilder_ != null || definedBy_ != null;
    }
    /**
     * <code>optional .dossier.expression.NamedType defined_by = 7;</code>
     *
     * <pre>
     * The class or interface that defines this property.
     * </pre>
     */
    public com.github.jsdossier.proto.NamedType getDefinedBy() {
      if (definedByBuilder_ == null) {
        return definedBy_ == null ? com.github.jsdossier.proto.NamedType.getDefaultInstance() : definedBy_;
      } else {
        return definedByBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .dossier.expression.NamedType defined_by = 7;</code>
     *
     * <pre>
     * The class or interface that defines this property.
     * </pre>
     */
    public Builder setDefinedBy(com.github.jsdossier.proto.NamedType value) {
      if (definedByBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        definedBy_ = value;
        onChanged();
      } else {
        definedByBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .dossier.expression.NamedType defined_by = 7;</code>
     *
     * <pre>
     * The class or interface that defines this property.
     * </pre>
     */
    public Builder setDefinedBy(
        com.github.jsdossier.proto.NamedType.Builder builderForValue) {
      if (definedByBuilder_ == null) {
        definedBy_ = builderForValue.build();
        onChanged();
      } else {
        definedByBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .dossier.expression.NamedType defined_by = 7;</code>
     *
     * <pre>
     * The class or interface that defines this property.
     * </pre>
     */
    public Builder mergeDefinedBy(com.github.jsdossier.proto.NamedType value) {
      if (definedByBuilder_ == null) {
        if (definedBy_ != null) {
          definedBy_ =
            com.github.jsdossier.proto.NamedType.newBuilder(definedBy_).mergeFrom(value).buildPartial();
        } else {
          definedBy_ = value;
        }
        onChanged();
      } else {
        definedByBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .dossier.expression.NamedType defined_by = 7;</code>
     *
     * <pre>
     * The class or interface that defines this property.
     * </pre>
     */
    public Builder clearDefinedBy() {
      if (definedByBuilder_ == null) {
        definedBy_ = null;
        onChanged();
      } else {
        definedBy_ = null;
        definedByBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .dossier.expression.NamedType defined_by = 7;</code>
     *
     * <pre>
     * The class or interface that defines this property.
     * </pre>
     */
    public com.github.jsdossier.proto.NamedType.Builder getDefinedByBuilder() {
      
      onChanged();
      return getDefinedByFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .dossier.expression.NamedType defined_by = 7;</code>
     *
     * <pre>
     * The class or interface that defines this property.
     * </pre>
     */
    public com.github.jsdossier.proto.NamedTypeOrBuilder getDefinedByOrBuilder() {
      if (definedByBuilder_ != null) {
        return definedByBuilder_.getMessageOrBuilder();
      } else {
        return definedBy_ == null ?
            com.github.jsdossier.proto.NamedType.getDefaultInstance() : definedBy_;
      }
    }
    /**
     * <code>optional .dossier.expression.NamedType defined_by = 7;</code>
     *
     * <pre>
     * The class or interface that defines this property.
     * </pre>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.github.jsdossier.proto.NamedType, com.github.jsdossier.proto.NamedType.Builder, com.github.jsdossier.proto.NamedTypeOrBuilder> 
        getDefinedByFieldBuilder() {
      if (definedByBuilder_ == null) {
        definedByBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.github.jsdossier.proto.NamedType, com.github.jsdossier.proto.NamedType.Builder, com.github.jsdossier.proto.NamedTypeOrBuilder>(
                getDefinedBy(),
                getParentForChildren(),
                isClean());
        definedBy_ = null;
      }
      return definedByBuilder_;
    }

    private com.github.jsdossier.proto.NamedType overrides_ = null;
    private com.google.protobuf.SingleFieldBuilder<
        com.github.jsdossier.proto.NamedType, com.github.jsdossier.proto.NamedType.Builder, com.github.jsdossier.proto.NamedTypeOrBuilder> overridesBuilder_;
    /**
     * <code>optional .dossier.expression.NamedType overrides = 8;</code>
     *
     * <pre>
     * Parent class that defines this property.
     * </pre>
     */
    public boolean hasOverrides() {
      return overridesBuilder_ != null || overrides_ != null;
    }
    /**
     * <code>optional .dossier.expression.NamedType overrides = 8;</code>
     *
     * <pre>
     * Parent class that defines this property.
     * </pre>
     */
    public com.github.jsdossier.proto.NamedType getOverrides() {
      if (overridesBuilder_ == null) {
        return overrides_ == null ? com.github.jsdossier.proto.NamedType.getDefaultInstance() : overrides_;
      } else {
        return overridesBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .dossier.expression.NamedType overrides = 8;</code>
     *
     * <pre>
     * Parent class that defines this property.
     * </pre>
     */
    public Builder setOverrides(com.github.jsdossier.proto.NamedType value) {
      if (overridesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        overrides_ = value;
        onChanged();
      } else {
        overridesBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .dossier.expression.NamedType overrides = 8;</code>
     *
     * <pre>
     * Parent class that defines this property.
     * </pre>
     */
    public Builder setOverrides(
        com.github.jsdossier.proto.NamedType.Builder builderForValue) {
      if (overridesBuilder_ == null) {
        overrides_ = builderForValue.build();
        onChanged();
      } else {
        overridesBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .dossier.expression.NamedType overrides = 8;</code>
     *
     * <pre>
     * Parent class that defines this property.
     * </pre>
     */
    public Builder mergeOverrides(com.github.jsdossier.proto.NamedType value) {
      if (overridesBuilder_ == null) {
        if (overrides_ != null) {
          overrides_ =
            com.github.jsdossier.proto.NamedType.newBuilder(overrides_).mergeFrom(value).buildPartial();
        } else {
          overrides_ = value;
        }
        onChanged();
      } else {
        overridesBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .dossier.expression.NamedType overrides = 8;</code>
     *
     * <pre>
     * Parent class that defines this property.
     * </pre>
     */
    public Builder clearOverrides() {
      if (overridesBuilder_ == null) {
        overrides_ = null;
        onChanged();
      } else {
        overrides_ = null;
        overridesBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .dossier.expression.NamedType overrides = 8;</code>
     *
     * <pre>
     * Parent class that defines this property.
     * </pre>
     */
    public com.github.jsdossier.proto.NamedType.Builder getOverridesBuilder() {
      
      onChanged();
      return getOverridesFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .dossier.expression.NamedType overrides = 8;</code>
     *
     * <pre>
     * Parent class that defines this property.
     * </pre>
     */
    public com.github.jsdossier.proto.NamedTypeOrBuilder getOverridesOrBuilder() {
      if (overridesBuilder_ != null) {
        return overridesBuilder_.getMessageOrBuilder();
      } else {
        return overrides_ == null ?
            com.github.jsdossier.proto.NamedType.getDefaultInstance() : overrides_;
      }
    }
    /**
     * <code>optional .dossier.expression.NamedType overrides = 8;</code>
     *
     * <pre>
     * Parent class that defines this property.
     * </pre>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.github.jsdossier.proto.NamedType, com.github.jsdossier.proto.NamedType.Builder, com.github.jsdossier.proto.NamedTypeOrBuilder> 
        getOverridesFieldBuilder() {
      if (overridesBuilder_ == null) {
        overridesBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.github.jsdossier.proto.NamedType, com.github.jsdossier.proto.NamedType.Builder, com.github.jsdossier.proto.NamedTypeOrBuilder>(
                getOverrides(),
                getParentForChildren(),
                isClean());
        overrides_ = null;
      }
      return overridesBuilder_;
    }

    private java.util.List<com.github.jsdossier.proto.NamedType> specifiedBy_ =
      java.util.Collections.emptyList();
    private void ensureSpecifiedByIsMutable() {
      if (!((bitField0_ & 0x00000100) == 0x00000100)) {
        specifiedBy_ = new java.util.ArrayList<com.github.jsdossier.proto.NamedType>(specifiedBy_);
        bitField0_ |= 0x00000100;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.github.jsdossier.proto.NamedType, com.github.jsdossier.proto.NamedType.Builder, com.github.jsdossier.proto.NamedTypeOrBuilder> specifiedByBuilder_;

    /**
     * <code>repeated .dossier.expression.NamedType specified_by = 9;</code>
     *
     * <pre>
     * Interfaces that define this property.
     * </pre>
     */
    public java.util.List<com.github.jsdossier.proto.NamedType> getSpecifiedByList() {
      if (specifiedByBuilder_ == null) {
        return java.util.Collections.unmodifiableList(specifiedBy_);
      } else {
        return specifiedByBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .dossier.expression.NamedType specified_by = 9;</code>
     *
     * <pre>
     * Interfaces that define this property.
     * </pre>
     */
    public int getSpecifiedByCount() {
      if (specifiedByBuilder_ == null) {
        return specifiedBy_.size();
      } else {
        return specifiedByBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .dossier.expression.NamedType specified_by = 9;</code>
     *
     * <pre>
     * Interfaces that define this property.
     * </pre>
     */
    public com.github.jsdossier.proto.NamedType getSpecifiedBy(int index) {
      if (specifiedByBuilder_ == null) {
        return specifiedBy_.get(index);
      } else {
        return specifiedByBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .dossier.expression.NamedType specified_by = 9;</code>
     *
     * <pre>
     * Interfaces that define this property.
     * </pre>
     */
    public Builder setSpecifiedBy(
        int index, com.github.jsdossier.proto.NamedType value) {
      if (specifiedByBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpecifiedByIsMutable();
        specifiedBy_.set(index, value);
        onChanged();
      } else {
        specifiedByBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dossier.expression.NamedType specified_by = 9;</code>
     *
     * <pre>
     * Interfaces that define this property.
     * </pre>
     */
    public Builder setSpecifiedBy(
        int index, com.github.jsdossier.proto.NamedType.Builder builderForValue) {
      if (specifiedByBuilder_ == null) {
        ensureSpecifiedByIsMutable();
        specifiedBy_.set(index, builderForValue.build());
        onChanged();
      } else {
        specifiedByBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dossier.expression.NamedType specified_by = 9;</code>
     *
     * <pre>
     * Interfaces that define this property.
     * </pre>
     */
    public Builder addSpecifiedBy(com.github.jsdossier.proto.NamedType value) {
      if (specifiedByBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpecifiedByIsMutable();
        specifiedBy_.add(value);
        onChanged();
      } else {
        specifiedByBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .dossier.expression.NamedType specified_by = 9;</code>
     *
     * <pre>
     * Interfaces that define this property.
     * </pre>
     */
    public Builder addSpecifiedBy(
        int index, com.github.jsdossier.proto.NamedType value) {
      if (specifiedByBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpecifiedByIsMutable();
        specifiedBy_.add(index, value);
        onChanged();
      } else {
        specifiedByBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dossier.expression.NamedType specified_by = 9;</code>
     *
     * <pre>
     * Interfaces that define this property.
     * </pre>
     */
    public Builder addSpecifiedBy(
        com.github.jsdossier.proto.NamedType.Builder builderForValue) {
      if (specifiedByBuilder_ == null) {
        ensureSpecifiedByIsMutable();
        specifiedBy_.add(builderForValue.build());
        onChanged();
      } else {
        specifiedByBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dossier.expression.NamedType specified_by = 9;</code>
     *
     * <pre>
     * Interfaces that define this property.
     * </pre>
     */
    public Builder addSpecifiedBy(
        int index, com.github.jsdossier.proto.NamedType.Builder builderForValue) {
      if (specifiedByBuilder_ == null) {
        ensureSpecifiedByIsMutable();
        specifiedBy_.add(index, builderForValue.build());
        onChanged();
      } else {
        specifiedByBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dossier.expression.NamedType specified_by = 9;</code>
     *
     * <pre>
     * Interfaces that define this property.
     * </pre>
     */
    public Builder addAllSpecifiedBy(
        java.lang.Iterable<? extends com.github.jsdossier.proto.NamedType> values) {
      if (specifiedByBuilder_ == null) {
        ensureSpecifiedByIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, specifiedBy_);
        onChanged();
      } else {
        specifiedByBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .dossier.expression.NamedType specified_by = 9;</code>
     *
     * <pre>
     * Interfaces that define this property.
     * </pre>
     */
    public Builder clearSpecifiedBy() {
      if (specifiedByBuilder_ == null) {
        specifiedBy_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
      } else {
        specifiedByBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .dossier.expression.NamedType specified_by = 9;</code>
     *
     * <pre>
     * Interfaces that define this property.
     * </pre>
     */
    public Builder removeSpecifiedBy(int index) {
      if (specifiedByBuilder_ == null) {
        ensureSpecifiedByIsMutable();
        specifiedBy_.remove(index);
        onChanged();
      } else {
        specifiedByBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .dossier.expression.NamedType specified_by = 9;</code>
     *
     * <pre>
     * Interfaces that define this property.
     * </pre>
     */
    public com.github.jsdossier.proto.NamedType.Builder getSpecifiedByBuilder(
        int index) {
      return getSpecifiedByFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .dossier.expression.NamedType specified_by = 9;</code>
     *
     * <pre>
     * Interfaces that define this property.
     * </pre>
     */
    public com.github.jsdossier.proto.NamedTypeOrBuilder getSpecifiedByOrBuilder(
        int index) {
      if (specifiedByBuilder_ == null) {
        return specifiedBy_.get(index);  } else {
        return specifiedByBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .dossier.expression.NamedType specified_by = 9;</code>
     *
     * <pre>
     * Interfaces that define this property.
     * </pre>
     */
    public java.util.List<? extends com.github.jsdossier.proto.NamedTypeOrBuilder> 
         getSpecifiedByOrBuilderList() {
      if (specifiedByBuilder_ != null) {
        return specifiedByBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(specifiedBy_);
      }
    }
    /**
     * <code>repeated .dossier.expression.NamedType specified_by = 9;</code>
     *
     * <pre>
     * Interfaces that define this property.
     * </pre>
     */
    public com.github.jsdossier.proto.NamedType.Builder addSpecifiedByBuilder() {
      return getSpecifiedByFieldBuilder().addBuilder(
          com.github.jsdossier.proto.NamedType.getDefaultInstance());
    }
    /**
     * <code>repeated .dossier.expression.NamedType specified_by = 9;</code>
     *
     * <pre>
     * Interfaces that define this property.
     * </pre>
     */
    public com.github.jsdossier.proto.NamedType.Builder addSpecifiedByBuilder(
        int index) {
      return getSpecifiedByFieldBuilder().addBuilder(
          index, com.github.jsdossier.proto.NamedType.getDefaultInstance());
    }
    /**
     * <code>repeated .dossier.expression.NamedType specified_by = 9;</code>
     *
     * <pre>
     * Interfaces that define this property.
     * </pre>
     */
    public java.util.List<com.github.jsdossier.proto.NamedType.Builder> 
         getSpecifiedByBuilderList() {
      return getSpecifiedByFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.github.jsdossier.proto.NamedType, com.github.jsdossier.proto.NamedType.Builder, com.github.jsdossier.proto.NamedTypeOrBuilder> 
        getSpecifiedByFieldBuilder() {
      if (specifiedByBuilder_ == null) {
        specifiedByBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.github.jsdossier.proto.NamedType, com.github.jsdossier.proto.NamedType.Builder, com.github.jsdossier.proto.NamedTypeOrBuilder>(
                specifiedBy_,
                ((bitField0_ & 0x00000100) == 0x00000100),
                getParentForChildren(),
                isClean());
        specifiedBy_ = null;
      }
      return specifiedByBuilder_;
    }

    private java.util.List<com.github.jsdossier.proto.Comment> seeAlso_ =
      java.util.Collections.emptyList();
    private void ensureSeeAlsoIsMutable() {
      if (!((bitField0_ & 0x00000200) == 0x00000200)) {
        seeAlso_ = new java.util.ArrayList<com.github.jsdossier.proto.Comment>(seeAlso_);
        bitField0_ |= 0x00000200;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.github.jsdossier.proto.Comment, com.github.jsdossier.proto.Comment.Builder, com.github.jsdossier.proto.CommentOrBuilder> seeAlsoBuilder_;

    /**
     * <code>repeated .dossier.Comment see_also = 10;</code>
     */
    public java.util.List<com.github.jsdossier.proto.Comment> getSeeAlsoList() {
      if (seeAlsoBuilder_ == null) {
        return java.util.Collections.unmodifiableList(seeAlso_);
      } else {
        return seeAlsoBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .dossier.Comment see_also = 10;</code>
     */
    public int getSeeAlsoCount() {
      if (seeAlsoBuilder_ == null) {
        return seeAlso_.size();
      } else {
        return seeAlsoBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .dossier.Comment see_also = 10;</code>
     */
    public com.github.jsdossier.proto.Comment getSeeAlso(int index) {
      if (seeAlsoBuilder_ == null) {
        return seeAlso_.get(index);
      } else {
        return seeAlsoBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .dossier.Comment see_also = 10;</code>
     */
    public Builder setSeeAlso(
        int index, com.github.jsdossier.proto.Comment value) {
      if (seeAlsoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSeeAlsoIsMutable();
        seeAlso_.set(index, value);
        onChanged();
      } else {
        seeAlsoBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dossier.Comment see_also = 10;</code>
     */
    public Builder setSeeAlso(
        int index, com.github.jsdossier.proto.Comment.Builder builderForValue) {
      if (seeAlsoBuilder_ == null) {
        ensureSeeAlsoIsMutable();
        seeAlso_.set(index, builderForValue.build());
        onChanged();
      } else {
        seeAlsoBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dossier.Comment see_also = 10;</code>
     */
    public Builder addSeeAlso(com.github.jsdossier.proto.Comment value) {
      if (seeAlsoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSeeAlsoIsMutable();
        seeAlso_.add(value);
        onChanged();
      } else {
        seeAlsoBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .dossier.Comment see_also = 10;</code>
     */
    public Builder addSeeAlso(
        int index, com.github.jsdossier.proto.Comment value) {
      if (seeAlsoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSeeAlsoIsMutable();
        seeAlso_.add(index, value);
        onChanged();
      } else {
        seeAlsoBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dossier.Comment see_also = 10;</code>
     */
    public Builder addSeeAlso(
        com.github.jsdossier.proto.Comment.Builder builderForValue) {
      if (seeAlsoBuilder_ == null) {
        ensureSeeAlsoIsMutable();
        seeAlso_.add(builderForValue.build());
        onChanged();
      } else {
        seeAlsoBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dossier.Comment see_also = 10;</code>
     */
    public Builder addSeeAlso(
        int index, com.github.jsdossier.proto.Comment.Builder builderForValue) {
      if (seeAlsoBuilder_ == null) {
        ensureSeeAlsoIsMutable();
        seeAlso_.add(index, builderForValue.build());
        onChanged();
      } else {
        seeAlsoBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dossier.Comment see_also = 10;</code>
     */
    public Builder addAllSeeAlso(
        java.lang.Iterable<? extends com.github.jsdossier.proto.Comment> values) {
      if (seeAlsoBuilder_ == null) {
        ensureSeeAlsoIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, seeAlso_);
        onChanged();
      } else {
        seeAlsoBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .dossier.Comment see_also = 10;</code>
     */
    public Builder clearSeeAlso() {
      if (seeAlsoBuilder_ == null) {
        seeAlso_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
      } else {
        seeAlsoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .dossier.Comment see_also = 10;</code>
     */
    public Builder removeSeeAlso(int index) {
      if (seeAlsoBuilder_ == null) {
        ensureSeeAlsoIsMutable();
        seeAlso_.remove(index);
        onChanged();
      } else {
        seeAlsoBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .dossier.Comment see_also = 10;</code>
     */
    public com.github.jsdossier.proto.Comment.Builder getSeeAlsoBuilder(
        int index) {
      return getSeeAlsoFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .dossier.Comment see_also = 10;</code>
     */
    public com.github.jsdossier.proto.CommentOrBuilder getSeeAlsoOrBuilder(
        int index) {
      if (seeAlsoBuilder_ == null) {
        return seeAlso_.get(index);  } else {
        return seeAlsoBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .dossier.Comment see_also = 10;</code>
     */
    public java.util.List<? extends com.github.jsdossier.proto.CommentOrBuilder> 
         getSeeAlsoOrBuilderList() {
      if (seeAlsoBuilder_ != null) {
        return seeAlsoBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(seeAlso_);
      }
    }
    /**
     * <code>repeated .dossier.Comment see_also = 10;</code>
     */
    public com.github.jsdossier.proto.Comment.Builder addSeeAlsoBuilder() {
      return getSeeAlsoFieldBuilder().addBuilder(
          com.github.jsdossier.proto.Comment.getDefaultInstance());
    }
    /**
     * <code>repeated .dossier.Comment see_also = 10;</code>
     */
    public com.github.jsdossier.proto.Comment.Builder addSeeAlsoBuilder(
        int index) {
      return getSeeAlsoFieldBuilder().addBuilder(
          index, com.github.jsdossier.proto.Comment.getDefaultInstance());
    }
    /**
     * <code>repeated .dossier.Comment see_also = 10;</code>
     */
    public java.util.List<com.github.jsdossier.proto.Comment.Builder> 
         getSeeAlsoBuilderList() {
      return getSeeAlsoFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.github.jsdossier.proto.Comment, com.github.jsdossier.proto.Comment.Builder, com.github.jsdossier.proto.CommentOrBuilder> 
        getSeeAlsoFieldBuilder() {
      if (seeAlsoBuilder_ == null) {
        seeAlsoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.github.jsdossier.proto.Comment, com.github.jsdossier.proto.Comment.Builder, com.github.jsdossier.proto.CommentOrBuilder>(
                seeAlso_,
                ((bitField0_ & 0x00000200) == 0x00000200),
                getParentForChildren(),
                isClean());
        seeAlso_ = null;
      }
      return seeAlsoBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:dossier.BaseProperty)
  }

  // @@protoc_insertion_point(class_scope:dossier.BaseProperty)
  private static final com.github.jsdossier.proto.BaseProperty DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.jsdossier.proto.BaseProperty();
  }

  public static com.github.jsdossier.proto.BaseProperty getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BaseProperty>
      PARSER = new com.google.protobuf.AbstractParser<BaseProperty>() {
    public BaseProperty parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new BaseProperty(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<BaseProperty> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BaseProperty> getParserForType() {
    return PARSER;
  }

  public com.github.jsdossier.proto.BaseProperty getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

