// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dossier.proto

package com.github.jsdossier.proto;

public interface FunctionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dossier.Function)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .dossier.BaseProperty base = 1;</code>
   */
  boolean hasBase();
  /**
   * <code>required .dossier.BaseProperty base = 1;</code>
   */
  com.github.jsdossier.proto.BaseProperty getBase();
  /**
   * <code>required .dossier.BaseProperty base = 1;</code>
   */
  com.github.jsdossier.proto.BasePropertyOrBuilder getBaseOrBuilder();

  /**
   * <code>repeated string template_name = 2;</code>
   */
  com.google.protobuf.ProtocolStringList
      getTemplateNameList();
  /**
   * <code>repeated string template_name = 2;</code>
   */
  int getTemplateNameCount();
  /**
   * <code>repeated string template_name = 2;</code>
   */
  java.lang.String getTemplateName(int index);
  /**
   * <code>repeated string template_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getTemplateNameBytes(int index);

  /**
   * <code>optional bool is_constructor = 3 [default = false];</code>
   */
  boolean hasIsConstructor();
  /**
   * <code>optional bool is_constructor = 3 [default = false];</code>
   */
  boolean getIsConstructor();

  /**
   * <code>repeated .dossier.Function.Detail parameter = 4;</code>
   */
  java.util.List<com.github.jsdossier.proto.Function.Detail> 
      getParameterList();
  /**
   * <code>repeated .dossier.Function.Detail parameter = 4;</code>
   */
  com.github.jsdossier.proto.Function.Detail getParameter(int index);
  /**
   * <code>repeated .dossier.Function.Detail parameter = 4;</code>
   */
  int getParameterCount();
  /**
   * <code>repeated .dossier.Function.Detail parameter = 4;</code>
   */
  java.util.List<? extends com.github.jsdossier.proto.Function.DetailOrBuilder> 
      getParameterOrBuilderList();
  /**
   * <code>repeated .dossier.Function.Detail parameter = 4;</code>
   */
  com.github.jsdossier.proto.Function.DetailOrBuilder getParameterOrBuilder(
      int index);

  /**
   * <code>optional .dossier.Function.Detail return = 5;</code>
   */
  boolean hasReturn();
  /**
   * <code>optional .dossier.Function.Detail return = 5;</code>
   */
  com.github.jsdossier.proto.Function.Detail getReturn();
  /**
   * <code>optional .dossier.Function.Detail return = 5;</code>
   */
  com.github.jsdossier.proto.Function.DetailOrBuilder getReturnOrBuilder();

  /**
   * <code>repeated .dossier.Function.Detail thrown = 6;</code>
   */
  java.util.List<com.github.jsdossier.proto.Function.Detail> 
      getThrownList();
  /**
   * <code>repeated .dossier.Function.Detail thrown = 6;</code>
   */
  com.github.jsdossier.proto.Function.Detail getThrown(int index);
  /**
   * <code>repeated .dossier.Function.Detail thrown = 6;</code>
   */
  int getThrownCount();
  /**
   * <code>repeated .dossier.Function.Detail thrown = 6;</code>
   */
  java.util.List<? extends com.github.jsdossier.proto.Function.DetailOrBuilder> 
      getThrownOrBuilderList();
  /**
   * <code>repeated .dossier.Function.Detail thrown = 6;</code>
   */
  com.github.jsdossier.proto.Function.DetailOrBuilder getThrownOrBuilder(
      int index);
}
