// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dossier.proto

package com.github.jsdossier.proto;

public interface HtmlRenderSpecOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dossier.HtmlRenderSpec)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .dossier.Resources resources = 1;</code>
   *
   * <pre>
   * The resources to include.
   * </pre>
   */
  boolean hasResources();
  /**
   * <code>required .dossier.Resources resources = 1;</code>
   *
   * <pre>
   * The resources to include.
   * </pre>
   */
  com.github.jsdossier.proto.Resources getResources();
  /**
   * <code>required .dossier.Resources resources = 1;</code>
   *
   * <pre>
   * The resources to include.
   * </pre>
   */
  com.github.jsdossier.proto.ResourcesOrBuilder getResourcesOrBuilder();

  /**
   * <code>required string title = 2;</code>
   *
   * <pre>
   * The page title.
   * </pre>
   */
  boolean hasTitle();
  /**
   * <code>required string title = 2;</code>
   *
   * <pre>
   * The page title.
   * </pre>
   */
  java.lang.String getTitle();
  /**
   * <code>required string title = 2;</code>
   *
   * <pre>
   * The page title.
   * </pre>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>optional .dossier.Comment content = 3;</code>
   *
   * <pre>
   * The page content, if any.
   * </pre>
   */
  boolean hasContent();
  /**
   * <code>optional .dossier.Comment content = 3;</code>
   *
   * <pre>
   * The page content, if any.
   * </pre>
   */
  com.github.jsdossier.proto.Comment getContent();
  /**
   * <code>optional .dossier.Comment content = 3;</code>
   *
   * <pre>
   * The page content, if any.
   * </pre>
   */
  com.github.jsdossier.proto.CommentOrBuilder getContentOrBuilder();

  /**
   * <code>required .dossier.Index index = 4;</code>
   *
   * <pre>
   * Navigation index.
   * </pre>
   */
  boolean hasIndex();
  /**
   * <code>required .dossier.Index index = 4;</code>
   *
   * <pre>
   * Navigation index.
   * </pre>
   */
  com.github.jsdossier.proto.Index getIndex();
  /**
   * <code>required .dossier.Index index = 4;</code>
   *
   * <pre>
   * Navigation index.
   * </pre>
   */
  com.github.jsdossier.proto.IndexOrBuilder getIndexOrBuilder();
}
