// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dossier.proto

package com.github.jsdossier.proto;

public interface IndexOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dossier.Index)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .dossier.Index.Entry module = 1;</code>
   */
  java.util.List<com.github.jsdossier.proto.Index.Entry> 
      getModuleList();
  /**
   * <code>repeated .dossier.Index.Entry module = 1;</code>
   */
  com.github.jsdossier.proto.Index.Entry getModule(int index);
  /**
   * <code>repeated .dossier.Index.Entry module = 1;</code>
   */
  int getModuleCount();
  /**
   * <code>repeated .dossier.Index.Entry module = 1;</code>
   */
  java.util.List<? extends com.github.jsdossier.proto.Index.EntryOrBuilder> 
      getModuleOrBuilderList();
  /**
   * <code>repeated .dossier.Index.Entry module = 1;</code>
   */
  com.github.jsdossier.proto.Index.EntryOrBuilder getModuleOrBuilder(
      int index);

  /**
   * <code>repeated .dossier.Index.Entry type = 2;</code>
   */
  java.util.List<com.github.jsdossier.proto.Index.Entry> 
      getTypeList();
  /**
   * <code>repeated .dossier.Index.Entry type = 2;</code>
   */
  com.github.jsdossier.proto.Index.Entry getType(int index);
  /**
   * <code>repeated .dossier.Index.Entry type = 2;</code>
   */
  int getTypeCount();
  /**
   * <code>repeated .dossier.Index.Entry type = 2;</code>
   */
  java.util.List<? extends com.github.jsdossier.proto.Index.EntryOrBuilder> 
      getTypeOrBuilderList();
  /**
   * <code>repeated .dossier.Index.Entry type = 2;</code>
   */
  com.github.jsdossier.proto.Index.EntryOrBuilder getTypeOrBuilder(
      int index);

  /**
   * <code>repeated .dossier.Link page = 3;</code>
   */
  java.util.List<com.github.jsdossier.proto.Link> 
      getPageList();
  /**
   * <code>repeated .dossier.Link page = 3;</code>
   */
  com.github.jsdossier.proto.Link getPage(int index);
  /**
   * <code>repeated .dossier.Link page = 3;</code>
   */
  int getPageCount();
  /**
   * <code>repeated .dossier.Link page = 3;</code>
   */
  java.util.List<? extends com.github.jsdossier.proto.LinkOrBuilder> 
      getPageOrBuilderList();
  /**
   * <code>repeated .dossier.Link page = 3;</code>
   */
  com.github.jsdossier.proto.LinkOrBuilder getPageOrBuilder(
      int index);

  /**
   * <code>repeated .dossier.Link source_file = 4;</code>
   */
  java.util.List<com.github.jsdossier.proto.Link> 
      getSourceFileList();
  /**
   * <code>repeated .dossier.Link source_file = 4;</code>
   */
  com.github.jsdossier.proto.Link getSourceFile(int index);
  /**
   * <code>repeated .dossier.Link source_file = 4;</code>
   */
  int getSourceFileCount();
  /**
   * <code>repeated .dossier.Link source_file = 4;</code>
   */
  java.util.List<? extends com.github.jsdossier.proto.LinkOrBuilder> 
      getSourceFileOrBuilderList();
  /**
   * <code>repeated .dossier.Link source_file = 4;</code>
   */
  com.github.jsdossier.proto.LinkOrBuilder getSourceFileOrBuilder(
      int index);
}
