/*
 Copyright 2013-2015 Jason Leyba

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dossier.proto

package com.github.jsdossier.proto;

/**
 * Protobuf type {@code dossier.Resources}
 *
 * <pre>
 * Describes the resources to include in a generated HTML page.
 * </pre>
 */
public final class Resources extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:dossier.Resources)
    ResourcesOrBuilder {
  // Use Resources.newBuilder() to construct.
  private Resources(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private Resources(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final Resources defaultInstance;
  public static Resources getDefaultInstance() {
    return defaultInstance;
  }

  public Resources getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private Resources(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              css_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            css_.add(bs);
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              headScript_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            headScript_.add(bs);
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              tailScript_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000004;
            }
            tailScript_.add(bs);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        css_ = css_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        headScript_ = headScript_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        tailScript_ = tailScript_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.jsdossier.proto.Dossier.internal_static_dossier_Resources_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.jsdossier.proto.Dossier.internal_static_dossier_Resources_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.jsdossier.proto.Resources.class, com.github.jsdossier.proto.Resources.Builder.class);
  }

  public static com.google.protobuf.Parser<Resources> PARSER =
      new com.google.protobuf.AbstractParser<Resources>() {
    public Resources parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Resources(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<Resources> getParserForType() {
    return PARSER;
  }

  public static final int CSS_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList css_;
  /**
   * <code>repeated string css = 1;</code>
   *
   * <pre>
   * Paths to stylesheets to link to in the generated page.
   * </pre>
   */
  public com.google.protobuf.ProtocolStringList
      getCssList() {
    return css_;
  }
  /**
   * <code>repeated string css = 1;</code>
   *
   * <pre>
   * Paths to stylesheets to link to in the generated page.
   * </pre>
   */
  public int getCssCount() {
    return css_.size();
  }
  /**
   * <code>repeated string css = 1;</code>
   *
   * <pre>
   * Paths to stylesheets to link to in the generated page.
   * </pre>
   */
  public java.lang.String getCss(int index) {
    return css_.get(index);
  }
  /**
   * <code>repeated string css = 1;</code>
   *
   * <pre>
   * Paths to stylesheets to link to in the generated page.
   * </pre>
   */
  public com.google.protobuf.ByteString
      getCssBytes(int index) {
    return css_.getByteString(index);
  }

  public static final int HEAD_SCRIPT_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList headScript_;
  /**
   * <code>repeated string head_script = 2;</code>
   *
   * <pre>
   * Paths to JavaScript files to include in the generated page's head.
   * </pre>
   */
  public com.google.protobuf.ProtocolStringList
      getHeadScriptList() {
    return headScript_;
  }
  /**
   * <code>repeated string head_script = 2;</code>
   *
   * <pre>
   * Paths to JavaScript files to include in the generated page's head.
   * </pre>
   */
  public int getHeadScriptCount() {
    return headScript_.size();
  }
  /**
   * <code>repeated string head_script = 2;</code>
   *
   * <pre>
   * Paths to JavaScript files to include in the generated page's head.
   * </pre>
   */
  public java.lang.String getHeadScript(int index) {
    return headScript_.get(index);
  }
  /**
   * <code>repeated string head_script = 2;</code>
   *
   * <pre>
   * Paths to JavaScript files to include in the generated page's head.
   * </pre>
   */
  public com.google.protobuf.ByteString
      getHeadScriptBytes(int index) {
    return headScript_.getByteString(index);
  }

  public static final int TAIL_SCRIPT_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList tailScript_;
  /**
   * <code>repeated string tail_script = 3;</code>
   *
   * <pre>
   * Paths to JavaScript files to include in the generated page after
   * the DOM has been defined.
   * </pre>
   */
  public com.google.protobuf.ProtocolStringList
      getTailScriptList() {
    return tailScript_;
  }
  /**
   * <code>repeated string tail_script = 3;</code>
   *
   * <pre>
   * Paths to JavaScript files to include in the generated page after
   * the DOM has been defined.
   * </pre>
   */
  public int getTailScriptCount() {
    return tailScript_.size();
  }
  /**
   * <code>repeated string tail_script = 3;</code>
   *
   * <pre>
   * Paths to JavaScript files to include in the generated page after
   * the DOM has been defined.
   * </pre>
   */
  public java.lang.String getTailScript(int index) {
    return tailScript_.get(index);
  }
  /**
   * <code>repeated string tail_script = 3;</code>
   *
   * <pre>
   * Paths to JavaScript files to include in the generated page after
   * the DOM has been defined.
   * </pre>
   */
  public com.google.protobuf.ByteString
      getTailScriptBytes(int index) {
    return tailScript_.getByteString(index);
  }

  private void initFields() {
    css_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    headScript_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    tailScript_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    for (int i = 0; i < css_.size(); i++) {
      output.writeBytes(1, css_.getByteString(i));
    }
    for (int i = 0; i < headScript_.size(); i++) {
      output.writeBytes(2, headScript_.getByteString(i));
    }
    for (int i = 0; i < tailScript_.size(); i++) {
      output.writeBytes(3, tailScript_.getByteString(i));
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < css_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(css_.getByteString(i));
      }
      size += dataSize;
      size += 1 * getCssList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < headScript_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(headScript_.getByteString(i));
      }
      size += dataSize;
      size += 1 * getHeadScriptList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < tailScript_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(tailScript_.getByteString(i));
      }
      size += dataSize;
      size += 1 * getTailScriptList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.github.jsdossier.proto.Resources parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.jsdossier.proto.Resources parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.jsdossier.proto.Resources parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.jsdossier.proto.Resources parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.jsdossier.proto.Resources parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.github.jsdossier.proto.Resources parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.github.jsdossier.proto.Resources parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.github.jsdossier.proto.Resources parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.github.jsdossier.proto.Resources parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.github.jsdossier.proto.Resources parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.github.jsdossier.proto.Resources prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dossier.Resources}
   *
   * <pre>
   * Describes the resources to include in a generated HTML page.
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dossier.Resources)
      com.github.jsdossier.proto.ResourcesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.jsdossier.proto.Dossier.internal_static_dossier_Resources_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.jsdossier.proto.Dossier.internal_static_dossier_Resources_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.jsdossier.proto.Resources.class, com.github.jsdossier.proto.Resources.Builder.class);
    }

    // Construct using com.github.jsdossier.proto.Resources.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      css_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      headScript_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      tailScript_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.jsdossier.proto.Dossier.internal_static_dossier_Resources_descriptor;
    }

    public com.github.jsdossier.proto.Resources getDefaultInstanceForType() {
      return com.github.jsdossier.proto.Resources.getDefaultInstance();
    }

    public com.github.jsdossier.proto.Resources build() {
      com.github.jsdossier.proto.Resources result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.github.jsdossier.proto.Resources buildPartial() {
      com.github.jsdossier.proto.Resources result = new com.github.jsdossier.proto.Resources(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        css_ = css_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.css_ = css_;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        headScript_ = headScript_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.headScript_ = headScript_;
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        tailScript_ = tailScript_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.tailScript_ = tailScript_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.jsdossier.proto.Resources) {
        return mergeFrom((com.github.jsdossier.proto.Resources)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.jsdossier.proto.Resources other) {
      if (other == com.github.jsdossier.proto.Resources.getDefaultInstance()) return this;
      if (!other.css_.isEmpty()) {
        if (css_.isEmpty()) {
          css_ = other.css_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureCssIsMutable();
          css_.addAll(other.css_);
        }
        onChanged();
      }
      if (!other.headScript_.isEmpty()) {
        if (headScript_.isEmpty()) {
          headScript_ = other.headScript_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureHeadScriptIsMutable();
          headScript_.addAll(other.headScript_);
        }
        onChanged();
      }
      if (!other.tailScript_.isEmpty()) {
        if (tailScript_.isEmpty()) {
          tailScript_ = other.tailScript_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureTailScriptIsMutable();
          tailScript_.addAll(other.tailScript_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.jsdossier.proto.Resources parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.jsdossier.proto.Resources) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList css_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureCssIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        css_ = new com.google.protobuf.LazyStringArrayList(css_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string css = 1;</code>
     *
     * <pre>
     * Paths to stylesheets to link to in the generated page.
     * </pre>
     */
    public com.google.protobuf.ProtocolStringList
        getCssList() {
      return css_.getUnmodifiableView();
    }
    /**
     * <code>repeated string css = 1;</code>
     *
     * <pre>
     * Paths to stylesheets to link to in the generated page.
     * </pre>
     */
    public int getCssCount() {
      return css_.size();
    }
    /**
     * <code>repeated string css = 1;</code>
     *
     * <pre>
     * Paths to stylesheets to link to in the generated page.
     * </pre>
     */
    public java.lang.String getCss(int index) {
      return css_.get(index);
    }
    /**
     * <code>repeated string css = 1;</code>
     *
     * <pre>
     * Paths to stylesheets to link to in the generated page.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCssBytes(int index) {
      return css_.getByteString(index);
    }
    /**
     * <code>repeated string css = 1;</code>
     *
     * <pre>
     * Paths to stylesheets to link to in the generated page.
     * </pre>
     */
    public Builder setCss(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCssIsMutable();
      css_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string css = 1;</code>
     *
     * <pre>
     * Paths to stylesheets to link to in the generated page.
     * </pre>
     */
    public Builder addCss(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCssIsMutable();
      css_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string css = 1;</code>
     *
     * <pre>
     * Paths to stylesheets to link to in the generated page.
     * </pre>
     */
    public Builder addAllCss(
        java.lang.Iterable<java.lang.String> values) {
      ensureCssIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, css_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string css = 1;</code>
     *
     * <pre>
     * Paths to stylesheets to link to in the generated page.
     * </pre>
     */
    public Builder clearCss() {
      css_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string css = 1;</code>
     *
     * <pre>
     * Paths to stylesheets to link to in the generated page.
     * </pre>
     */
    public Builder addCssBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCssIsMutable();
      css_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList headScript_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureHeadScriptIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        headScript_ = new com.google.protobuf.LazyStringArrayList(headScript_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string head_script = 2;</code>
     *
     * <pre>
     * Paths to JavaScript files to include in the generated page's head.
     * </pre>
     */
    public com.google.protobuf.ProtocolStringList
        getHeadScriptList() {
      return headScript_.getUnmodifiableView();
    }
    /**
     * <code>repeated string head_script = 2;</code>
     *
     * <pre>
     * Paths to JavaScript files to include in the generated page's head.
     * </pre>
     */
    public int getHeadScriptCount() {
      return headScript_.size();
    }
    /**
     * <code>repeated string head_script = 2;</code>
     *
     * <pre>
     * Paths to JavaScript files to include in the generated page's head.
     * </pre>
     */
    public java.lang.String getHeadScript(int index) {
      return headScript_.get(index);
    }
    /**
     * <code>repeated string head_script = 2;</code>
     *
     * <pre>
     * Paths to JavaScript files to include in the generated page's head.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getHeadScriptBytes(int index) {
      return headScript_.getByteString(index);
    }
    /**
     * <code>repeated string head_script = 2;</code>
     *
     * <pre>
     * Paths to JavaScript files to include in the generated page's head.
     * </pre>
     */
    public Builder setHeadScript(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureHeadScriptIsMutable();
      headScript_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string head_script = 2;</code>
     *
     * <pre>
     * Paths to JavaScript files to include in the generated page's head.
     * </pre>
     */
    public Builder addHeadScript(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureHeadScriptIsMutable();
      headScript_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string head_script = 2;</code>
     *
     * <pre>
     * Paths to JavaScript files to include in the generated page's head.
     * </pre>
     */
    public Builder addAllHeadScript(
        java.lang.Iterable<java.lang.String> values) {
      ensureHeadScriptIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, headScript_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string head_script = 2;</code>
     *
     * <pre>
     * Paths to JavaScript files to include in the generated page's head.
     * </pre>
     */
    public Builder clearHeadScript() {
      headScript_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string head_script = 2;</code>
     *
     * <pre>
     * Paths to JavaScript files to include in the generated page's head.
     * </pre>
     */
    public Builder addHeadScriptBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureHeadScriptIsMutable();
      headScript_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList tailScript_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureTailScriptIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        tailScript_ = new com.google.protobuf.LazyStringArrayList(tailScript_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated string tail_script = 3;</code>
     *
     * <pre>
     * Paths to JavaScript files to include in the generated page after
     * the DOM has been defined.
     * </pre>
     */
    public com.google.protobuf.ProtocolStringList
        getTailScriptList() {
      return tailScript_.getUnmodifiableView();
    }
    /**
     * <code>repeated string tail_script = 3;</code>
     *
     * <pre>
     * Paths to JavaScript files to include in the generated page after
     * the DOM has been defined.
     * </pre>
     */
    public int getTailScriptCount() {
      return tailScript_.size();
    }
    /**
     * <code>repeated string tail_script = 3;</code>
     *
     * <pre>
     * Paths to JavaScript files to include in the generated page after
     * the DOM has been defined.
     * </pre>
     */
    public java.lang.String getTailScript(int index) {
      return tailScript_.get(index);
    }
    /**
     * <code>repeated string tail_script = 3;</code>
     *
     * <pre>
     * Paths to JavaScript files to include in the generated page after
     * the DOM has been defined.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTailScriptBytes(int index) {
      return tailScript_.getByteString(index);
    }
    /**
     * <code>repeated string tail_script = 3;</code>
     *
     * <pre>
     * Paths to JavaScript files to include in the generated page after
     * the DOM has been defined.
     * </pre>
     */
    public Builder setTailScript(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTailScriptIsMutable();
      tailScript_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tail_script = 3;</code>
     *
     * <pre>
     * Paths to JavaScript files to include in the generated page after
     * the DOM has been defined.
     * </pre>
     */
    public Builder addTailScript(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTailScriptIsMutable();
      tailScript_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tail_script = 3;</code>
     *
     * <pre>
     * Paths to JavaScript files to include in the generated page after
     * the DOM has been defined.
     * </pre>
     */
    public Builder addAllTailScript(
        java.lang.Iterable<java.lang.String> values) {
      ensureTailScriptIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, tailScript_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tail_script = 3;</code>
     *
     * <pre>
     * Paths to JavaScript files to include in the generated page after
     * the DOM has been defined.
     * </pre>
     */
    public Builder clearTailScript() {
      tailScript_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tail_script = 3;</code>
     *
     * <pre>
     * Paths to JavaScript files to include in the generated page after
     * the DOM has been defined.
     * </pre>
     */
    public Builder addTailScriptBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTailScriptIsMutable();
      tailScript_.add(value);
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:dossier.Resources)
  }

  static {
    defaultInstance = new Resources(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:dossier.Resources)
}

