/*
 Copyright 2013-2015 Jason Leyba

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dossier.proto

package com.github.jsdossier.proto;

public interface SourceFileOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dossier.SourceFile)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string base_name = 1;</code>
   *
   * <pre>
   * The file's base name.
   * </pre>
   */
  boolean hasBaseName();
  /**
   * <code>required string base_name = 1;</code>
   *
   * <pre>
   * The file's base name.
   * </pre>
   */
  java.lang.String getBaseName();
  /**
   * <code>required string base_name = 1;</code>
   *
   * <pre>
   * The file's base name.
   * </pre>
   */
  com.google.protobuf.ByteString
      getBaseNameBytes();

  /**
   * <code>required string path = 2;</code>
   *
   * <pre>
   * The path to the file; may be relative to some unspecified directory.
   * </pre>
   */
  boolean hasPath();
  /**
   * <code>required string path = 2;</code>
   *
   * <pre>
   * The path to the file; may be relative to some unspecified directory.
   * </pre>
   */
  java.lang.String getPath();
  /**
   * <code>required string path = 2;</code>
   *
   * <pre>
   * The path to the file; may be relative to some unspecified directory.
   * </pre>
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>repeated string lines = 3;</code>
   *
   * <pre>
   * The individual lines in the file. Each line should not be HTML escaped.
   * </pre>
   */
  com.google.protobuf.ProtocolStringList
      getLinesList();
  /**
   * <code>repeated string lines = 3;</code>
   *
   * <pre>
   * The individual lines in the file. Each line should not be HTML escaped.
   * </pre>
   */
  int getLinesCount();
  /**
   * <code>repeated string lines = 3;</code>
   *
   * <pre>
   * The individual lines in the file. Each line should not be HTML escaped.
   * </pre>
   */
  java.lang.String getLines(int index);
  /**
   * <code>repeated string lines = 3;</code>
   *
   * <pre>
   * The individual lines in the file. Each line should not be HTML escaped.
   * </pre>
   */
  com.google.protobuf.ByteString
      getLinesBytes(int index);
}
