// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dossier.proto

package com.github.jsdossier.proto;

/**
 * Protobuf type {@code dossier.Tags}
 */
public  final class Tags extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:dossier.Tags)
    TagsOrBuilder {
  // Use Tags.newBuilder() to construct.
  private Tags(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Tags() {
    isConst_ = false;
    isDeprecated_ = false;
    isDict_ = false;
    isFinal_ = false;
    isInterface_ = false;
    isModule_ = false;
    isStruct_ = false;
    isDefault_ = false;
    isRecord_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Tags(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            isConst_ = input.readBool();
            break;
          }
          case 16: {

            isDeprecated_ = input.readBool();
            break;
          }
          case 24: {

            isDict_ = input.readBool();
            break;
          }
          case 32: {

            isFinal_ = input.readBool();
            break;
          }
          case 40: {

            isInterface_ = input.readBool();
            break;
          }
          case 48: {

            isModule_ = input.readBool();
            break;
          }
          case 56: {

            isStruct_ = input.readBool();
            break;
          }
          case 64: {

            isDefault_ = input.readBool();
            break;
          }
          case 72: {

            isRecord_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.jsdossier.proto.Dossier.internal_static_dossier_Tags_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.jsdossier.proto.Dossier.internal_static_dossier_Tags_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.jsdossier.proto.Tags.class, com.github.jsdossier.proto.Tags.Builder.class);
  }

  public static final int IS_CONST_FIELD_NUMBER = 1;
  private boolean isConst_;
  /**
   * <code>optional bool is_const = 1;</code>
   */
  public boolean getIsConst() {
    return isConst_;
  }

  public static final int IS_DEPRECATED_FIELD_NUMBER = 2;
  private boolean isDeprecated_;
  /**
   * <code>optional bool is_deprecated = 2;</code>
   */
  public boolean getIsDeprecated() {
    return isDeprecated_;
  }

  public static final int IS_DICT_FIELD_NUMBER = 3;
  private boolean isDict_;
  /**
   * <code>optional bool is_dict = 3;</code>
   */
  public boolean getIsDict() {
    return isDict_;
  }

  public static final int IS_FINAL_FIELD_NUMBER = 4;
  private boolean isFinal_;
  /**
   * <code>optional bool is_final = 4;</code>
   */
  public boolean getIsFinal() {
    return isFinal_;
  }

  public static final int IS_INTERFACE_FIELD_NUMBER = 5;
  private boolean isInterface_;
  /**
   * <code>optional bool is_interface = 5;</code>
   */
  public boolean getIsInterface() {
    return isInterface_;
  }

  public static final int IS_MODULE_FIELD_NUMBER = 6;
  private boolean isModule_;
  /**
   * <code>optional bool is_module = 6;</code>
   */
  public boolean getIsModule() {
    return isModule_;
  }

  public static final int IS_STRUCT_FIELD_NUMBER = 7;
  private boolean isStruct_;
  /**
   * <code>optional bool is_struct = 7;</code>
   */
  public boolean getIsStruct() {
    return isStruct_;
  }

  public static final int IS_DEFAULT_FIELD_NUMBER = 8;
  private boolean isDefault_;
  /**
   * <code>optional bool is_default = 8;</code>
   */
  public boolean getIsDefault() {
    return isDefault_;
  }

  public static final int IS_RECORD_FIELD_NUMBER = 9;
  private boolean isRecord_;
  /**
   * <code>optional bool is_record = 9;</code>
   */
  public boolean getIsRecord() {
    return isRecord_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (isConst_ != false) {
      output.writeBool(1, isConst_);
    }
    if (isDeprecated_ != false) {
      output.writeBool(2, isDeprecated_);
    }
    if (isDict_ != false) {
      output.writeBool(3, isDict_);
    }
    if (isFinal_ != false) {
      output.writeBool(4, isFinal_);
    }
    if (isInterface_ != false) {
      output.writeBool(5, isInterface_);
    }
    if (isModule_ != false) {
      output.writeBool(6, isModule_);
    }
    if (isStruct_ != false) {
      output.writeBool(7, isStruct_);
    }
    if (isDefault_ != false) {
      output.writeBool(8, isDefault_);
    }
    if (isRecord_ != false) {
      output.writeBool(9, isRecord_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (isConst_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, isConst_);
    }
    if (isDeprecated_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, isDeprecated_);
    }
    if (isDict_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, isDict_);
    }
    if (isFinal_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, isFinal_);
    }
    if (isInterface_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, isInterface_);
    }
    if (isModule_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, isModule_);
    }
    if (isStruct_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, isStruct_);
    }
    if (isDefault_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, isDefault_);
    }
    if (isRecord_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(9, isRecord_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static com.github.jsdossier.proto.Tags parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.jsdossier.proto.Tags parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.jsdossier.proto.Tags parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.jsdossier.proto.Tags parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.jsdossier.proto.Tags parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.github.jsdossier.proto.Tags parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.github.jsdossier.proto.Tags parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.github.jsdossier.proto.Tags parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.github.jsdossier.proto.Tags parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.github.jsdossier.proto.Tags parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.jsdossier.proto.Tags prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dossier.Tags}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dossier.Tags)
      com.github.jsdossier.proto.TagsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.jsdossier.proto.Dossier.internal_static_dossier_Tags_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.jsdossier.proto.Dossier.internal_static_dossier_Tags_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.jsdossier.proto.Tags.class, com.github.jsdossier.proto.Tags.Builder.class);
    }

    // Construct using com.github.jsdossier.proto.Tags.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      isConst_ = false;

      isDeprecated_ = false;

      isDict_ = false;

      isFinal_ = false;

      isInterface_ = false;

      isModule_ = false;

      isStruct_ = false;

      isDefault_ = false;

      isRecord_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.jsdossier.proto.Dossier.internal_static_dossier_Tags_descriptor;
    }

    public com.github.jsdossier.proto.Tags getDefaultInstanceForType() {
      return com.github.jsdossier.proto.Tags.getDefaultInstance();
    }

    public com.github.jsdossier.proto.Tags build() {
      com.github.jsdossier.proto.Tags result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.github.jsdossier.proto.Tags buildPartial() {
      com.github.jsdossier.proto.Tags result = new com.github.jsdossier.proto.Tags(this);
      result.isConst_ = isConst_;
      result.isDeprecated_ = isDeprecated_;
      result.isDict_ = isDict_;
      result.isFinal_ = isFinal_;
      result.isInterface_ = isInterface_;
      result.isModule_ = isModule_;
      result.isStruct_ = isStruct_;
      result.isDefault_ = isDefault_;
      result.isRecord_ = isRecord_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.jsdossier.proto.Tags) {
        return mergeFrom((com.github.jsdossier.proto.Tags)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.jsdossier.proto.Tags other) {
      if (other == com.github.jsdossier.proto.Tags.getDefaultInstance()) return this;
      if (other.getIsConst() != false) {
        setIsConst(other.getIsConst());
      }
      if (other.getIsDeprecated() != false) {
        setIsDeprecated(other.getIsDeprecated());
      }
      if (other.getIsDict() != false) {
        setIsDict(other.getIsDict());
      }
      if (other.getIsFinal() != false) {
        setIsFinal(other.getIsFinal());
      }
      if (other.getIsInterface() != false) {
        setIsInterface(other.getIsInterface());
      }
      if (other.getIsModule() != false) {
        setIsModule(other.getIsModule());
      }
      if (other.getIsStruct() != false) {
        setIsStruct(other.getIsStruct());
      }
      if (other.getIsDefault() != false) {
        setIsDefault(other.getIsDefault());
      }
      if (other.getIsRecord() != false) {
        setIsRecord(other.getIsRecord());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.jsdossier.proto.Tags parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.jsdossier.proto.Tags) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean isConst_ ;
    /**
     * <code>optional bool is_const = 1;</code>
     */
    public boolean getIsConst() {
      return isConst_;
    }
    /**
     * <code>optional bool is_const = 1;</code>
     */
    public Builder setIsConst(boolean value) {
      
      isConst_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool is_const = 1;</code>
     */
    public Builder clearIsConst() {
      
      isConst_ = false;
      onChanged();
      return this;
    }

    private boolean isDeprecated_ ;
    /**
     * <code>optional bool is_deprecated = 2;</code>
     */
    public boolean getIsDeprecated() {
      return isDeprecated_;
    }
    /**
     * <code>optional bool is_deprecated = 2;</code>
     */
    public Builder setIsDeprecated(boolean value) {
      
      isDeprecated_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool is_deprecated = 2;</code>
     */
    public Builder clearIsDeprecated() {
      
      isDeprecated_ = false;
      onChanged();
      return this;
    }

    private boolean isDict_ ;
    /**
     * <code>optional bool is_dict = 3;</code>
     */
    public boolean getIsDict() {
      return isDict_;
    }
    /**
     * <code>optional bool is_dict = 3;</code>
     */
    public Builder setIsDict(boolean value) {
      
      isDict_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool is_dict = 3;</code>
     */
    public Builder clearIsDict() {
      
      isDict_ = false;
      onChanged();
      return this;
    }

    private boolean isFinal_ ;
    /**
     * <code>optional bool is_final = 4;</code>
     */
    public boolean getIsFinal() {
      return isFinal_;
    }
    /**
     * <code>optional bool is_final = 4;</code>
     */
    public Builder setIsFinal(boolean value) {
      
      isFinal_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool is_final = 4;</code>
     */
    public Builder clearIsFinal() {
      
      isFinal_ = false;
      onChanged();
      return this;
    }

    private boolean isInterface_ ;
    /**
     * <code>optional bool is_interface = 5;</code>
     */
    public boolean getIsInterface() {
      return isInterface_;
    }
    /**
     * <code>optional bool is_interface = 5;</code>
     */
    public Builder setIsInterface(boolean value) {
      
      isInterface_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool is_interface = 5;</code>
     */
    public Builder clearIsInterface() {
      
      isInterface_ = false;
      onChanged();
      return this;
    }

    private boolean isModule_ ;
    /**
     * <code>optional bool is_module = 6;</code>
     */
    public boolean getIsModule() {
      return isModule_;
    }
    /**
     * <code>optional bool is_module = 6;</code>
     */
    public Builder setIsModule(boolean value) {
      
      isModule_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool is_module = 6;</code>
     */
    public Builder clearIsModule() {
      
      isModule_ = false;
      onChanged();
      return this;
    }

    private boolean isStruct_ ;
    /**
     * <code>optional bool is_struct = 7;</code>
     */
    public boolean getIsStruct() {
      return isStruct_;
    }
    /**
     * <code>optional bool is_struct = 7;</code>
     */
    public Builder setIsStruct(boolean value) {
      
      isStruct_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool is_struct = 7;</code>
     */
    public Builder clearIsStruct() {
      
      isStruct_ = false;
      onChanged();
      return this;
    }

    private boolean isDefault_ ;
    /**
     * <code>optional bool is_default = 8;</code>
     */
    public boolean getIsDefault() {
      return isDefault_;
    }
    /**
     * <code>optional bool is_default = 8;</code>
     */
    public Builder setIsDefault(boolean value) {
      
      isDefault_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool is_default = 8;</code>
     */
    public Builder clearIsDefault() {
      
      isDefault_ = false;
      onChanged();
      return this;
    }

    private boolean isRecord_ ;
    /**
     * <code>optional bool is_record = 9;</code>
     */
    public boolean getIsRecord() {
      return isRecord_;
    }
    /**
     * <code>optional bool is_record = 9;</code>
     */
    public Builder setIsRecord(boolean value) {
      
      isRecord_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool is_record = 9;</code>
     */
    public Builder clearIsRecord() {
      
      isRecord_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:dossier.Tags)
  }

  // @@protoc_insertion_point(class_scope:dossier.Tags)
  private static final com.github.jsdossier.proto.Tags DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.jsdossier.proto.Tags();
  }

  public static com.github.jsdossier.proto.Tags getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Tags>
      PARSER = new com.google.protobuf.AbstractParser<Tags>() {
    public Tags parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new Tags(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<Tags> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Tags> getParserForType() {
    return PARSER;
  }

  public com.github.jsdossier.proto.Tags getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

