/*
 Copyright 2013-2015 Jason Leyba

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dossier.proto

package com.github.jsdossier.proto;

/**
 * Protobuf enum {@code dossier.Visibility}
 *
 * <pre>
 * Describes a type/property's visibility.
 * </pre>
 */
public enum Visibility
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>PUBLIC = 0;</code>
   *
   * <pre>
   * The type is globally accessible.
   * </pre>
   */
  PUBLIC(0, 0),
  /**
   * <code>PROTECTED = 1;</code>
   *
   * <pre>
   * The type may only be used by subclasses or other code in the same file.
   * </pre>
   */
  PROTECTED(1, 1),
  /**
   * <code>PRIVATE = 2;</code>
   *
   * <pre>
   * The type may only be used by other code in the same file.
   * </pre>
   */
  PRIVATE(2, 2),
  /**
   * <code>PACKAGE = 3;</code>
   *
   * <pre>
   * The type may only be used by subclasses, or other code in the same
   * package.
   * </pre>
   */
  PACKAGE(3, 3),
  ;

  /**
   * <code>PUBLIC = 0;</code>
   *
   * <pre>
   * The type is globally accessible.
   * </pre>
   */
  public static final int PUBLIC_VALUE = 0;
  /**
   * <code>PROTECTED = 1;</code>
   *
   * <pre>
   * The type may only be used by subclasses or other code in the same file.
   * </pre>
   */
  public static final int PROTECTED_VALUE = 1;
  /**
   * <code>PRIVATE = 2;</code>
   *
   * <pre>
   * The type may only be used by other code in the same file.
   * </pre>
   */
  public static final int PRIVATE_VALUE = 2;
  /**
   * <code>PACKAGE = 3;</code>
   *
   * <pre>
   * The type may only be used by subclasses, or other code in the same
   * package.
   * </pre>
   */
  public static final int PACKAGE_VALUE = 3;


  public final int getNumber() { return value; }

  public static Visibility valueOf(int value) {
    switch (value) {
      case 0: return PUBLIC;
      case 1: return PROTECTED;
      case 2: return PRIVATE;
      case 3: return PACKAGE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Visibility>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static com.google.protobuf.Internal.EnumLiteMap<Visibility>
      internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Visibility>() {
          public Visibility findValueByNumber(int number) {
            return Visibility.valueOf(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(index);
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.github.jsdossier.proto.Dossier.getDescriptor()
        .getEnumTypes().get(0);
  }

  private static final Visibility[] VALUES = values();

  public static Visibility valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int index;
  private final int value;

  private Visibility(int index, int value) {
    this.index = index;
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:dossier.Visibility)
}

