// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dossier.proto

package com.github.jsdossier.proto;

public interface VisibilityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dossier.Visibility)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool public = 1;</code>
   *
   * <pre>
   * The type is globally accessible.
   * </pre>
   */
  boolean getPublic();

  /**
   * <code>optional bool protected = 2;</code>
   *
   * <pre>
   * The type may only be used by subclasses or other code in the same file.
   * </pre>
   */
  boolean getProtected();

  /**
   * <code>optional bool private = 3;</code>
   *
   * <pre>
   * The type may only be used by other code in the same file.
   * </pre>
   */
  boolean getPrivate();

  /**
   * <code>optional bool package = 4;</code>
   *
   * <pre>
   * The type may only be used by subclasses, or other code in the same
   * package.
   * </pre>
   */
  boolean getPackage();

  public com.github.jsdossier.proto.Visibility.TypeCase getTypeCase();
}
