java_library(
    name = "markdown",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/java/com/github/jsdossier:__subpackages__",
        "//test/java/com/github/jsdossier:__subpackages__",
    ],
    deps = [
        "@maven//:com_atlassian_commonmark_commonmark",
        "@maven//:com_google_guava_guava",
    ],
)
