java_library(
    name = "markdown",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/java/com/github/jsdossier:__subpackages__",
        "//test/java/com/github/jsdossier:__subpackages__",
    ],
    deps = [
        "//third_party/java/commonmark",
        "//third_party/java/guava",
    ],
)
