java_library(
    name = "markdown",
    srcs = glob(["*.java"]),
    deps = [
        "//lib/maven:commonmark",
        "//lib/maven:guava",
    ],
    visibility = [
        "//src/java/com/github/jsdossier:__subpackages__",
        "//test/java/com/github/jsdossier:__subpackages__",
    ],
)
