// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dossier.proto

package com.github.jsdossier.proto;

public interface IndexOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dossier.Index)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string home = 1;</code>
   *
   * <pre>
   * Defines the href from the current page to the main index.
   * </pre>
   */
  boolean hasHome();
  /**
   * <code>required string home = 1;</code>
   *
   * <pre>
   * Defines the href from the current page to the main index.
   * </pre>
   */
  java.lang.String getHome();
  /**
   * <code>required string home = 1;</code>
   *
   * <pre>
   * Defines the href from the current page to the main index.
   * </pre>
   */
  com.google.protobuf.ByteString
      getHomeBytes();

  /**
   * <code>repeated .dossier.TypeLink type = 2;</code>
   *
   * <pre>
   * Links to the global JavaScript types.
   * </pre>
   */
  java.util.List<com.github.jsdossier.proto.TypeLink> 
      getTypeList();
  /**
   * <code>repeated .dossier.TypeLink type = 2;</code>
   *
   * <pre>
   * Links to the global JavaScript types.
   * </pre>
   */
  com.github.jsdossier.proto.TypeLink getType(int index);
  /**
   * <code>repeated .dossier.TypeLink type = 2;</code>
   *
   * <pre>
   * Links to the global JavaScript types.
   * </pre>
   */
  int getTypeCount();
  /**
   * <code>repeated .dossier.TypeLink type = 2;</code>
   *
   * <pre>
   * Links to the global JavaScript types.
   * </pre>
   */
  java.util.List<? extends com.github.jsdossier.proto.TypeLinkOrBuilder> 
      getTypeOrBuilderList();
  /**
   * <code>repeated .dossier.TypeLink type = 2;</code>
   *
   * <pre>
   * Links to the global JavaScript types.
   * </pre>
   */
  com.github.jsdossier.proto.TypeLinkOrBuilder getTypeOrBuilder(
      int index);

  /**
   * <code>repeated .dossier.Index.Module module = 3;</code>
   *
   * <pre>
   * Links to JavaScript modules.
   * </pre>
   */
  java.util.List<com.github.jsdossier.proto.Index.Module> 
      getModuleList();
  /**
   * <code>repeated .dossier.Index.Module module = 3;</code>
   *
   * <pre>
   * Links to JavaScript modules.
   * </pre>
   */
  com.github.jsdossier.proto.Index.Module getModule(int index);
  /**
   * <code>repeated .dossier.Index.Module module = 3;</code>
   *
   * <pre>
   * Links to JavaScript modules.
   * </pre>
   */
  int getModuleCount();
  /**
   * <code>repeated .dossier.Index.Module module = 3;</code>
   *
   * <pre>
   * Links to JavaScript modules.
   * </pre>
   */
  java.util.List<? extends com.github.jsdossier.proto.Index.ModuleOrBuilder> 
      getModuleOrBuilderList();
  /**
   * <code>repeated .dossier.Index.Module module = 3;</code>
   *
   * <pre>
   * Links to JavaScript modules.
   * </pre>
   */
  com.github.jsdossier.proto.Index.ModuleOrBuilder getModuleOrBuilder(
      int index);
}
