(function(){var l,n=this;
function q(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}function r(a){return"array"==q(a)}function aa(a){var b=q(a);return"array"==b||"object"==b&&"number"==typeof a.length}function t(a){return"string"==typeof a}function ba(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}var ca="closure_uid_"+(1E9*Math.random()>>>0),ea=0;function fa(a,b,c){return a.call.apply(a.bind,arguments)}
function ga(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function u(a,b,c){u=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?fa:ga;return u.apply(null,arguments)}var ha=Date.now||function(){return+new Date};
function x(a,b){function c(){}c.prototype=b.prototype;a.na=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Ga=function(a,c,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[c].apply(a,g)}};var ia;function y(){0!=ja&&(this[ca]||(this[ca]=++ea));this.la=this.la;this.ra=this.ra}var ja=0;y.prototype.la=!1;var ka;function z(a,b){this.type=a;this.a=this.target=b;this.f=!1;this.ka=!0}z.prototype.stopPropagation=function(){this.f=!0};z.prototype.preventDefault=function(){this.ka=!1};var la="closure_listenable_"+(1E6*Math.random()|0),ma=0;function na(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.M=!!d;this.N=e;this.aa=++ma;this.H=this.L=!1}function oa(a){a.H=!0;a.listener=null;a.a=null;a.src=null;a.N=null};function A(a,b){this.width=a;this.height=b}A.prototype.clone=function(){return new A(this.width,this.height)};A.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};A.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};A.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function pa(a,b){for(var c in a)b.call(void 0,a[c],c,a)}var qa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function ra(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<qa.length;f++)c=qa[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function sa(a){sa[" "](a);return a}sa[" "]=function(){};function ta(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}var ua=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
function va(a){if(!wa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(xa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(ya,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(za,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Aa,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Ba,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Ca,"&#0;"));return a}var xa=/&/g,ya=/</g,za=/>/g,Aa=/"/g,Ba=/'/g,Ca=/\x00/g,wa=/[\x00&<>"']/;
function Da(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")}function Ea(a,b){return a<b?-1:a>b?1:0};var B=Array.prototype,Fa=B.indexOf?function(a,b,c){return B.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(t(a))return t(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},C=B.forEach?function(a,b,c){B.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Ga=B.filter?function(a,b,c){return B.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=t(a)?
a.split(""):a,h=0;h<d;h++)if(h in g){var k=g[h];b.call(c,k,h,a)&&(e[f++]=k)}return e};function Ha(a,b){var c;a:{c=a.length;for(var d=t(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){c=e;break a}c=-1}return 0>c?null:t(a)?a.charAt(c):a[c]}function Ia(a,b){var c=Fa(a,b),d;(d=0<=c)&&B.splice.call(a,c,1);return d}function Ja(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}
function Ka(a,b,c){return 2>=arguments.length?B.slice.call(a,b):B.slice.call(a,b,c)};var La={};
function Ma(a,b,c,d){var e=document.createElement("li"),f=document.createElement("a");f.textContent=a.getKey();a.b&&(f.href=b+a.b.href,a.b.interface&&f.classList.add("interface"));var g=a.G();if(g){var h=document.createElement("input");h.type="checkbox";h.id=d+a.getKey();e.appendChild(h);d=document.createElement("label");d.setAttribute("for",h.id);d.appendChild(f);a.b&&a.b.href===c&&d.classList.add("current");e.appendChild(d);var k=document.createElement("ul");k.classList.add("nav-tree");e.appendChild(k);
g.forEach(function(a){k.appendChild(Ma(a,b,c,h.id+"."))})}else a.b&&a.b.href===c&&f.classList.add("current"),e.appendChild(f);return e}function Na(a){if(a=a.G())a.sort(function(a,c){return a.getKey()<c.getKey()?-1:a.getKey()>c.getKey()?1:0}),a.forEach(Na)}
function Oa(a){var b=a.G();b&&(b.forEach(Oa),b.filter(function(a){return null===a.b&&1==(a.a?a.a.length:0)}).forEach(function(b){a.removeChild(b);var d=Pa(b);d&&d.forEach(function(d){var f=b.getKey()+"."+d.getKey();d.f=f;Qa(a,d)})}),b.filter(function(a){return a.b&&!a.b.namespace&&!a.b.types&&(a.a?a.a.length:0)}).forEach(function(b){var d=Pa(b);d&&d.forEach(function(d){var f=b.getKey()+"."+d.getKey();d.f=f;Qa(a,d)})}))}function D(a,b){this.f=a;this.b=b;this.a=this.c=null}D.prototype.getKey=function(){return this.f};
D.prototype.R=function(a){this.b=a};function Qa(a,b){a.a||(a.a=[]);b.c=a;a.a.push(b)}D.prototype.G=function(){return this.a};D.prototype.removeChild=function(a){a.c=null;Ia(this.a,a)};function Pa(a){var b=a.a;a.a&&(a.a.forEach(function(a){a.c=null}),a.a=null);return b}function Ra(a,b){return a.a?Ha(a.a,function(a){return a.f===b}):null}
La.$=function(a,b){var c=new D("",null);a.forEach(function(a){if(b){var e;a.types?(e=La.$(a.types,!1),e.f=a.name,e.R(a)):e=new D(a.name,a);Qa(c,e)}else{var f=c;a.name.split(/\./).forEach(function(a){var b=Ra(f,a);b||(b=new D(a,null),Qa(f,b));f=b});f.R(a)}});Oa(c);Na(c);return c};La.Z=function(a,b,c){var d=Sa;d&&!ta(d,"/")&&(d+="/");a=La.$(a,c);var e=document.createElement("ul");a.G()&&a.G().forEach(function(a){e.appendChild(Ma(a,d,b,c?".nav-module:":".nav:"))});return e};function Ta(a){if(a.classList)return a.classList;a=a.className;return t(a)&&a.match(/\S+/g)||[]}function Ua(a,b){var c;a.classList?c=a.classList.contains(b):(c=Ta(a),c=0<=Fa(c,b));return c}function Va(a,b){a.classList?a.classList.add(b):Ua(a,b)||(a.className+=0<a.className.length?" "+b:b)}function Wa(a,b){if(a.classList)C(b,function(b){Va(a,b)});else{var c={};C(Ta(a),function(a){c[a]=!0});C(b,function(a){c[a]=!0});a.className="";for(var d in c)a.className+=0<a.className.length?" "+d:d}}
function Xa(a,b){a.classList?a.classList.remove(b):Ua(a,b)&&(a.className=Ga(Ta(a),function(a){return a!=b}).join(" "))}function Ya(a){var b=["ac-active","active"];a.classList?C(b,function(b){Xa(a,b)}):a.className=Ga(Ta(a),function(a){return!(0<=Fa(b,a))}).join(" ")};function Za(a){this.src=a;this.a={};this.b=0}Za.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var g=$a(a,b,d,e);-1<g?(b=a[g],c||(b.L=!1)):(b=new na(b,this.src,f,!!d,e),b.L=c,a.push(b));return b};Za.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=$a(e,b,c,d);return-1<b?(oa(e[b]),B.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};
function ab(a,b){var c=b.type;if(!(c in a.a))return!1;var d=Ia(a.a[c],b);d&&(oa(b),0==a.a[c].length&&(delete a.a[c],a.b--));return d}function bb(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=$a(a,c,d,e));return-1<b?a[b]:null}function $a(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.H&&f.listener==b&&f.M==!!c&&f.N==d)return e}return-1};var cb;a:{var db=n.navigator;if(db){var eb=db.userAgent;if(eb){cb=eb;break a}}cb=""}function E(a){return-1!=cb.indexOf(a)};function fb(){return E("Opera")||E("OPR")}function gb(){return E("Edge")||E("Trident")||E("MSIE")}function hb(){return(E("Chrome")||E("CriOS"))&&!fb()&&!gb()};function F(){return E("Edge")};function G(a,b){this.x=void 0!==a?a:0;this.y=void 0!==b?b:0}G.prototype.clone=function(){return new G(this.x,this.y)};function ib(a,b){return new G(a.x-b.x,a.y-b.y)}G.prototype.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};G.prototype.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};G.prototype.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};function H(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}l=H.prototype;l.clone=function(){return new H(this.top,this.right,this.bottom,this.left)};l.contains=function(a){return this&&a?a instanceof H?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom:!1};
l.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};l.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};l.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};function jb(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}l=jb.prototype;l.clone=function(){return new jb(this.left,this.top,this.width,this.height)};l.contains=function(a){return a instanceof jb?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};
l.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};l.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};l.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function kb(a){this.a=a||[]}function lb(a,b,c){for(var d=[],e=0;e<c.length;e++){var f=c[e],g=a.toLowerCase(),h=String(f).toLowerCase(),k=0;if(-1!=h.indexOf(g))k=parseInt((h.indexOf(g)/4).toString(),10);else for(var m=g.split(""),p=-1,v=10,w=0,da;da=m[w];w++)da=h.indexOf(da),da>p?(p=da-p-1,p>v-5&&(p=v-5),k+=p,p=da):(k+=v,v+=5);k<6*g.length&&d.push({Fa:f,ma:k,index:e})}d.sort(function(a,b){var c=a.ma-b.ma;return 0!=c?c:a.index-b.index});a=[];for(w=0;w<b&&w<d.length;w++)a.push(d[w].Fa);return a};function I(){}I.a=function(){return I.b?I.b:I.b=new I};I.prototype.a=0;var mb=fb(),J=gb(),K=E("Gecko")&&!(-1!=cb.toLowerCase().indexOf("webkit")&&!F())&&!(E("Trident")||E("MSIE"))&&!F(),L=-1!=cb.toLowerCase().indexOf("webkit")&&!F(),M=E("Macintosh");function nb(){var a=cb;if(K)return/rv\:([^\);]+)(\)|;)/.exec(a);if(J&&F())return/Edge\/([\d\.]+)/.exec(a);if(J)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(L)return/WebKit\/(\S+)/.exec(a)}function ob(){var a=n.document;return a?a.documentMode:void 0}
var pb=function(){if(mb&&n.opera){var a=n.opera.version;return"function"==q(a)?a():a}var a="",b=nb();b&&(a=b?b[1]:"");return J&&!F()&&(b=ob(),b>parseFloat(a))?String(b):a}(),qb={};
function N(a){var b;if(!(b=qb[a])){b=0;for(var c=ua(String(pb)).split("."),d=ua(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"",k=/(\d*)(\D*)/g,m=/(\d*)(\D*)/g;do{var p=k.exec(g)||["","",""],v=m.exec(h)||["","",""];if(0==p[0].length&&0==v[0].length)break;b=Ea(0==p[1].length?0:parseInt(p[1],10),0==v[1].length?0:parseInt(v[1],10))||Ea(0==p[2].length,0==v[2].length)||Ea(p[2],v[2])}while(0==b)}b=qb[a]=0<=b}return b}
function O(a){return J&&(F()||rb>=a)}var sb=n.document,tb=ob(),rb=!sb||!J||!tb&&F()?void 0:tb||("CSS1Compat"==sb.compatMode?parseInt(pb,10):5);var ub=!J||O(9),vb=!K&&!J||J&&O(9)||K&&N("1.9.1");J&&N("9");function P(a){return a?new wb(Q(a)):ka||(ka=new wb)}function xb(a){var b=document;return t(a)?b.getElementById(a):a}function yb(a,b){pa(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in zb?a.setAttribute(zb[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})}
var zb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function Ab(a){var b=Bb(a);a=Cb(a);return J&&N("10")&&a.pageYOffset!=b.scrollTop?new G(b.scrollLeft,b.scrollTop):new G(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)}
function Bb(a){return L||"CSS1Compat"!=a.compatMode?a.body||a.documentElement:a.documentElement}function Cb(a){return a.parentWindow||a.defaultView}function Db(a,b,c){function d(c){c&&b.appendChild(t(c)?a.createTextNode(c):c)}for(var e=2;e<c.length;e++){var f=c[e];if(!aa(f)||ba(f)&&0<f.nodeType)d(f);else{var g;a:{if(f&&"number"==typeof f.length){if(ba(f)){g="function"==typeof f.item||"string"==typeof f.item;break a}if("function"==q(f)){g="function"==typeof f.item;break a}}g=!1}C(g?Ja(f):f,d)}}}
function Eb(a){for(var b;b=a.firstChild;)a.removeChild(b)}function Q(a){return 9==a.nodeType?a:a.ownerDocument||a.document}function Fb(a,b){a=a.parentNode;for(var c=0;a;){if(b(a))return a;a=a.parentNode;c++}return null}function wb(a){this.a=a||n.document||document}
wb.prototype.b=function(a,b,c){var d=this.a,e=arguments,f=e[0],g=e[1];if(!ub&&g&&(g.name||g.type)){f=["<",f];g.name&&f.push(' name="',va(g.name),'"');if(g.type){f.push(' type="',va(g.type),'"');var h={};ra(h,g);delete h.type;g=h}f.push(">");f=f.join("")}f=d.createElement(f);g&&(t(g)?f.className=g:r(g)?f.className=g.join(" "):yb(f,g));2<e.length&&Db(d,f,e);return f};function Gb(a){return"CSS1Compat"==a.a.compatMode}wb.prototype.f=Eb;
wb.prototype.G=function(a){return vb&&void 0!=a.children?a.children:Ga(a.childNodes,function(a){return 1==a.nodeType})};wb.prototype.contains=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};function Hb(a,b){b?a.setAttribute("role",b):a.removeAttribute("role")}function Ib(a,b,c){r(c)&&(c=c.join(" "));var d="aria-"+b;""===c||void 0==c?(ia||(ia={atomic:!1,autocomplete:"none",dropeffect:"none",haspopup:!1,live:"off",multiline:!1,multiselectable:!1,orientation:"vertical",readonly:!1,relevant:"additions text",required:!1,sort:"none",busy:!1,disabled:!1,hidden:!1,invalid:"false"}),c=ia,b in c?a.setAttribute(d,c[b]):a.removeAttribute(d)):a.setAttribute(d,c)}
function Jb(a,b){var c="";b&&(c=b.id);Ib(a,"activedescendant",c)};function Kb(a){var b=0,c=0;if(Lb(a))b=a.selectionStart,c=-1;else if(J){var d=Mb(a),e=d[0],d=d[1];if(e.inRange(d)){e.setEndPoint("EndToStart",d);if("textarea"==a.type){d.duplicate();b=a=e.text;for(c=!1;!c;)0==e.compareEndPoints("StartToEnd",e)?c=!0:(e.moveEnd("character",-1),e.text==a?b+="\r\n":c=!0);e=[b.length,-1];return e}b=e.text.length;c=-1}}return[b,c]}
function Mb(a){var b=a.ownerDocument||a.document,c=b.selection.createRange();"textarea"==a.type?(b=b.body.createTextRange(),b.moveToElementText(a)):b=a.createTextRange();return[b,c]}function Nb(a,b){"textarea"==a.type&&(b=a.value.substring(0,b).replace(/(\r\n|\r|\n)/g,"\n").length);return b}function Lb(a){try{return"number"==typeof a.selectionStart}catch(b){return!1}};var Ob=!J||O(9),Pb=J&&!N("9");!L||N("528");K&&N("1.9b")||J&&N("8")||mb&&N("9.5")||L&&N("528");K&&!N("8")||J&&N("9");function R(a,b){z.call(this,a?a.type:"");this.a=this.target=null;this.i=this.keyCode=this.screenY=this.screenX=this.clientY=this.clientX=0;this.metaKey=this.l=this.b=this.ctrlKey=!1;this.c=null;if(a){var c=this.type=a.type,d=null;if("touchstart"==c||"touchmove"==c)d=a.targetTouches[0];else if("touchend"==c||"touchcancel"==c)d=a.changedTouches[0];this.target=null===d?a.target||a.srcElement:d.target;this.a=b;var e=a.relatedTarget;if(e&&K)try{sa(e.nodeName)}catch(f){}null===d?(this.clientX=void 0!==
a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0):(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0);this.keyCode=a.keyCode||0;this.i=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.b=a.altKey;this.l=a.shiftKey;this.metaKey=a.metaKey;this.c=a;a.defaultPrevented&&this.preventDefault()}}x(R,z);
R.prototype.stopPropagation=function(){R.na.stopPropagation.call(this);this.c.stopPropagation?this.c.stopPropagation():this.c.cancelBubble=!0};R.prototype.preventDefault=function(){R.na.preventDefault.call(this);var a=this.c;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Pb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var Qb="closure_lm_"+(1E6*Math.random()|0),Rb={},Sb=0;function S(a,b,c,d,e){if(r(b)){for(var f=0;f<b.length;f++)S(a,b[f],c,d,e);return null}c=Tb(c);if(a&&a[la])a=a.f(b,c,d,e);else{if(!b)throw Error("Invalid event type");var f=!!d,g=Ub(a);g||(a[Qb]=g=new Za(a));c=g.add(b,c,!1,d,e);c.a||(d=Vb(),c.a=d,d.src=a,d.listener=c,a.addEventListener?a.addEventListener(b.toString(),d,f):a.attachEvent(Wb(b.toString()),d),Sb++);a=c}return a}
function Vb(){var a=Xb,b=Ob?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function Yb(a,b,c,d,e){if(r(b))for(var f=0;f<b.length;f++)Yb(a,b[f],c,d,e);else c=Tb(c),a&&a[la]?a.i(b,c,d,e):a&&(a=Ub(a))&&(b=bb(a,b,c,!!d,e))&&T(b)}
function T(a){if("number"==typeof a||!a||a.H)return!1;var b=a.src;if(b&&b[la])return ab(b.F,a);var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.M):b.detachEvent&&b.detachEvent(Wb(c),d);Sb--;(c=Ub(b))?(ab(c,a),0==c.b&&(c.src=null,b[Qb]=null)):oa(a);return!0}function Wb(a){return a in Rb?Rb[a]:Rb[a]="on"+a}function Zb(a,b,c,d){var e=!0;if(a=Ub(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.M==c&&!f.H&&(f=$b(f,d),e=e&&!1!==f)}return e}
function $b(a,b){var c=a.listener,d=a.N||a.src;a.L&&T(a);return c.call(d,b)}
function Xb(a,b){if(a.H)return!0;if(!Ob){var c;if(!(c=b))a:{c=["window","event"];for(var d=n,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break a}c=d}e=c;c=new R(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){a:{var f=!1;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(g){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.a;f;f=f.parentNode)e.push(f);for(var f=a.type,h=e.length-1;!c.f&&0<=h;h--){c.a=e[h];var k=Zb(e[h],f,!0,c),d=d&&k}for(h=0;!c.f&&h<e.length;h++)c.a=e[h],k=Zb(e[h],
f,!1,c),d=d&&k}return d}return $b(a,new R(b,this))}function Ub(a){a=a[Qb];return a instanceof Za?a:null}var ac="__closure_events_fn_"+(1E9*Math.random()>>>0);function Tb(a){if("function"==q(a))return a;a[ac]||(a[ac]=function(b){return a.handleEvent(b)});return a[ac]};function bc(a){y.call(this);this.b=a;this.a={}}x(bc,y);var cc=[];bc.prototype.f=function(a,b,c,d){r(b)||(b&&(cc[0]=b.toString()),b=cc);for(var e=0;e<b.length;e++){var f=S(a,b[e],c||this.handleEvent,d||!1,this.b||this);if(!f)break;this.a[f.aa]=f}return this};
bc.prototype.i=function(a,b,c,d,e){if(r(b))for(var f=0;f<b.length;f++)this.i(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.b||this,c=Tb(c),d=!!d,b=a&&a[la]?bb(a.F,String(b),c,d,e):a?(a=Ub(a))?bb(a,b,c,d,e):null:null,b&&(T(b),delete this.a[b.aa]);return this};bc.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function U(){y.call(this);this.F=new Za(this);this.oa=this;this.S=null}x(U,y);U.prototype[la]=!0;U.prototype.addEventListener=function(a,b,c,d){S(this,a,b,c,d)};U.prototype.removeEventListener=function(a,b,c,d){Yb(this,a,b,c,d)};
function V(a,b){var c,d=a.S;if(d)for(c=[];d;d=d.S)c.push(d);var d=a.oa,e=b,f=e.type||e;if(t(e))e=new z(e,d);else if(e instanceof z)e.target=e.target||d;else{var g=e,e=new z(f,d);ra(e,g)}var g=!0,h;if(c)for(var k=c.length-1;!e.f&&0<=k;k--)h=e.a=c[k],g=dc(h,f,!0,e)&&g;e.f||(h=e.a=d,g=dc(h,f,!0,e)&&g,e.f||(g=dc(h,f,!1,e)&&g));if(c)for(k=0;!e.f&&k<c.length;k++)h=e.a=c[k],g=dc(h,f,!1,e)&&g;return g}U.prototype.f=function(a,b,c,d){return this.F.add(String(a),b,!1,c,d)};
U.prototype.i=function(a,b,c,d){return this.F.remove(String(a),b,c,d)};function dc(a,b,c,d){b=a.F.a[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.H&&g.M==c){var h=g.listener,k=g.N||g.src;g.L&&ab(a.F,g);e=!1!==h.call(k,d)&&e}}return e&&0!=d.ka};function ec(a,b,c,d,e){if(!(J||L&&N("525")))return!0;if(M&&e)return fc(a);if(e&&!d)return!1;"number"==typeof b&&(b=gc(b));if(!c&&(17==b||18==b||M&&91==b))return!1;if(L&&d&&c)switch(a){case 220:case 219:case 221:case 192:case 186:case 189:case 187:case 188:case 190:case 191:case 192:case 222:return!1}if(J&&d&&b==a)return!1;switch(a){case 13:return!0;case 27:return!L}return fc(a)}
function fc(a){if(48<=a&&57>=a||96<=a&&106>=a||65<=a&&90>=a||L&&0==a)return!0;switch(a){case 32:case 63:case 107:case 109:case 110:case 111:case 186:case 59:case 189:case 187:case 61:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:return!0;default:return!1}}function gc(a){if(K)a=hc(a);else if(M&&L)a:switch(a){case 93:a=91;break a}return a}
function hc(a){switch(a){case 61:return 187;case 59:return 186;case 173:return 189;case 224:return 91;case 0:return 224;default:return a}};function ic(a,b){U.call(this);a&&jc(this,a,b)}x(ic,U);l=ic.prototype;l.I=null;l.O=null;l.V=null;l.P=null;l.s=-1;l.w=-1;l.T=!1;
var kc={3:13,12:144,63232:38,63233:40,63234:37,63235:39,63236:112,63237:113,63238:114,63239:115,63240:116,63241:117,63242:118,63243:119,63244:120,63245:121,63246:122,63247:123,63248:44,63272:46,63273:36,63275:35,63276:33,63277:34,63289:144,63302:45},lc={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},mc=J||L&&N("525"),nc=M&&K;
ic.prototype.a=function(a){L&&(17==this.s&&!a.ctrlKey||18==this.s&&!a.b||M&&91==this.s&&!a.metaKey)&&(this.w=this.s=-1);-1==this.s&&(a.ctrlKey&&17!=a.keyCode?this.s=17:a.b&&18!=a.keyCode?this.s=18:a.metaKey&&91!=a.keyCode&&(this.s=91));mc&&!ec(a.keyCode,this.s,a.l,a.ctrlKey,a.b)?this.handleEvent(a):(this.w=gc(a.keyCode),nc&&(this.T=a.b))};ic.prototype.b=function(a){this.w=this.s=-1;this.T=a.b};
ic.prototype.handleEvent=function(a){var b=a.c,c,d,e=b.altKey;J&&"keypress"==a.type?(c=this.w,d=13!=c&&27!=c?b.keyCode:0):L&&"keypress"==a.type?(c=this.w,d=0<=b.charCode&&63232>b.charCode&&fc(c)?b.charCode:0):mb?(c=this.w,d=fc(c)?b.keyCode:0):(c=b.keyCode||this.w,d=b.charCode||0,nc&&(e=this.T),M&&63==d&&224==c&&(c=191));var f=c=gc(c),g=b.keyIdentifier;c?63232<=c&&c in kc?f=kc[c]:25==c&&a.l&&(f=9):g&&g in lc&&(f=lc[g]);this.s=f;a=new oc(f,d,0,b);a.b=e;V(this,a)};
function jc(a,b,c){a.P&&pc(a);a.I=b;a.O=S(a.I,"keypress",a,c);a.V=S(a.I,"keydown",a.a,c,a);a.P=S(a.I,"keyup",a.b,c,a)}function pc(a){a.O&&(T(a.O),T(a.V),T(a.P),a.O=null,a.V=null,a.P=null);a.I=null;a.s=-1;a.w=-1}function oc(a,b,c,d){R.call(this,d);this.type="key";this.keyCode=a;this.i=b}x(oc,R);function W(a,b){var c=Q(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,null))?c[b]||c.getPropertyValue(b)||"":""}function X(a,b){return W(a,b)||(a.currentStyle?a.currentStyle[b]:null)||a.style&&a.style[b]}
function qc(a){var b;try{b=a.getBoundingClientRect()}catch(c){return{left:0,top:0,right:0,bottom:0}}J&&a.ownerDocument.body&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b}
function rc(a){if(J&&!O(8))return a.offsetParent;var b=Q(a),c=X(a,"position"),d="fixed"==c||"absolute"==c;for(a=a.parentNode;a&&a!=b;a=a.parentNode)if(11==a.nodeType&&a.host&&(a=a.host),c=X(a,"position"),d=d&&"static"==c&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==c||"absolute"==c||"relative"==c))return a;return null}
function sc(a){for(var b=new H(0,Infinity,Infinity,0),c=P(a),d=c.a.body,e=c.a.documentElement,f=Bb(c.a);a=rc(a);)if(!(J&&0==a.clientWidth||L&&0==a.clientHeight&&a==d)&&a!=d&&a!=e&&"visible"!=X(a,"overflow")){var g=Y(a),h=new G(a.clientLeft,a.clientTop);g.x+=h.x;g.y+=h.y;b.top=Math.max(b.top,g.y);b.right=Math.min(b.right,g.x+a.clientWidth);b.bottom=Math.min(b.bottom,g.y+a.clientHeight);b.left=Math.max(b.left,g.x)}d=f.scrollLeft;f=f.scrollTop;b.left=Math.max(b.left,d);b.top=Math.max(b.top,f);c=(Cb(c.a)||
window).document;c="CSS1Compat"==c.compatMode?c.documentElement:c.body;c=new A(c.clientWidth,c.clientHeight);b.right=Math.min(b.right,d+c.width);b.bottom=Math.min(b.bottom,f+c.height);return 0<=b.top&&0<=b.left&&b.bottom>b.top&&b.right>b.left?b:null}function Y(a){var b=Q(a),c=new G(0,0),d;d=b?Q(b):document;d=!J||O(9)||Gb(P(d))?d.documentElement:d.body;if(a==d)return c;a=qc(a);b=P(b);b=Ab(b.a);c.x=a.left+b.x;c.y=a.top+b.y;return c}function tc(a){"number"==typeof a&&(a=a+"px");return a}
function uc(a){var b=vc;if("none"!=X(a,"display"))return b(a);var c=a.style,d=c.display,e=c.visibility,f=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";a=b(a);c.display=d;c.position=f;c.visibility=e;return a}function vc(a){var b=a.offsetWidth,c=a.offsetHeight,d=L&&!b&&!c;return(void 0===b||d)&&a.getBoundingClientRect?(a=qc(a),new A(a.right-a.left,a.bottom-a.top)):new A(b,c)}var wc=K?"MozUserSelect":L?"WebkitUserSelect":null;
function xc(a){var b=a.getElementsByTagName("*");if(wc){var c="none";a.style[wc]=c;if(b){a=0;for(var d;d=b[a];a++)d.style[wc]=c}}else if(J||mb)if(c="on",a.setAttribute("unselectable",c),b)for(a=0;d=b[a];a++)d.setAttribute("unselectable",c)}function yc(a,b){if(/^\d+px?$/.test(b))return parseInt(b,10);var c=a.style.left,d=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=b;var e=a.style.pixelLeft;a.style.left=c;a.runtimeStyle.left=d;return e}
function zc(a,b){var c=a.currentStyle?a.currentStyle[b]:null;return c?yc(a,c):0}var Ac={thin:2,medium:4,thick:6};function Bc(a,b){if("none"==(a.currentStyle?a.currentStyle[b+"Style"]:null))return 0;var c=a.currentStyle?a.currentStyle[b+"Width"]:null;return c in Ac?Ac[c]:yc(a,c)}
function Cc(a){if(J&&!O(9)){var b=Bc(a,"borderLeft"),c=Bc(a,"borderRight"),d=Bc(a,"borderTop");a=Bc(a,"borderBottom");return new H(d,c,a,b)}b=W(a,"borderLeftWidth");c=W(a,"borderRightWidth");d=W(a,"borderTopWidth");a=W(a,"borderBottomWidth");return new H(parseFloat(d),parseFloat(c),parseFloat(a),parseFloat(b))};function Dc(a,b){return(b&4&&"rtl"==X(a,"direction")?b^2:b)&-5};function Ec(a,b){U.call(this);this.c=a||1;this.b=b||n;this.j=u(this.o,this);this.m=ha()}x(Ec,U);Ec.prototype.h=!1;Ec.prototype.a=null;Ec.prototype.o=function(){if(this.h){var a=ha()-this.m;0<a&&a<.8*this.c?this.a=this.b.setTimeout(this.j,this.c-a):(this.a&&(this.b.clearTimeout(this.a),this.a=null),V(this,Fc),this.h&&(this.a=this.b.setTimeout(this.j,this.c),this.m=ha()))}};var Fc="tick";function Gc(a,b,c){U.call(this);this.v=a;this.J=c;this.c=b;S(b,[Hc,Ic,Jc,Kc],this.handleEvent,!1,this);this.m=null;this.b=[];this.h=-1;this.a=0;this.j=this.o=null;this.K={}}x(Gc,U);Gc.prototype.D=10;var Hc="hilite",Ic="select",Kc="dismiss",Jc="canceldismiss";l=Gc.prototype;
l.handleEvent=function(a){var b=this.v;if(a.target==this.c)switch(a.type){case Hc:this.B(a.C);break;case Ic:var c=!1;if("number"==typeof a.C){a=a.C;var d=this.b[Lc(this,a)],c=!!d&&b.U&&b.U(d);d&&!c&&this.h!=a&&this.B(a)}c||Mc(this);break;case Jc:Nc(this);break;case Kc:Oc(this)}};function Pc(a){for(var b=a.a+a.b.length-1,c=a.h,d=0;d<a.b.length;d++){if(c>=a.a&&c<b)c++;else if(-1==c)c=a.a;else break;if(a.B(c))break}}
l.B=function(a){var b=Lc(this,a),c=this.b[b];return c&&this.v.U&&this.v.U(c)?!1:(this.h=a,this.c.B(a),-1!=b)};
function Mc(a){var b=Lc(a,a.h);if(-1!=b){var c=a.b[b],d=a.J;if(d.g){var e=c.toString();if(d.c){var f=Qc(d,d.g.value,Kb(d.g)[0]),g=Rc(d,d.g.value);d.S.test(e)||(e=e.replace(/[\s\xa0]+$/,"")+d.v);0==f||/^[\s\xa0]*$/.test(g[f-1])||(e=" "+e);f==g.length-1&&(e+=" ");if(e!=g[f]){g[f]=e;e=d.g;(K||J&&N("9"))&&e.blur();e.value=g.join("");for(var h=0,k=0;k<=f;k++)h+=g[k].length;e.focus();f=h;g=d.g;e=f;Lb(g)?g.selectionStart=e:J&&(h=Mb(g),k=h[0],k.inRange(h[1])&&(e=Nb(g,e),k.collapse(!0),k.move("character",
e),k.select()));g=d.g;Lb(g)?g.selectionEnd=f:J&&(h=Mb(g),e=h[1],h[0].inRange(e)&&(f=Nb(g,f),g=Nb(g,Kb(g)[0]),e.collapse(!0),e.moveEnd("character",f-g),e.select()))}}else d.R(e);d.Y=!0}a.u();V(a,{type:"update",C:c,index:b});return!0}a.u();V(a,{type:"update",C:null,index:null});return!1}l.u=function(){this.h=-1;this.m=null;this.a+=this.b.length;this.b=[];window.clearTimeout(this.j);this.j=null;this.c.u();V(this,"suggestionsupdate");V(this,Kc)};
function Oc(a){a.j||(a.j=window.setTimeout(u(a.u,a),100))}l.ca=function(){return this.j?(window.clearTimeout(this.j),this.j=null,!0):!1};function Nc(a){a.ca()||window.setTimeout(u(a.ca,a),10)}l.Da=function(a,b,c){this.m==a&&this.X(b,c)};
l.X=function(a,b){var c="object"==q(b)&&b,d=(c?c.Ha():b)?Lc(this,this.h):-1;this.a+=this.b.length;this.b=a;for(var e=[],f=0;f<a.length;++f)e.push({id:this.a+f,data:a[f]});f=null;if(this.o){var f=this.K,g;g=this.o;g=g[ca]||(g[ca]=++ea);f=f[g]||this.o}this.c.pa=f;this.c.X(e,this.m,this.o);f=!0;c&&void 0!==c.wa()&&(f=c.wa());this.h=-1;(f||0<=d)&&0!=e.length&&this.m&&(0<=d?this.B(this.a+d):Pc(this));V(this,"suggestionsupdate")};function Lc(a,b){var c=b-a.a;return 0>c||c>=a.b.length?-1:c}l.update=function(a){this.J.update(a)};function Sc(a,b,c,d){U.call(this);this.v=a||document.body;this.j=P(this.v);this.sa=!a;this.b=null;this.D="";this.c=[];this.h=[];this.J=this.o=-1;this.l=!1;this.className="ac-renderer";this.qa="ac-highlighted";this.m=b||null;this.ua=null!=d?d:!0;this.ta=!!c}x(Sc,U);l=Sc.prototype;l.X=function(a,b,c){this.D=b;this.c=a;this.o=-1;this.J=ha();this.a=c;this.h=[];Tc(this)};l.u=function(){this.a&&Jb(this.a,null);this.l&&(this.l=!1,this.a&&Ib(this.a,"haspopup",!1),this.b.style.display="none")};
function Uc(a){a.l||(a.l=!0,a.a&&(Hb(a.a,"combobox"),Ib(a.a,"autocomplete","list"),Ib(a.a,"haspopup",!0)),a.b.style.display="")}
function Vc(a,b){var c=0<=b&&b<a.c.length?a.c[b]:void 0,d=0<=b&&b<a.h.length?a.h[b]:void 0;if(V(a,{type:"rowhilite",Ka:d,C:c?c.data:null})&&(0<=a.o&&Ya(a.h[a.o]),a.o=b,d)){Wa(d,["ac-active","active"]);a.a&&Jb(a.a,d);var c=a.b,e,f=Y(d);e=Y(c);var g=Cc(c),h=f.x-e.x-g.left,f=f.y-e.y-g.top,k=c.clientWidth-d.offsetWidth,d=c.clientHeight-d.offsetHeight,m=c.scrollLeft,p=c.scrollTop;if(c==document.body||c==document.documentElement)m=e.x+g.left,p=e.y+g.top,J&&!O(10)&&(m+=g.left,p+=g.top);m+=Math.min(h,Math.max(h-
k,0));p+=Math.min(f,Math.max(f-d,0));e=new G(m,p);c.scrollLeft=e.x;c.scrollTop=e.y}}l.B=function(a){if(-1==a)Vc(this,-1);else for(var b=0;b<this.c.length;b++)if(this.c[b].id==a){Vc(this,b);break}};function Wc(a){if(!a.b){var b=a.j.b("DIV",{style:"display:none"});a.b=b;Wa(b,ua(a.className).split(" "));Hb(b,"listbox");b.id=":"+(I.a().a++).toString(36);a.v.appendChild(b);S(b,"click",a.za,!1,a);S(b,"mousedown",a.Ba,!1,a);S(b,"mouseover",a.Ca,!1,a)}}
function Tc(a){Wc(a);a.va&&(a.b.style.minWidth=a.va.clientWidth+"px");a.h.length=0;a.j.f(a.b);a.m&&a.m.Ia||C(a.c,function(a){var c=a;a=this.D;var d=this.j.b("DIV",{className:"ac-row",id:":"+(I.a().a++).toString(36)});Hb(d,"option");if(!this.m||!this.m.Ja)if(c=c.data.toString(),"textContent"in d)d.textContent=c;else if(3==d.nodeType)d.data=c;else if(d.firstChild&&3==d.firstChild.nodeType){for(;d.lastChild!=d.firstChild;)d.removeChild(d.lastChild);d.firstChild.data=c}else Eb(d),d.appendChild(Q(d).createTextNode(String(c)));
a&&this.ua&&(this.K=!1,Xc(this,d,a));Va(d,"ac-row");this.h.push(d);this.b.appendChild(d)},a);0==a.c.length?a.u():(Uc(a),Yc(a),xc(a.b))}
function Yc(a){if(a.a&&a.sa){var b=a.pa||a.a,c;c=a.ta?3:1;a=a.b;var d=c^1,e,f;if(e=a.offsetParent){var g="HTML"==e.tagName||"BODY"==e.tagName;g&&"static"==X(e,"position")||(f=Y(e),g||(g=(g="rtl"==X(e,"direction"))&&K?-e.scrollLeft:!g||J&&N("8")||"visible"==X(e,"overflowX")?e.scrollLeft:e.scrollWidth-e.clientWidth-e.scrollLeft,f=ib(f,new G(g,e.scrollTop))))}e=f||new G;f=Y(b);g=uc(b);f=new jb(f.x,f.y,g.width,g.height);if(g=sc(b)){var h=new jb(g.left,g.top,g.right-g.left,g.bottom-g.top),g=Math.max(f.left,
h.left),k=Math.min(f.left+f.width,h.left+h.width);if(g<=k){var m=Math.max(f.top,h.top),h=Math.min(f.top+f.height,h.top+h.height);m<=h&&(f.left=g,f.top=m,f.width=k-g,f.height=h-m)}}g=P(b);m=P(a);if(g.a!=m.a){var k=g.a.body,m=Cb(m.a),h=new G(0,0),p;p=(p=Q(k))?Cb(p):window;var v=k;do{var w;p==m?w=Y(v):(w=qc(v),w=new G(w.left,w.top));h.x+=w.x;h.y+=w.y}while(p&&p!=m&&p!=p.parent&&(v=p.frameElement)&&(p=p.parent));k=ib(h,Y(k));!J||O(9)||Gb(g)||(k=ib(k,Ab(g.a)));f.left+=k.x;f.top+=k.y}b=Dc(b,c);c=new G(b&
2?f.left+f.width:f.left,b&1?f.top+f.height:f.top);c=ib(c,e);if(b=sc(a))b.top-=e.y,b.right-=e.x,b.bottom-=e.y,b.left-=e.x;c=c.clone();f=Dc(a,d);d=uc(a);e=d.clone();c=c.clone();e=e.clone();0!=f&&(f&2&&(c.x-=e.width+0),f&1&&(c.y-=e.height+0));b?(f=c,g=e,k=65,m=0,65==(k&65)&&(f.x<b.left||f.x>=b.right)&&(k&=-2),132==(k&132)&&(f.y<b.top||f.y>=b.bottom)&&(k&=-5),f.x<b.left&&k&1&&(f.x=b.left,m|=1),k&16&&(h=f.x,f.x<b.left&&(f.x=b.left,m|=4),f.x+g.width>b.right&&(g.width=Math.min(b.right-f.x,h+g.width-b.left),
g.width=Math.max(g.width,0),m|=4)),f.x+g.width>b.right&&k&1&&(f.x=Math.max(b.right-g.width,b.left),m|=1),k&2&&(m=m|(f.x<b.left?16:0)|(f.x+g.width>b.right?32:0)),f.y<b.top&&k&4&&(f.y=b.top,m|=2),k&32&&(h=f.y,f.y<b.top&&(f.y=b.top,m|=8),f.y+g.height>b.bottom&&(g.height=Math.min(b.bottom-f.y,h+g.height-b.top),g.height=Math.max(g.height,0),m|=8)),f.y+g.height>b.bottom&&k&4&&(f.y=Math.max(b.bottom-g.height,b.top),m|=2),k&8&&(m=m|(f.y<b.top?64:0)|(f.y+g.height>b.bottom?128:0)),f=m):f=256;b=new jb(0,0,0,
0);b.left=c.x;b.top=c.y;b.width=e.width;b.height=e.height;f&496||(e=new G(b.left,b.top),e instanceof G?(c=e.x,e=e.y):(c=e,e=void 0),a.style.left=tc(c),a.style.top=tc(e),e=new A(b.width,b.height),d==e||d&&e&&d.width==e.width&&d.height==e.height||(d=e,c=Gb(P(Q(a))),!J||N("10")||c&&N("8")?(a=a.style,K?a.MozBoxSizing="border-box":L?a.WebkitBoxSizing="border-box":a.boxSizing="border-box",a.width=Math.max(d.width,0)+"px",a.height=Math.max(d.height,0)+"px"):(b=a.style,c?(J?(c=zc(a,"paddingLeft"),e=zc(a,
"paddingRight"),f=zc(a,"paddingTop"),g=zc(a,"paddingBottom"),c=new H(f,e,g,c)):(c=W(a,"paddingLeft"),e=W(a,"paddingRight"),f=W(a,"paddingTop"),g=W(a,"paddingBottom"),c=new H(parseFloat(f),parseFloat(e),parseFloat(g),parseFloat(c))),a=Cc(a),b.pixelWidth=d.width-a.left-c.left-c.right-a.right,b.pixelHeight=d.height-a.top-c.top-c.bottom-a.bottom):(b.pixelWidth=d.width,b.pixelHeight=d.height))))}}
function Xc(a,b,c){if(!a.K)if(3==b.nodeType){var d=null;r(c)&&1<c.length&&(d=Ka(c,1));c=Zc(c);if(0!=c.length){var e=b.nodeValue,f=new RegExp("\\b(?:"+c+")","gi");c=[];for(var g=0,h=f.exec(e),k=0;h;)k++,c.push(e.substring(g,h.index)),c.push(e.substring(h.index,f.lastIndex)),g=f.lastIndex,h=f.exec(e);c.push(e.substring(g));if(1<c.length){for(d=0;1>d;d++)e=2*d,b.nodeValue=c[e],f=a.j.a.createElement("B"),f.className=a.qa,f.appendChild(a.j.a.createTextNode(String(c[e+1]))),f=b.parentNode.insertBefore(f,
b.nextSibling),b.parentNode.insertBefore(a.j.a.createTextNode(""),f.nextSibling),b=f.nextSibling;b.nodeValue=Ka(c,2).join("");a.K=!0}else d&&Xc(a,b,d)}}else for(b=b.firstChild;b;)d=b.nextSibling,Xc(a,b,c),b=d}function Zc(a){var b="";if(!a)return b;r(a)&&(a=Ga(a,function(a){return!/^[\s\xa0]*$/.test(null==a?"":String(a))}));r(a)?b=0<a.length?Da(a[0]):"":/^\W/.test(a)||(b=Da(a));return b}function $c(a,b){for(;b&&b!=a.b&&!Ua(b,"ac-row");)b=b.parentNode;return b?Fa(a.h,b):-1}
l.za=function(a){var b=$c(this,a.target);0<=b&&V(this,{type:Ic,C:this.c[b].id});a.stopPropagation()};l.Ba=function(a){a.stopPropagation();a.preventDefault()};l.Ca=function(a){a=$c(this,a.target);0<=a&&!(300>ha()-this.J)&&V(this,{type:Hc,C:this.c[a].id})};var ad=E("iPhone")&&!E("iPod")&&!E("iPad")||E("iPod"),bd=E("iPad");!E("Android")||hb()||E("Firefox")||fb();hb();function cd(a,b,c,d){y.call(this);d=d||150;this.c=null!=c?c:!0;this.i=a||",;";this.v=this.i.substring(0,1);a=this.c?"[\\s"+this.i+"]+":"[\\s]+";this.o=new RegExp("^"+a+"|"+a+"$","g");this.S=new RegExp("\\s*["+this.i+"]$");this.m=b||"";this.D=this.c;this.f=0<d?new Ec(d):null;this.b=new bc(this);this.h=new bc(this);this.l=new ic;this.j=-1}x(cd,y);var dd=(ad||bd)&&!N("533.17.9");l=cd.prototype;l.g=null;l.W="";l.A=!1;l.Y=!1;l.R=function(a){this.g.value=a};
l.xa=function(a){for(var b=0;b<arguments.length;b++){var c=arguments[b];ba(c)&&1==c.nodeType&&Ib(c,"haspopup",!0);this.b.f(c,"focus",this.ba);this.b.f(c,"blur",this.ya);if(!this.g&&(this.h.f(c,"keydown",this.Ea),ba(c)&&1==c.nodeType)){var d;a:{var e=Q(c);try{d=e&&e.activeElement;break a}catch(f){}d=null}d==c&&ed(this,c)}}};
function fd(a,b){switch(b.keyCode){case 40:if(a.a.c.l){Pc(a.a);b.preventDefault();return}if(!a.c){a.update(!0);b.preventDefault();return}break;case 38:if(a.a.c.l){a:for(var c=a.a,d=c.h,e=0;e<c.b.length;e++){if(d>c.a)d--;else break;if(c.B(d))break a}b.preventDefault();return}break;case 9:if(!a.a.c.l||b.l)a.a.u();else if(a.update(),Mc(a.a)&&a.D){b.preventDefault();return}break;case 13:if(a.a.c.l){if(a.update(),Mc(a.a)){b.preventDefault();b.stopPropagation();return}}else a.a.u();break;case 27:if(a.a.c.l){a.a.u();
b.preventDefault();b.stopPropagation();return}break;case 229:if(!a.A){a.A||(a.b.f(a.g,"keyup",a.fa),a.b.f(a.g,"keypress",a.ea),a.A=!0);return}}gd(a,b)}function gd(a,b){var c=a.c&&b.i&&-1!=a.i.indexOf(String.fromCharCode(b.i));c&&a.update();c&&Mc(a.a)&&b.preventDefault()}l.Aa=function(){return!1};l.ba=function(a){ed(this,a.target||null)};
function ed(a,b){var c=a.h;pa(c.a,T);c.a={};a.a&&Nc(a.a);b!=a.g&&(a.g=b,a.f&&(c=a.f,c.h=!0,c.a||(c.a=c.b.setTimeout(c.j,c.c),c.m=ha()),a.b.f(a.f,Fc,a.ia)),a.W=a.g.value,jc(a.l,a.g),a.b.f(a.l,"key",a.ga),a.b.f(a.g,"mousedown",a.ha),J&&a.b.f(a.g,"keypress",a.da))}l.ya=function(){dd?window.setTimeout(u(this.ja,this),0):this.ja()};
l.ja=function(){if(this.g){this.b.i(this.l,"key",this.ga);pc(this.l);this.b.i(this.g,"keyup",this.Aa);this.b.i(this.g,"mousedown",this.ha);J&&this.b.i(this.g,"keypress",this.da);this.A&&hd(this);this.g=null;if(this.f){var a=this.f;a.h=!1;a.a&&(a.b.clearTimeout(a.a),a.a=null);this.b.i(this.f,Fc,this.ia)}this.a&&Oc(this.a)}};l.ia=function(){this.update()};l.Ea=function(a){this.ba(a)};l.ga=function(a){this.j=a.keyCode;this.a&&fd(this,a)};l.ea=function(){this.A&&229!=this.j&&hd(this)};
l.fa=function(a){this.A&&(13==a.keyCode||77==a.keyCode&&a.ctrlKey)&&hd(this)};l.ha=function(){};function hd(a){a.A&&(a.A=!1,a.b.i(a.g,"keypress",a.ea),a.b.i(a.g,"keyup",a.fa))}l.da=function(a){gd(this,a)};
l.update=function(a){if(this.g&&(a||this.g.value!=this.W)){if(a||!this.Y){var b;a=Kb(this.g)[0];b=this.g.value;a=Rc(this,b)[Qc(this,b,a)];b=this.o?String(a).replace(this.o,""):a;if(this.a&&(this.a.o=this.g,a=this.a,a.m!=b)){a.m=b;var c=a.v;b=a.m;var d=a.D,e=u(a.Da,a),c=c.a,f;f=[];if(""!=b)for(var g=Da(b),g=new RegExp("(^|\\W+)"+g,"i"),h=0;h<c.length&&f.length<d;h++){var k=c[h];String(k).match(g)&&f.push(k)}0==f.length&&(f=lb(b,d,c));e(b,f);Nc(a)}}this.W=this.g.value}this.Y=!1};
function Qc(a,b,c){a=Rc(a,b);if(c==b.length)return a.length-1;for(var d=b=0,e=0;d<a.length&&e<=c;d++)e+=a[d].length,b=d;return b}function Rc(a,b){if(!a.c)return[b];for(var c=String(b).split(""),d=[],e=[],f=0,g=!1;f<c.length;f++)a.m&&-1!=a.m.indexOf(c[f])?(g||(d.push(e.join("")),e.length=0),e.push(c[f]),g=!g):g||-1==a.i.indexOf(c[f])?e.push(c[f]):(e.push(c[f]),d.push(e.join("")),e.length=0);d.push(e.join(""));return d};function id(a,b){var c=new kb(a),d=new Sc,e=new cd(null,null,!1),c=new Gc(c,d,e);e.a=c;e.xa(b);return c};function jd(){var a=n.TYPES;kd(a);ld(a);md()}var nd=["init"],Z=n;nd[0]in Z||!Z.execScript||Z.execScript("var "+nd[0]);for(var od;nd.length&&(od=nd.shift());)nd.length||void 0===jd?Z[od]?Z=Z[od]:Z=Z[od]={}:Z[od]=jd;var Sa=function(){var a="";Ha(document.querySelectorAll("script"),function(b){b=b.getAttribute("src");var c=b.length;return"dossier.js"===b.slice(c-10)?(a=b.slice(0,c-10),!0):!1});return a}();
function md(){function a(a){a=Fb(a,function(a){return"TR"===a.nodeName});Va(a,"hilite")}var b=document.querySelector("article.srcfile table");if(b){if(location.hash){var c=document.querySelector("tr > td a"+location.hash);c&&a(c)}S(window,"hashchange",function(){C(b.querySelectorAll("tr.hilite"),function(a){Xa(a,"hilite")});var c=b.querySelector("tr > td a:target");c&&a(c)})}}
function kd(a){function b(){var a=c[e.value];a&&(window.location.href=Sa+a)}var c={},d=[];a.types&&C(a.types,function(a){pd(d,c,a)});a.modules&&C(a.modules,function(a){pd(d,c,a,!0)});a=document.querySelector("header form");S(a,"submit",function(a){a.preventDefault();a.stopPropagation();b();return!1});var e=a.querySelector("input");e.setAttribute("title","Search ("+(M?"⌘":"Ctrl+")+"E)");a=id(d,e);a.D=20;S(a,"update",b);S(document.documentElement,"keydown",function(a){if(document.activeElement!==e&&
69===a.keyCode&&(M?a.metaKey:a.ctrlKey))return e.focus(),a.preventDefault(),a.stopPropagation(),!1;document.activeElement===e&&27===a.keyCode&&e.blur()})}
function pd(a,b,c,d,e){var f=c.name;e&&(f=e+(ta(e,")")?" ":".")+f);b[f]=c.href;a.push(f);d&&(f="("+f+")");d&&c.types&&C(c.types,function(c){pd(a,b,c,!1,f)});c.statics&&C(c.statics,function(d){var e=c.href+"#"+d;d=ta(f,")")?f+" "+d:-1===d.indexOf(".")?f+"."+d:f+d.slice(d.lastIndexOf("."));b[d]=e;a.push(d)});c.members&&C(c.members,function(d){b[f+"#"+d]=c.href+"#"+d;a.push(f+"#"+d)})}
function ld(a){var b="";Sa?b=window.location.pathname.split("/").slice(Sa.split("/").length).join("/"):window.location.pathname&&"/"!==window.location.pathname&&(b=window.location.pathname.slice(window.location.pathname.lastIndexOf("/")+1));var c=La,d=xb("nav-types-view");d&&a.types&&d.appendChild(c.Z(a.types,b,!1));(d=xb("nav-modules-view"))&&a.modules&&d.appendChild(c.Z(a.modules,b,!0));window.localStorage&&(c=document.querySelector("nav"),C(c.querySelectorAll('input[type="checkbox"][id]'),function(a){var b=
window.localStorage.getItem(a.id);a.checked=!t(b)||"closed"===b}),S(c,"change",function(a){window.localStorage.setItem(a.target.id,a.target.checked?"closed":"open")}))};;init();})();
