(function(){var h,n=this;function aa(){}
function ba(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}function r(a){return"array"==ba(a)}function ca(a){var b=ba(a);return"array"==b||"object"==b&&"number"==typeof a.length}function u(a){return"string"==typeof a}function v(a){return"number"==typeof a}function da(a){return"function"==ba(a)}function ea(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function fa(a){return a[ga]||(a[ga]=++ha)}var ga="closure_uid_"+(1E9*Math.random()>>>0),ha=0;
function ia(a,b,c){return a.call.apply(a.bind,arguments)}function ja(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function x(a,b,c){x=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ia:ja;return x.apply(null,arguments)}
function ka(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}}var y=Date.now||function(){return+new Date};function A(a,b){function c(){}c.prototype=b.prototype;a.i=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.ec=function(a,c,f){return b.prototype[c].apply(a,Array.prototype.slice.call(arguments,2))}};var la;var ma=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};function na(a){if(!oa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(pa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(qa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(ra,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(sa,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(ta,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(ua,"&#0;"));return a}var pa=/&/g,qa=/</g,ra=/>/g,sa=/"/g,ta=/'/g,ua=/\x00/g,oa=/[\x00&<>"']/;
function va(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")}function wa(a,b){return a<b?-1:a>b?1:0}function xa(){return"transform".replace(/\-([a-z])/g,function(a,b){return b.toUpperCase()})}function ya(a){var b=u(void 0)?va(void 0):"\\s";return a.replace(new RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,e){return b+e.toUpperCase()})};var B=Array.prototype,za=B.indexOf?function(a,b,c){return B.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(u(a))return u(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},C=B.forEach?function(a,b,c){B.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=u(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Aa=B.filter?function(a,b,c){return B.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=u(a)?
a.split(""):a,k=0;k<d;k++)if(k in g){var l=g[k];b.call(c,l,k,a)&&(e[f++]=l)}return e},Ba=B.map?function(a,b,c){return B.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=u(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};function Ca(a,b){var c;a:{c=a.length;for(var d=u(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){c=e;break a}c=-1}return 0>c?null:u(a)?a.charAt(c):a[c]}function Da(a){return B.concat.apply(B,arguments)}
function Ea(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function Fa(a,b,c){return 2>=arguments.length?B.slice.call(a,b):B.slice.call(a,b,c)};var Ga;a:{var Ha=n.navigator;if(Ha){var Ia=Ha.userAgent;if(Ia){Ga=Ia;break a}}Ga=""}function Ja(a){return-1!=Ga.indexOf(a)};function Ka(a,b){for(var c in a)b.call(void 0,a[c],c,a)}function La(){var a=Ma,b;for(b in a)return!1;return!0}var Na="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Oa(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Na.length;f++)c=Na[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var D=Ja("Opera")||Ja("OPR"),E=Ja("Trident")||Ja("MSIE"),F=Ja("Gecko")&&-1==Ga.toLowerCase().indexOf("webkit")&&!(Ja("Trident")||Ja("MSIE")),G=-1!=Ga.toLowerCase().indexOf("webkit"),Pa=n.navigator||null,Qa=-1!=(Pa&&Pa.platform||"").indexOf("Mac"),Ra,Sa=n.navigator||null;Ra=!!Sa&&-1!=(Sa.appVersion||"").indexOf("X11");function Ta(){var a=n.document;return a?a.documentMode:void 0}
var Ua=function(){var a="",b;if(D&&n.opera)return a=n.opera.version,da(a)?a():a;F?b=/rv\:([^\);]+)(\)|;)/:E?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:G&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(Ga))?a[1]:"");return E&&(b=Ta(),b>parseFloat(a))?String(b):a}(),Va={};
function H(a){var b;if(!(b=Va[a])){b=0;for(var c=ma(String(Ua)).split("."),d=ma(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",k=d[f]||"",l=/(\d*)(\D*)/g,q=/(\d*)(\D*)/g;do{var p=l.exec(g)||["","",""],w=q.exec(k)||["","",""];if(0==p[0].length&&0==w[0].length)break;b=wa(0==p[1].length?0:parseInt(p[1],10),0==w[1].length?0:parseInt(w[1],10))||wa(0==p[2].length,0==w[2].length)||wa(p[2],w[2])}while(0==b)}b=Va[a]=0<=b}return b}
var Wa=n.document,Xa=Wa&&E?Ta()||("CSS1Compat"==Wa.compatMode?parseInt(Ua,10):5):void 0;var Ya=!E||E&&9<=Xa;!F&&!E||E&&E&&9<=Xa||F&&H("1.9.1");E&&H("9");function I(a,b){this.x=void 0!==a?a:0;this.y=void 0!==b?b:0}h=I.prototype;h.clone=function(){return new I(this.x,this.y)};function Za(a,b){return new I(a.x-b.x,a.y-b.y)}h.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};h.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};h.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};
h.translate=function(a,b){a instanceof I?(this.x+=a.x,this.y+=a.y):(this.x+=a,v(b)&&(this.y+=b));return this};h.scale=function(a,b){var c=v(b)?b:a;this.x*=a;this.y*=c;return this};function $a(a,b){this.width=a;this.height=b}h=$a.prototype;h.clone=function(){return new $a(this.width,this.height)};h.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};h.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};h.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};h.scale=function(a,b){var c=v(b)?b:a;this.width*=a;this.height*=c;return this};function J(a){return a?new ab(K(a)):la||(la=new ab)}function L(a){var b=document;return u(a)?b.getElementById(a):a}function bb(a,b){Ka(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in cb?a.setAttribute(cb[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})}
var cb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function db(a){return G||"CSS1Compat"!=a.compatMode?a.body||a.documentElement:a.documentElement}function eb(a){return a.parentWindow||a.defaultView}function fb(a,b,c){return gb(document,arguments)}
function gb(a,b){var c=b[0],d=b[1];if(!Ya&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',na(d.name),'"');if(d.type){c.push(' type="',na(d.type),'"');var e={};Oa(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&(u(d)?c.className=d:r(d)?c.className=d.join(" "):bb(c,d));2<b.length&&hb(a,c,b,2);return c}
function hb(a,b,c,d){function e(c){c&&b.appendChild(u(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var f=c[d];if(!ca(f)||ea(f)&&0<f.nodeType)e(f);else{var g;a:{if(f&&"number"==typeof f.length){if(ea(f)){g="function"==typeof f.item||"string"==typeof f.item;break a}if(da(f)){g="function"==typeof f.item;break a}}g=!1}C(g?Ea(f):f,e)}}}function ib(a){for(var b;b=a.firstChild;)a.removeChild(b)}function jb(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)}
function kb(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}function K(a){return 9==a.nodeType?a:a.ownerDocument||a.document}function ab(a){this.l=a||n.document||document}h=ab.prototype;h.Pa=function(a,b,c){return gb(this.l,arguments)};h.createElement=function(a){return this.l.createElement(a)};h.createTextNode=function(a){return this.l.createTextNode(String(a))};function lb(a){return"CSS1Compat"==a.l.compatMode}
function mb(a){var b=a.l;a=db(b);b=eb(b);return E&&H("10")&&b.pageYOffset!=a.scrollTop?new I(a.scrollLeft,a.scrollTop):new I(b.pageXOffset||a.scrollLeft,b.pageYOffset||a.scrollTop)}h.appendChild=function(a,b){a.appendChild(b)};h.append=function(a,b){hb(K(a),a,arguments,1)};h.canHaveChildren=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
h.Sb=ib;h.removeNode=kb;h.contains=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};E&&H(8);function nb(){this.Rb="";this.wb=ob;this.Cb=null}var ob={};var pb={},qb={};function rb(){throw Error("Do not instantiate directly");}rb.prototype.ya=null;rb.prototype.toString=function(){return this.content};function sb(a,b){var c=J(),d=tb(a(b||ub,void 0,void 0));var e=c.l,c=e.createElement("div");E?(c.innerHTML="<br>"+d,c.removeChild(c.firstChild)):c.innerHTML=d;if(1==c.childNodes.length)d=c.removeChild(c.firstChild);else for(d=e.createDocumentFragment();c.firstChild;)d.appendChild(c.firstChild);return d}function tb(a){if(!ea(a))return String(a);if(a instanceof rb){if(a.za===pb)return a.content;if(a.za===qb)return na(a.content)}return"zSoyz"}var ub={};function vb(a){if(null!=a)switch(a.ya){case 1:return 1;case -1:return-1;case 0:return 0}return null}function wb(){rb.call(this)}A(wb,rb);wb.prototype.za=pb;function M(a){return null!=a&&a.za===pb?a:a instanceof nb?xb(a instanceof nb&&a.constructor===nb&&a.wb===ob?a.Rb:"type_error:SafeHtml",a.Cb):xb(na(String(String(a))),vb(a))}var xb=function(a){function b(a){this.content=a}b.prototype=a.prototype;return function(a,d){var e=new b(String(a));void 0!==d&&(e.ya=d);return e}}(wb);
(function(a){function b(a){this.content=a}b.prototype=a.prototype;return function(a,d){var e=String(a);if(!e)return"";e=new b(e);void 0!==d&&(e.ya=d);return e}})(wb);function yb(a){return'<div class="wrap-details inv '+M(a.visibility)+'"><div><details><summary><label for="show-'+M(a.visibility)+'">Show '+M(a.count)+" hidden item"+(1<a.count?"s":"")+"</label></summary></details></div></div>"}
function zb(a){var b="";if(a.types.length){for(var b=b+"<ul>",c=a.types,d=c.length,e=0;e<d;e++)var f=c[e],b=b+((f.hc?"":'<li class="link"><a href="'+M(a.H)+M(f.href)+'">'+(f.gc?"<i>"+M(f.name)+"</i>":M(f.name))+"</a>")+(a.Aa&&f.types&&f.types.length?zb({types:f.types,H:a.H,Aa:a.Aa}):""));b+="</ul>"}return b}
function Ab(a){var b,c=0<a.file.children.length;b=""+(a.parent?"":"<ul>");if(c){b+=a.file.name?"<li>"+M(a.file.name)+"/<ul>":"";for(var c=a.file.children,d=c.length,e=0;e<d;e++)b+=Ab({file:c[e],H:a.H,parent:a.file});b+=a.file.name?"</ul>":""}else a.file.name&&(b+='<li class="link"><a href="'+M(a.H)+M(a.file.href)+'">'+M(a.file.name)+"</a>");return b+=a.parent?"":"</ul>"};var Bb=!E||E&&9<=Xa,Cb=E&&!H("9");!G||H("528");F&&H("1.9b")||E&&H("8")||D&&H("9.5")||G&&H("528");F&&!H("8")||E&&H("9");function N(){0!=Db&&(Eb[fa(this)]=this);this.ga=this.ga;this.oa=this.oa}var Db=0,Eb={};N.prototype.ga=!1;N.prototype.B=function(){if(!this.ga&&(this.ga=!0,this.f(),0!=Db)){var a=fa(this);delete Eb[a]}};N.prototype.f=function(){if(this.oa)for(;this.oa.length;)this.oa.shift()()};function Fb(a){a&&"function"==typeof a.B&&a.B()};function P(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.M=!1;this.nb=!0}P.prototype.f=function(){};P.prototype.B=function(){};P.prototype.stopPropagation=function(){this.M=!0};P.prototype.preventDefault=function(){this.defaultPrevented=!0;this.nb=!1};function Gb(a){Gb[" "](a);return a}Gb[" "]=aa;function Q(a,b){P.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.charCode=this.keyCode=this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.Q=this.state=null;if(a){var c=this.type=a.type;this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(F){var e;a:{try{Gb(d.nodeName);e=!0;break a}catch(f){}e=!1}e||(d=null)}}else"mouseover"==c?d=
a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=G||void 0!==a.offsetX?a.offsetX:a.layerX;this.offsetY=G||void 0!==a.offsetY?a.offsetY:a.layerY;this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=
a.metaKey;this.state=a.state;this.Q=a;a.defaultPrevented&&this.preventDefault()}}A(Q,P);Q.prototype.stopPropagation=function(){Q.i.stopPropagation.call(this);this.Q.stopPropagation?this.Q.stopPropagation():this.Q.cancelBubble=!0};Q.prototype.preventDefault=function(){Q.i.preventDefault.call(this);var a=this.Q;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Cb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};Q.prototype.f=function(){};var Hb="closure_listenable_"+(1E6*Math.random()|0),Ib=0;function Jb(a,b,c,d,e){this.K=a;this.pa=null;this.src=b;this.type=c;this.ea=!!d;this.ha=e;this.key=++Ib;this.U=this.da=!1}function Kb(a){a.U=!0;a.K=null;a.pa=null;a.src=null;a.ha=null};function Lb(a){this.src=a;this.k={};this.ca=0}Lb.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.k[f];a||(a=this.k[f]=[],this.ca++);var g=Mb(a,b,d,e);-1<g?(b=a[g],c||(b.da=!1)):(b=new Jb(b,this.src,f,!!d,e),b.da=c,a.push(b));return b};Lb.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.k))return!1;var e=this.k[a];b=Mb(e,b,c,d);return-1<b?(Kb(e[b]),B.splice.call(e,b,1),0==e.length&&(delete this.k[a],this.ca--),!0):!1};
function Nb(a,b){var c=b.type;if(!(c in a.k))return!1;var d=a.k[c],e=za(d,b),f;(f=0<=e)&&B.splice.call(d,e,1);f&&(Kb(b),0==a.k[c].length&&(delete a.k[c],a.ca--));return f}Lb.prototype.qa=function(a){a=a&&a.toString();var b=0,c;for(c in this.k)if(!a||c==a){for(var d=this.k[c],e=0;e<d.length;e++)++b,Kb(d[e]);delete this.k[c];this.ca--}return b};Lb.prototype.W=function(a,b,c,d){a=this.k[a.toString()];var e=-1;a&&(e=Mb(a,b,c,d));return-1<e?a[e]:null};
function Mb(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.U&&f.K==b&&f.ea==!!c&&f.ha==d)return e}return-1};var Ob="closure_lm_"+(1E6*Math.random()|0),Pb={},Qb=0;function S(a,b,c,d,e){if(r(b)){for(var f=0;f<b.length;f++)S(a,b[f],c,d,e);return null}c=Rb(c);if(a&&a[Hb])a=a.p(b,c,d,e);else{if(!b)throw Error("Invalid event type");var f=!!d,g=Sb(a);g||(a[Ob]=g=new Lb(a));c=g.add(b,c,!1,d,e);c.pa||(d=Tb(),c.pa=d,d.src=a,d.K=c,a.addEventListener?a.addEventListener(b.toString(),d,f):a.attachEvent(Ub(b.toString()),d),Qb++);a=c}return a}
function Tb(){var a=Vb,b=Bb?function(c){return a.call(b.src,b.K,c)}:function(c){c=a.call(b.src,b.K,c);if(!c)return c};return b}function Wb(a,b,c,d,e){if(r(b))for(var f=0;f<b.length;f++)Wb(a,b[f],c,d,e);else c=Rb(c),a&&a[Hb]?a.u(b,c,d,e):a&&(a=Sb(a))&&(b=a.W(b,c,!!d,e))&&Xb(b)}
function Xb(a){if(v(a)||!a||a.U)return!1;var b=a.src;if(b&&b[Hb])return Nb(b.C,a);var c=a.type,d=a.pa;b.removeEventListener?b.removeEventListener(c,d,a.ea):b.detachEvent&&b.detachEvent(Ub(c),d);Qb--;(c=Sb(b))?(Nb(c,a),0==c.ca&&(c.src=null,b[Ob]=null)):Kb(a);return!0}function Ub(a){return a in Pb?Pb[a]:Pb[a]="on"+a}function Yb(a,b,c,d){var e=1;if(a=Sb(a))if(b=a.k[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.ea==c&&!f.U&&(e&=!1!==Zb(f,d))}return Boolean(e)}
function Zb(a,b){var c=a.K,d=a.ha||a.src;a.da&&Xb(a);return c.call(d,b)}
function Vb(a,b){if(a.U)return!0;if(!Bb){var c;if(!(c=b))a:{c=["window","event"];for(var d=n,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break a}c=d}e=c;c=new Q(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){a:{var f=!1;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(g){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.currentTarget;f;f=f.parentNode)e.push(f);for(var f=a.type,k=e.length-1;!c.M&&0<=k;k--)c.currentTarget=e[k],d&=Yb(e[k],f,!0,c);for(k=0;!c.M&&k<e.length;k++)c.currentTarget=
e[k],d&=Yb(e[k],f,!1,c)}return d}return Zb(a,new Q(b,this))}function Sb(a){a=a[Ob];return a instanceof Lb?a:null}var $b="__closure_events_fn_"+(1E9*Math.random()>>>0);function Rb(a){if(da(a))return a;a[$b]||(a[$b]=function(b){return a.handleEvent(b)});return a[$b]};function ac(a){if(a.classList)return a.classList;a=a.className;return u(a)&&a.match(/\S+/g)||[]}function T(a,b){var c;a.classList?c=a.classList.contains(b):(c=ac(a),c=0<=za(c,b));return c}function bc(a,b){a.classList?a.classList.add(b):T(a,b)||(a.className+=0<a.className.length?" "+b:b)}function cc(a,b){if(a.classList)C(b,function(b){bc(a,b)});else{var c={};C(ac(a),function(a){c[a]=!0});C(b,function(a){c[a]=!0});a.className="";for(var d in c)a.className+=0<a.className.length?" "+d:d}}
function dc(a,b){a.classList?a.classList.remove(b):T(a,b)&&(a.className=Aa(ac(a),function(a){return a!=b}).join(" "))}function ec(a,b){a.classList?C(b,function(b){dc(a,b)}):a.className=Aa(ac(a),function(a){return!(0<=za(b,a))}).join(" ")};function U(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}h=U.prototype;h.clone=function(){return new U(this.top,this.right,this.bottom,this.left)};h.contains=function(a){return this&&a?a instanceof U?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom:!1};
h.expand=function(a,b,c,d){ea(a)?(this.top-=a.top,this.right+=a.right,this.bottom+=a.bottom,this.left-=a.left):(this.top-=a,this.right+=b,this.bottom+=c,this.left-=d);return this};h.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};h.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};
h.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};h.translate=function(a,b){a instanceof I?(this.left+=a.x,this.right+=a.x,this.top+=a.y,this.bottom+=a.y):(this.left+=a,this.right+=a,v(b)&&(this.top+=b,this.bottom+=b));return this};h.scale=function(a,b){var c=v(b)?b:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};function fc(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}h=fc.prototype;h.clone=function(){return new fc(this.left,this.top,this.width,this.height)};h.contains=function(a){return a instanceof fc?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};
h.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};h.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};h.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
h.translate=function(a,b){a instanceof I?(this.left+=a.x,this.top+=a.y):(this.left+=a,v(b)&&(this.top+=b));return this};h.scale=function(a,b){var c=v(b)?b:a;this.left*=a;this.width*=a;this.top*=c;this.height*=c;return this};function V(a,b){var c=K(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,null))?c[b]||c.getPropertyValue(b)||"":""}function W(a,b){return V(a,b)||(a.currentStyle?a.currentStyle[b]:null)||a.style&&a.style[b]}
function gc(a){var b;try{b=a.getBoundingClientRect()}catch(c){return{left:0,top:0,right:0,bottom:0}}E&&a.ownerDocument.body&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b}
function hc(a){if(E&&!(E&&8<=Xa))return a.offsetParent;var b=K(a),c=W(a,"position"),d="fixed"==c||"absolute"==c;for(a=a.parentNode;a&&a!=b;a=a.parentNode)if(c=W(a,"position"),d=d&&"static"==c&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==c||"absolute"==c||"relative"==c))return a;return null}
function ic(a){for(var b=new U(0,Infinity,Infinity,0),c=J(a),d=c.l.body,e=c.l.documentElement,f=db(c.l);a=hc(a);)if(!(E&&0==a.clientWidth||G&&0==a.clientHeight&&a==d)&&a!=d&&a!=e&&"visible"!=W(a,"overflow")){var g=X(a),k;k=a;if(F&&!H("1.9")){var l=parseFloat(V(k,"borderLeftWidth"));if(jc(k))var q=k.offsetWidth-k.clientWidth-l-parseFloat(V(k,"borderRightWidth")),l=l+q;k=new I(l,parseFloat(V(k,"borderTopWidth")))}else k=new I(k.clientLeft,k.clientTop);g.x+=k.x;g.y+=k.y;b.top=Math.max(b.top,g.y);b.right=
Math.min(b.right,g.x+a.clientWidth);b.bottom=Math.min(b.bottom,g.y+a.clientHeight);b.left=Math.max(b.left,g.x)}d=f.scrollLeft;f=f.scrollTop;b.left=Math.max(b.left,d);b.top=Math.max(b.top,f);c=(eb(c.l)||window).document;c="CSS1Compat"==c.compatMode?c.documentElement:c.body;c=new $a(c.clientWidth,c.clientHeight);b.right=Math.min(b.right,d+c.width);b.bottom=Math.min(b.bottom,f+c.height);return 0<=b.top&&0<=b.left&&b.bottom>b.top&&b.right>b.left?b:null}
function X(a){var b,c=K(a),d=W(a,"position"),e=F&&c.getBoxObjectFor&&!a.getBoundingClientRect&&"absolute"==d&&(b=c.getBoxObjectFor(a))&&(0>b.screenX||0>b.screenY),f=new I(0,0),g;b=c?K(c):document;g=!E||E&&9<=Xa||lb(J(b))?b.documentElement:b.body;if(a==g)return f;if(a.getBoundingClientRect)b=gc(a),a=mb(J(c)),f.x=b.left+a.x,f.y=b.top+a.y;else if(c.getBoxObjectFor&&!e)b=c.getBoxObjectFor(a),a=c.getBoxObjectFor(g),f.x=b.screenX-a.screenX,f.y=b.screenY-a.screenY;else{b=a;do{f.x+=b.offsetLeft;f.y+=b.offsetTop;
b!=a&&(f.x+=b.clientLeft||0,f.y+=b.clientTop||0);if(G&&"fixed"==W(b,"position")){f.x+=c.body.scrollLeft;f.y+=c.body.scrollTop;break}b=b.offsetParent}while(b&&b!=a);if(D||G&&"absolute"==d)f.y-=c.body.offsetTop;for(b=a;(b=hc(b))&&b!=c.body&&b!=g;)f.x-=b.scrollLeft,D&&"TR"==b.tagName||(f.y-=b.scrollTop)}return f}function kc(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a}
function lc(a){var b=mc;if("none"!=W(a,"display"))return b(a);var c=a.style,d=c.display,e=c.visibility,f=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";a=b(a);c.display=d;c.position=f;c.visibility=e;return a}function mc(a){var b=a.offsetWidth,c=a.offsetHeight,d=G&&!b&&!c;return(void 0===b||d)&&a.getBoundingClientRect?(a=gc(a),new $a(a.right-a.left,a.bottom-a.top)):new $a(b,c)}function nc(a,b){a.style.display=b?"":"none"}function jc(a){return"rtl"==W(a,"direction")}
var oc=F?"MozUserSelect":G?"WebkitUserSelect":null;function pc(a){var b=a.getElementsByTagName("*");if(oc){var c="none";a.style[oc]=c;if(b){a=0;for(var d;d=b[a];a++)d.style[oc]=c}}else if(E||D)if(c="on",a.setAttribute("unselectable",c),b)for(a=0;d=b[a];a++)d.setAttribute("unselectable",c)}
function qc(a,b){if(/^\d+px?$/.test(b))return parseInt(b,10);var c=a.style.left,d=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=b;var e=a.style.pixelLeft;a.style.left=c;a.runtimeStyle.left=d;return e}function rc(a,b){var c=a.currentStyle?a.currentStyle[b]:null;return c?qc(a,c):0}var sc={thin:2,medium:4,thick:6};
function tc(a,b){if("none"==(a.currentStyle?a.currentStyle[b+"Style"]:null))return 0;var c=a.currentStyle?a.currentStyle[b+"Width"]:null;return c in sc?sc[c]:qc(a,c)}function uc(a){if(E&&!(E&&9<=Xa)){var b=tc(a,"borderLeft"),c=tc(a,"borderRight"),d=tc(a,"borderTop");a=tc(a,"borderBottom");return new U(d,c,a,b)}b=V(a,"borderLeftWidth");c=V(a,"borderRightWidth");d=V(a,"borderTopWidth");a=V(a,"borderBottomWidth");return new U(parseFloat(d),parseFloat(c),parseFloat(a),parseFloat(b))}
var vc=/[^\d]+$/,wc={cm:1,"in":1,mm:1,pc:1,pt:1},xc={em:1,ex:1};function yc(){var a=document.documentElement,b=W(a,"fontSize"),c;c=(c=b.match(vc))&&c[0]||null;if(b&&"px"==c)return parseInt(b,10);if(E){if(c in wc)return qc(a,b);if(a.parentNode&&1==a.parentNode.nodeType&&c in xc)return a=a.parentNode,c=W(a,"fontSize"),qc(a,b==c?"1em":b)}c=fb("span",{style:"visibility:hidden;position:absolute;line-height:0;padding:0;margin:0;border:0;height:1em;"});a.appendChild(c);b=c.offsetHeight;kb(c);return b}
var zc=/matrix\([0-9\.\-]+, [0-9\.\-]+, [0-9\.\-]+, [0-9\.\-]+, ([0-9\.\-]+)p?x?, ([0-9\.\-]+)p?x?\)/;function Ac(a){this.c=a||[];this.ac=!0}function Bc(a,b,c){var d=[];if(""!=a){a=va(a);a=new RegExp("(^|\\W+)"+a,"i");for(var e=0;e<c.length&&d.length<b;e++){var f=c[e];String(f).match(a)&&d.push(f)}}return d}
function Cc(a,b,c){for(var d=[],e=0;e<c.length;e++){var f=c[e],g=a.toLowerCase(),k=String(f).toLowerCase(),l=0;if(-1!=k.indexOf(g))l=parseInt((k.indexOf(g)/4).toString(),10);else for(var q=g.split(""),p=-1,w=10,s=0,R;R=q[s];s++)R=k.indexOf(R),R>p?(p=R-p-1,p>w-5&&(p=w-5),l+=p,p=R):(l+=w,w+=5);l<6*g.length&&d.push({Yb:f,ob:l,index:e})}d.sort(function(a,b){var c=a.ob-b.ob;return 0!=c?c:a.index-b.index});a=[];for(s=0;s<b&&s<d.length;s++)a.push(d[s].Yb);return a};function Y(){N.call(this);this.C=new Lb(this);this.xb=this;this.Ha=null}A(Y,N);Y.prototype[Hb]=!0;h=Y.prototype;h.addEventListener=function(a,b,c,d){S(this,a,b,c,d)};h.removeEventListener=function(a,b,c,d){Wb(this,a,b,c,d)};
h.dispatchEvent=function(a){var b,c=this.Ha;if(c)for(b=[];c;c=c.Ha)b.push(c);var c=this.xb,d=a.type||a;if(u(a))a=new P(a,c);else if(a instanceof P)a.target=a.target||c;else{var e=a;a=new P(d,c);Oa(a,e)}var e=!0,f;if(b)for(var g=b.length-1;!a.M&&0<=g;g--)f=a.currentTarget=b[g],e=Dc(f,d,!0,a)&&e;a.M||(f=a.currentTarget=c,e=Dc(f,d,!0,a)&&e,a.M||(e=Dc(f,d,!1,a)&&e));if(b)for(g=0;!a.M&&g<b.length;g++)f=a.currentTarget=b[g],e=Dc(f,d,!1,a)&&e;return e};
h.f=function(){Y.i.f.call(this);this.C&&this.C.qa(void 0);this.Ha=null};h.p=function(a,b,c,d){return this.C.add(String(a),b,!1,c,d)};h.u=function(a,b,c,d){return this.C.remove(String(a),b,c,d)};function Dc(a,b,c,d){b=a.C.k[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.U&&g.ea==c){var k=g.K,l=g.ha||g.src;g.da&&Nb(a.C,g);e=!1!==k.call(l,d)&&e}}return e&&0!=d.nb}h.W=function(a,b,c,d){return this.C.W(String(a),b,c,d)};function Ec(a,b,c){Y.call(this);this.Z=a;this.$=c;this.q=b;S(b,[Fc,Gc,Hc,Ic],this.handleEvent,!1,this);this.r=null;this.c=[];this.D=-1;this.j=0;this.I=this.g=null;this.Wa={}}A(Ec,Y);h=Ec.prototype;h.ab=10;h.zb=!0;h.Oa=!1;h.vb=!1;h.rb=!1;var Fc="hilite",Gc="select",Ic="dismiss",Hc="canceldismiss";h=Ec.prototype;
h.handleEvent=function(a){var b=this.Z;if(a.target==this.q)switch(a.type){case Fc:this.A(a.N);break;case Gc:var c=!1;if(v(a.N)){a=a.N;var d=this.c[Jc(this,a)],c=!!d&&b.Ba&&b.Ba(d);d&&!c&&this.D!=a&&this.A(a)}c||Kc(this);break;case Hc:Lc(this);break;case Ic:Mc(this)}};function Nc(a){for(var b=a.j+a.c.length-1,c=a.D,d=0;d<a.c.length;d++){if(c>=a.j&&c<b)c++;else if(-1==c)c=a.j;else if(a.Oa&&c==b){a.A(-1);break}else if(a.vb&&c==b)c=a.j;else break;if(a.A(c))break}}
function Oc(a){for(var b=a.j+a.c.length-1,c=a.D,d=0;d<a.c.length;d++){if(c>a.j)c--;else if(a.Oa&&c==a.j){a.A(-1);break}else if(!a.vb||-1!=c&&c!=a.j)break;else c=b;if(a.A(c))break}}h.A=function(a){var b=Jc(this,a),c=this.c[b];return c&&this.Z.Ba&&this.Z.Ba(c)?!1:(this.D=a,this.q.A(a),-1!=b)};
function Kc(a){var b=Jc(a,a.D);if(-1!=b){var c=a.c[b],d=a.$;if(d.a){var e=c.toString();if(d.S){var f=Pc(d,d.a.value,Qc(d.a)),g=Rc(d,d.a.value);d.Vb.test(e)||(e=e.replace(/[\s\xa0]+$/,"")+d.Bb);d.cc&&(0==f||/^[\s\xa0]*$/.test(g[f-1])||(e=" "+e),f==g.length-1&&(e+=" "));if(e!=g[f]){g[f]=e;e=d.a;(F||E&&H("9"))&&e.blur();e.value=g.join("");for(var k=0,l=0;l<=f;l++)k+=g[l].length;e.focus();f=k;g=d.a;e=f;Sc(g)?g.selectionStart=e:E&&(k=Tc(g),l=k[0],l.inRange(k[1])&&(e=Uc(g,e),l.collapse(!0),l.move("character",
e),l.select()));g=d.a;Sc(g)?g.selectionEnd=f:E&&(k=Tc(g),e=k[1],k[0].inRange(e)&&(f=Uc(g,f),g=Uc(g,Qc(g)),e.collapse(!0),e.moveEnd("character",f-g),e.select()))}}else d.a.value=e;d.La=!0}a.rb?(a.r=null,Mc(a)):a.w();a.dispatchEvent({type:"update",N:c,index:b});a.rb&&a.$.update(!0);return!0}a.w();a.dispatchEvent({type:"update",N:null,index:null});return!1}
h.w=function(){this.D=-1;this.r=null;this.j+=this.c.length;this.c=[];window.clearTimeout(this.I);this.I=null;this.q.w();this.dispatchEvent("suggestionsupdate");this.dispatchEvent(Ic)};function Mc(a){a.I||(a.I=window.setTimeout(x(a.w,a),100))}h.Va=function(){return this.I?(window.clearTimeout(this.I),this.I=null,!0):!1};function Lc(a){a.Va()||window.setTimeout(x(a.Va,a),10)}h.f=function(){Ec.i.f.call(this);delete this.Wa;this.q.B();this.$.B();this.Z=null};
h.Mb=function(a,b,c){this.r==a&&this.Ja(b,c)};h.Ja=function(a,b){var c="object"==ba(b)&&b,d=(c?c.fc():b)?Jc(this,this.D):-1;this.j+=this.c.length;this.c=a;for(var e=[],f=0;f<a.length;++f)e.push({id:this.j+f,data:a[f]});f=null;this.g&&(f=this.Wa[fa(this.g)]||this.g);this.q.yb=f;this.q.Ja(e,this.r,this.g);f=this.zb;c&&void 0!==c.Gb()&&(f=c.Gb());this.D=-1;(f||0<=d)&&0!=e.length&&this.r&&(0<=d?this.A(this.j+d):Nc(this));this.dispatchEvent("suggestionsupdate")};
function Jc(a,b){var c=b-a.j;return 0>c||c>=a.c.length?-1:c}h.wa=function(a){var b=this.$;b.wa.apply(b,arguments)};h.update=function(a){this.$.update(a)};function Vc(a,b){Y.call(this);this.J=a||1;this.V=b||n;this.xa=x(this.Zb,this);this.Ea=y()}A(Vc,Y);h=Vc.prototype;h.enabled=!1;h.e=null;h.setInterval=function(a){this.J=a;this.e&&this.enabled?(this.stop(),this.start()):this.e&&this.stop()};h.Zb=function(){if(this.enabled){var a=y()-this.Ea;0<a&&a<.8*this.J?this.e=this.V.setTimeout(this.xa,this.J-a):(this.e&&(this.V.clearTimeout(this.e),this.e=null),this.dispatchEvent(Wc),this.enabled&&(this.e=this.V.setTimeout(this.xa,this.J),this.Ea=y()))}};
h.start=function(){this.enabled=!0;this.e||(this.e=this.V.setTimeout(this.xa,this.J),this.Ea=y())};h.stop=function(){this.enabled=!1;this.e&&(this.V.clearTimeout(this.e),this.e=null)};h.f=function(){Vc.i.f.call(this);this.stop();delete this.V};var Wc="tick";var Xc;function Yc(a,b){b?a.setAttribute("role",b):a.removeAttribute("role")}function Zc(a,b,c){r(c)&&(c=c.join(" "));var d="aria-"+b;""===c||void 0==c?(Xc||(Xc={atomic:!1,autocomplete:"none",dropeffect:"none",haspopup:!1,live:"off",multiline:!1,multiselectable:!1,orientation:"vertical",readonly:!1,relevant:"additions text",required:!1,sort:"none",busy:!1,disabled:!1,hidden:!1,invalid:"false"}),c=Xc,b in c?a.setAttribute(d,c[b]):a.removeAttribute(d)):a.setAttribute(d,c)}
function $c(a,b){var c="";b&&(c=b.id);Zc(a,"activedescendant",c)};function Qc(a){var b;a:{var c=0,d=0;if(Sc(a))c=a.selectionStart,d=-1;else if(E){var e=Tc(a);b=e[0];e=e[1];if(b.inRange(e)){b.setEndPoint("EndToStart",e);if("textarea"==a.type){e.duplicate();c=a=b.text;for(d=!1;!d;)0==b.compareEndPoints("StartToEnd",b)?d=!0:(b.moveEnd("character",-1),b.text==a?c+="\r\n":d=!0);b=[c.length,-1];break a}c=b.text.length;d=-1}}b=[c,d]}return b[0]}
function Tc(a){var b=a.ownerDocument||a.document,c=b.selection.createRange();"textarea"==a.type?(b=b.body.createTextRange(),b.moveToElementText(a)):b=a.createTextRange();return[b,c]}function Uc(a,b){"textarea"==a.type&&(b=a.value.substring(0,b).replace(/(\r\n|\r|\n)/g,"\n").length);return b}function Sc(a){try{return"number"==typeof a.selectionStart}catch(b){return!1}};function ad(a){N.call(this);this.X=a;this.ma={}}A(ad,N);var bd=[];h=ad.prototype;h.p=function(a,b,c,d){r(b)||(b&&(bd[0]=b.toString()),b=bd);for(var e=0;e<b.length;e++){var f=S(a,b[e],c||this.handleEvent,d||!1,this.X||this);if(!f)break;this.ma[f.key]=f}return this};h.u=function(a,b,c,d,e){if(r(b))for(var f=0;f<b.length;f++)this.u(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.X||this,c=Rb(c),d=!!d,b=a&&a[Hb]?a.W(b,c,d,e):a?(a=Sb(a))?a.W(b,c,d,e):null:null,b&&(Xb(b),delete this.ma[b.key]);return this};
h.qa=function(){Ka(this.ma,Xb);this.ma={}};h.f=function(){ad.i.f.call(this);this.qa()};h.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function cd(a,b,c,d,e){if(!(E||G&&H("525")))return!0;if(Qa&&e)return dd(a);if(e&&!d)return!1;v(b)&&(b=ed(b));if(!c&&(17==b||18==b||Qa&&91==b))return!1;if(G&&d&&c)switch(a){case 220:case 219:case 221:case 192:case 186:case 189:case 187:case 188:case 190:case 191:case 192:case 222:return!1}if(E&&d&&b==a)return!1;switch(a){case 13:return!0;case 27:return!G}return dd(a)}
function dd(a){if(48<=a&&57>=a||96<=a&&106>=a||65<=a&&90>=a||G&&0==a)return!0;switch(a){case 32:case 63:case 107:case 109:case 110:case 111:case 186:case 59:case 189:case 187:case 61:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:return!0;default:return!1}}function ed(a){if(F)a=fd(a);else if(Qa&&G)a:switch(a){case 93:a=91;break a}return a}
function fd(a){switch(a){case 61:return 187;case 59:return 186;case 173:return 189;case 224:return 91;case 0:return 224;default:return a}};function gd(a,b){Y.call(this);a&&hd(this,a,b)}A(gd,Y);h=gd.prototype;h.b=null;h.ka=null;h.Ca=null;h.la=null;h.m=-1;h.F=-1;h.va=!1;
var id={3:13,12:144,63232:38,63233:40,63234:37,63235:39,63236:112,63237:113,63238:114,63239:115,63240:116,63241:117,63242:118,63243:119,63244:120,63245:121,63246:122,63247:123,63248:44,63272:46,63273:36,63275:35,63276:33,63277:34,63289:144,63302:45},jd={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},kd=E||G&&H("525"),ld=Qa&&F;h=gd.prototype;
h.Ib=function(a){G&&(17==this.m&&!a.ctrlKey||18==this.m&&!a.altKey||Qa&&91==this.m&&!a.metaKey)&&(this.F=this.m=-1);-1==this.m&&(a.ctrlKey&&17!=a.keyCode?this.m=17:a.altKey&&18!=a.keyCode?this.m=18:a.metaKey&&91!=a.keyCode&&(this.m=91));kd&&!cd(a.keyCode,this.m,a.shiftKey,a.ctrlKey,a.altKey)?this.handleEvent(a):(this.F=ed(a.keyCode),ld&&(this.va=a.altKey))};h.Kb=function(a){this.F=this.m=-1;this.va=a.altKey};
h.handleEvent=function(a){var b=a.Q,c,d,e=b.altKey;E&&"keypress"==a.type?(c=this.F,d=13!=c&&27!=c?b.keyCode:0):G&&"keypress"==a.type?(c=this.F,d=0<=b.charCode&&63232>b.charCode&&dd(c)?b.charCode:0):D?(c=this.F,d=dd(c)?b.keyCode:0):(c=b.keyCode||this.F,d=b.charCode||0,ld&&(e=this.va),Qa&&63==d&&224==c&&(c=191));var f=c=ed(c),g=b.keyIdentifier;c?63232<=c&&c in id?f=id[c]:25==c&&a.shiftKey&&(f=9):g&&g in jd&&(f=jd[g]);a=f==this.m;this.m=f;b=new md(f,d,a,b);b.altKey=e;this.dispatchEvent(b)};
function hd(a,b,c){a.la&&a.detach();a.b=b;a.ka=S(a.b,"keypress",a,c);a.Ca=S(a.b,"keydown",a.Ib,c,a);a.la=S(a.b,"keyup",a.Kb,c,a)}h.detach=function(){this.ka&&(Xb(this.ka),Xb(this.Ca),Xb(this.la),this.la=this.Ca=this.ka=null);this.b=null;this.F=this.m=-1};h.f=function(){gd.i.f.call(this);this.detach()};function md(a,b,c,d){Q.call(this,d);this.type="key";this.keyCode=a;this.charCode=b;this.repeat=c}A(md,Q);var nd,od;od=nd=!1;var pd=Ga;!pd||-1==pd.indexOf("Firefox")&&-1==pd.indexOf("Camino")&&(-1!=pd.indexOf("iPad")?od=!0:-1==pd.indexOf("iPhone")&&-1==pd.indexOf("iPod")||(nd=!0));var qd=nd,rd=od;function sd(a,b,c,d){N.call(this);d=d||150;this.S=null!=c?c:!0;this.aa=a||",;";this.Bb=this.aa.substring(0,1);a=this.S?"[\\s"+this.aa+"]+":"[\\s]+";this.sb=new RegExp("^"+a+"|"+a+"$","g");this.Vb=new RegExp("\\s*["+this.aa+"]$");this.$a=b||"";this.Qb=!1;this.Pb=this.S;this.e=0<d?new Vc(d):null;this.h=new ad(this);this.ta=new ad(this);this.Y=new gd;this.Ya=-1}A(sd,N);var td=(qd||rd)&&!H("533.17.9");h=sd.prototype;h.cc=!0;h.Fb=!0;h.tb=!1;h.Xb=!0;h.Wb=!0;h.ua=null;h.a=null;h.Da="";h.G=!1;h.La=!1;
h.$b=!0;h.wa=function(a){for(var b=0;b<arguments.length;b++){var c=arguments[b];ea(c)&&1==c.nodeType&&Zc(c,"haspopup",!0);this.h.p(c,"focus",this.Sa);this.h.p(c,"blur",this.Hb);if(!this.a&&(this.ta.p(c,"keydown",this.Ob),ea(c)&&1==c.nodeType)){var d;a:{var e=K(c);try{d=e&&e.activeElement;break a}catch(f){}d=null}d==c&&ud(this,c)}}};h.f=function(){sd.i.f.call(this);null!=this.ua&&window.clearTimeout(this.ua);this.h.B();delete this.h;this.ta.B();this.Y.B();Fb(this.e)};
function vd(a,b){switch(b.keyCode){case 40:if(a.d.q.v){a.tb?Oc(a.d):Nc(a.d);b.preventDefault();return}if(!a.S){a.update(!0);b.preventDefault();return}break;case 38:if(a.d.q.v){a.tb?Nc(a.d):Oc(a.d);b.preventDefault();return}break;case 9:if(!a.d.q.v||b.shiftKey||a.Qb)a.d.w();else if(a.update(),Kc(a.d)&&a.Pb){b.preventDefault();return}break;case 13:if(a.d.q.v){if(a.update(),Kc(a.d)){b.preventDefault();b.stopPropagation();return}}else a.d.w();break;case 27:if(a.d.q.v){a.d.w();b.preventDefault();b.stopPropagation();
return}break;case 229:if(!a.G){a.G||(a.h.p(a.a,"keyup",a.fb),a.h.p(a.a,"keypress",a.eb),a.G=!0);return}break;default:a.e&&!a.$b&&(a.e.stop(),a.e.start())}wd(a,b)}function wd(a,b){var c=a.S&&b.charCode&&-1!=a.aa.indexOf(String.fromCharCode(b.charCode));a.Xb&&c&&a.update();a.Wb&&c&&Kc(a.d)&&b.preventDefault()}h.Jb=function(){return!1};h.Sa=function(a){ud(this,a.target||null)};
function ud(a,b){a.ta.qa();a.d&&Lc(a.d);b!=a.a&&(a.a=b,a.e&&(a.e.start(),a.h.p(a.e,Wc,a.ib)),a.Da=a.a.value,hd(a.Y,a.a),a.h.p(a.Y,"key",a.gb),a.h.p(a.a,"mousedown",a.hb),E&&a.h.p(a.a,"keypress",a.cb))}h.Hb=function(){td?this.ua=window.setTimeout(x(this.kb,this),0):this.kb()};
h.kb=function(){this.a&&(this.h.u(this.Y,"key",this.gb),this.Y.detach(),this.h.u(this.a,"keyup",this.Jb),this.h.u(this.a,"mousedown",this.hb),E&&this.h.u(this.a,"keypress",this.cb),this.G&&xd(this),this.a=null,this.e&&(this.e.stop(),this.h.u(this.e,Wc,this.ib)),this.d&&Mc(this.d))};h.ib=function(){this.update()};h.Ob=function(a){this.Sa(a)};h.gb=function(a){this.Ya=a.keyCode;this.d&&vd(this,a)};h.eb=function(){this.G&&229!=this.Ya&&xd(this)};
h.fb=function(a){this.G&&(13==a.keyCode||77==a.keyCode&&a.ctrlKey)&&xd(this)};h.hb=function(){};function xd(a){a.G&&(a.G=!1,a.h.u(a.a,"keypress",a.eb),a.h.u(a.a,"keyup",a.fb))}h.cb=function(a){wd(this,a)};
h.update=function(a){if(this.a&&(a||this.a.value!=this.Da)){if(a||!this.La){var b;a=Qc(this.a);b=this.a.value;a=Rc(this,b)[Pc(this,b,a)];b=this.sb?String(a).replace(this.sb,""):a;if(this.d&&(this.d.g=this.a,a=this.d,a.r!=b)){a.r=b;var c=a.Z;b=a.r;var d=a.ab,e=x(a.Mb,a);if(c.ac){var c=c.c,f=Bc(b,d,c);0==f.length&&(f=Cc(b,d,c));d=f}else d=Bc(b,d,c.c);e(b,d);Lc(a)}}this.Da=this.a.value}this.La=!1};
function Pc(a,b,c){a=Rc(a,b);if(c==b.length)return a.length-1;for(var d=b=0,e=0;d<a.length&&e<=c;d++)e+=a[d].length,b=d;return b}function Rc(a,b){if(!a.S)return[b];for(var c=String(b).split(""),d=[],e=[],f=0,g=!1;f<c.length;f++)a.$a&&-1!=a.$a.indexOf(c[f])?(a.Fb&&!g&&(d.push(e.join("")),e.length=0),e.push(c[f]),g=!g):g||-1==a.aa.indexOf(c[f])?e.push(c[f]):(e.push(c[f]),d.push(e.join("")),e.length=0);d.push(e.join(""));return d};function yd(){Y.call(this);this.o=zd;this.endTime=this.startTime=null}A(yd,Y);var zd=0;yd.prototype.L=function(){this.s("begin")};yd.prototype.T=function(){this.s("end")};yd.prototype.s=function(a){this.dispatchEvent(a)};function Ad(a,b,c){N.call(this);this.Fa=a;this.J=b||0;this.X=c;this.Ab=x(this.Db,this)}A(Ad,N);h=Ad.prototype;h.R=0;h.f=function(){Ad.i.f.call(this);this.stop();delete this.Fa;delete this.X};h.start=function(a){this.stop();var b=this.Ab;a=void 0!==a?a:this.J;if(!da(b))if(b&&"function"==typeof b.handleEvent)b=x(b.handleEvent,b);else throw Error("Invalid listener argument");this.R=2147483647<a?-1:n.setTimeout(b,a||0)};h.stop=function(){0!=this.R&&n.clearTimeout(this.R);this.R=0};
h.Db=function(){this.R=0;this.Fa&&this.Fa.call(this.X)};var Ma={},Bd=null;function Cd(a){a=fa(a);delete Ma[a];La()&&Bd&&Bd.stop()}function Dd(){Bd||(Bd=new Ad(function(){Ed()},20));var a=Bd;0!=a.R||a.start()}function Ed(){var a=y();Ka(Ma,function(b){Fd(b,a)});La()||Dd()};function Gd(a,b,c,d){yd.call(this);if(!r(a)||!r(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.ba=a;this.Eb=b;this.duration=c;this.Ma=d;this.coords=[]}A(Gd,yd);h=Gd.prototype;h.n=0;
h.play=function(a){if(a||this.o==zd)this.n=0,this.coords=this.ba;else if(1==this.o)return!1;Cd(this);this.startTime=a=y();-1==this.o&&(this.startTime-=this.duration*this.n);this.endTime=this.startTime+this.duration;this.n||this.L();this.s("play");-1==this.o&&this.s("resume");this.o=1;var b=fa(this);b in Ma||(Ma[b]=this);Dd();Fd(this,a);return!0};h.stop=function(a){Cd(this);this.o=zd;a&&(this.n=1);Hd(this,this.n);this.s("stop");this.T()};h.pause=function(){1==this.o&&(Cd(this),this.o=-1,this.s("pause"))};
h.f=function(){this.o==zd||this.stop(!1);this.s("destroy");Gd.i.f.call(this)};function Fd(a,b){a.n=(b-a.startTime)/(a.endTime-a.startTime);1<=a.n&&(a.n=1);Hd(a,a.n);1==a.n?(a.o=zd,Cd(a),a.s("finish"),a.T()):1==a.o&&a.Ga()}function Hd(a,b){da(a.Ma)&&(b=a.Ma(b));a.coords=Array(a.ba.length);for(var c=0;c<a.ba.length;c++)a.coords[c]=(a.Eb[c]-a.ba[c])*b+a.ba[c]}h.Ga=function(){this.s("animate")};h.s=function(a){this.dispatchEvent(new Id(a,this))};
function Id(a,b){P.call(this,a);this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.n=b.n;this.state=b.o}A(Id,P);function Z(a,b,c,d,e){Gd.call(this,b,c,d,e);this.element=a}A(Z,Gd);Z.prototype.sa=aa;Z.prototype.Ga=function(){this.sa();Z.i.Ga.call(this)};Z.prototype.T=function(){this.sa();Z.i.T.call(this)};Z.prototype.L=function(){this.sa();Z.i.L.call(this)};function Jd(a,b,c,d,e){v(b)&&(b=[b]);v(c)&&(c=[c]);Z.call(this,a,b,c,d,e);if(1!=b.length||1!=c.length)throw Error("Start and end points must be 1D");}A(Jd,Z);
Jd.prototype.sa=function(){var a=this.coords[0],b=this.element.style;"opacity"in b?b.opacity=a:"MozOpacity"in b?b.MozOpacity=a:"filter"in b&&(b.filter=""===a?"":"alpha(opacity="+100*a+")")};Jd.prototype.show=function(){this.element.style.display=""};function Kd(a,b,c){Jd.call(this,a,1,0,b,c)}A(Kd,Jd);Kd.prototype.L=function(){this.show();Kd.i.L.call(this)};Kd.prototype.T=function(){this.element.style.display="none";Kd.i.T.call(this)};function Ld(a,b,c){Jd.call(this,a,0,1,b,c)}A(Ld,Jd);
Ld.prototype.L=function(){this.show();Ld.i.L.call(this)};function Md(a,b){return(b&4&&jc(a)?b^2:b)&-5};function $(){}$.Qa=function(){return $.Xa?$.Xa:$.Xa=new $};$.prototype.bb=0;function Nd(a,b,c,d){Y.call(this);this.Ia=a||document.body;this.t=J(this.Ia);this.Tb=!a;this.b=null;this.r="";this.c=[];this.O=[];this.qb=this.ja=-1;this.v=!1;this.className="ac-renderer";this.Ka="ac-row";this.Za="active";this.Na="ac-active";this.Lb="ac-highlighted";this.fa=b||null;this.bc=null!=d?d:!0;this.Nb=!0;this.ia=!1;this.Ub=!!c;this.ra=!1;this.na=0;this.pb=!1}A(Nd,Y);h=Nd.prototype;h.Ja=function(a,b,c){this.r=b;this.c=a;this.ja=-1;this.qb=y();this.g=c;this.O=[];Od(this)};
h.w=function(){this.g&&$c(this.g,null);this.v&&(this.v=!1,this.g&&Zc(this.g,"haspopup",!1),0<this.na?(Fb(this.P),this.P=new Kd(this.b,this.na),this.P.play()):nc(this.b,!1))};h.show=function(){this.v||(this.v=!0,this.g&&(Yc(this.g,"combobox"),Zc(this.g,"autocomplete","list"),Zc(this.g,"haspopup",!0)),0<this.na?(Fb(this.P),this.P=new Ld(this.b,this.na),this.P.play()):nc(this.b,!0))};
function Pd(a,b){var c=0<=b&&b<a.c.length?a.c[b]:void 0,d=0<=b&&b<a.O.length?a.O[b]:void 0;if(a.dispatchEvent({type:"rowhilite",kc:d,N:c?c.data:null})&&(0<=a.ja&&ec(a.O[a.ja],[a.Na,a.Za]),a.ja=b,d)){cc(d,[a.Na,a.Za]);a.g&&$c(a.g,d);var c=a.b,e=X(d),f=X(c),g=uc(c),k=e.x-f.x-g.left,e=e.y-f.y-g.top,f=c.clientHeight-d.offsetHeight,g=c.scrollLeft,l=c.scrollTop,g=g+Math.min(k,Math.max(k-(c.clientWidth-d.offsetWidth),0)),l=l+Math.min(e,Math.max(e-f,0)),d=new I(g,l);c.scrollLeft=d.x;c.scrollTop=d.y}}
h.A=function(a){if(-1==a)Pd(this,-1);else for(var b=0;b<this.c.length;b++)if(this.c[b].id==a){Pd(this,b);break}};function Qd(a){if(!a.b){var b=a.t.Pa("div",{style:"display:none"});a.pb&&(b.style.overflowY="auto");a.b=b;cc(b,ma(a.className).split(" "));Yc(b,"listbox");b.id=":"+($.Qa().bb++).toString(36);a.t.appendChild(a.Ia,b);S(b,"click",a.Ra,!1,a);S(b,"mousedown",a.Ta,!1,a);S(b,"mouseover",a.Ua,!1,a)}}
function Od(a){Qd(a);a.ra&&(a.b.style.visibility="hidden");a.dc&&(a.b.style.minWidth=a.dc.clientWidth+"px");a.O.length=0;a.t.Sb(a.b);if(!a.fa||!a.fa.ic){var b=null;C(a.c,function(a){var d=a;a=this.r;var e=this.t.Pa("div",{className:this.Ka,id:":"+($.Qa().bb++).toString(36)});Yc(e,"option");if(!this.fa||!this.fa.jc)if(d=d.data.toString(),"textContent"in e)e.textContent=d;else if(3==e.nodeType)e.data=d;else if(e.firstChild&&3==e.firstChild.nodeType){for(;e.lastChild!=e.firstChild;)e.removeChild(e.lastChild);
e.firstChild.data=d}else ib(e),e.appendChild(K(e).createTextNode(String(d)));a&&this.bc&&(this.ub=!1,Rd(this,e,a));bc(e,this.Ka);this.O.push(e);a=e;this.ra?this.b.insertBefore(a,b):this.t.appendChild(this.b,a);b=a},a)}0==a.c.length?a.w():(a.show(),Sd(a),pc(a.b))}
function Sd(a){if(a.g&&a.Tb){var b=a.yb||a.g,c,d=a.Ub?3:1;a.ra&&(d^=1);c=d;var e=65;a.pb&&(a.b.style.height="",e|=32);var d=a.b,f=c^1,g,k;if(g=d.offsetParent){var l="HTML"==g.tagName||"BODY"==g.tagName;l&&"static"==W(g,"position")||(k=X(g),l||(l=(l=jc(g))&&F?-g.scrollLeft:!l||E&&H("8")||"visible"==W(g,"overflowX")?g.scrollLeft:g.scrollWidth-g.clientWidth-g.scrollLeft,k=Za(k,new I(l,g.scrollTop))))}g=k||new I;k=X(b);l=lc(b);k=new fc(k.x,k.y,l.width,l.height);if(l=ic(b)){var q=new fc(l.left,l.top,l.right-
l.left,l.bottom-l.top),l=Math.max(k.left,q.left),p=Math.min(k.left+k.width,q.left+q.width);if(l<=p){var w=Math.max(k.top,q.top),q=Math.min(k.top+k.height,q.top+q.height);w<=q&&(k.left=l,k.top=w,k.width=p-l,k.height=q-w)}}l=J(b);w=J(d);if(l.l!=w.l){var p=l.l.body,w=eb(w.l),q=new I(0,0),s;s=(s=K(p))?eb(s):window;var R=p;do{var z;if(s==w)z=X(R);else{z=R;var O=void 0;if(z.getBoundingClientRect)O=gc(z),O=new I(O.left,O.top);else var O=mb(J(z)),t=X(z),O=new I(t.x-O.x,t.y-O.y);t=void 0;if(F&&!H(12)){t=void 0;
t=t=void 0;b:{t=xa();if(void 0===z.style[t]&&(t=(G?"Webkit":F?"Moz":E?"ms":D?"O":null)+ya(t),void 0!==z.style[t])){t=(G?"-webkit":F?"-moz":E?"-ms":D?"-o":null)+"-transform";break b}t="transform"}t=(t=W(z,t)||W(z,"transform"))?(z=t.match(zc))?new I(parseFloat(z[1]),parseFloat(z[2])):new I(0,0):new I(0,0);t=new I(O.x+t.x,O.y+t.y)}else t=O;z=t}q.x+=z.x;q.y+=z.y}while(s&&s!=w&&(R=s.frameElement)&&(s=s.parent));p=Za(q,X(p));!E||E&&9<=Xa||lb(l)||(p=Za(p,mb(l)));k.left+=p.x;k.top+=p.y}var b=Md(b,c),b=new I(b&
2?k.left+k.width:k.left,b&1?k.top+k.height:k.top),b=Za(b,g),m;e&&(m=ic(d))&&(m.top-=g.y,m.right-=g.x,m.bottom-=g.y,m.left-=g.x);b=b.clone();g=Md(d,f);f=lc(d);c=f.clone();b=b.clone();c=c.clone();k=0;0!=g&&(g&2&&(b.x-=c.width+0),g&1&&(b.y-=c.height+0));e&&(m?(g=b,k=c,l=0,65==(e&65)&&(g.x<m.left||g.x>=m.right)&&(e&=-2),132==(e&132)&&(g.y<m.top||g.y>=m.bottom)&&(e&=-5),g.x<m.left&&e&1&&(g.x=m.left,l|=1),g.x<m.left&&g.x+k.width>m.right&&e&16&&(k.width=Math.max(k.width-(g.x+k.width-m.right),0),l|=4),g.x+
k.width>m.right&&e&1&&(g.x=Math.max(m.right-k.width,m.left),l|=1),e&2&&(l=l|(g.x<m.left?16:0)|(g.x+k.width>m.right?32:0)),g.y<m.top&&e&4&&(g.y=m.top,l|=2),g.y<=m.top&&g.y+k.height<m.bottom&&e&32&&(k.height=Math.max(k.height-(m.top-g.y),0),g.y=m.top,l|=8),g.y>=m.top&&g.y+k.height>m.bottom&&e&32&&(k.height=Math.max(k.height-(g.y+k.height-m.bottom),0),l|=8),g.y+k.height>m.bottom&&e&4&&(g.y=Math.max(m.bottom-k.height,m.top),l|=2),e&8&&(l=l|(g.y<m.top?64:0)|(g.y+k.height>m.bottom?128:0)),e=l):e=256,k=
e);e=new fc(0,0,0,0);e.left=b.x;e.top=b.y;e.width=c.width;e.height=c.height;k&496||(c=new I(e.left,e.top),b=F&&(Qa||Ra)&&H("1.9"),c instanceof I?(m=c.x,c=c.y):(m=c,c=void 0),d.style.left=kc(m,b),d.style.top=kc(c,b),c=new $a(e.width,e.height),f==c||f&&c&&f.width==c.width&&f.height==c.height||(e=c,m=lb(J(K(d))),!E||H("10")||m&&H("8")?(d=d.style,F?d.MozBoxSizing="border-box":G?d.WebkitBoxSizing="border-box":d.boxSizing="border-box",d.width=Math.max(e.width,0)+"px",d.height=Math.max(e.height,0)+"px"):
(f=d.style,m?(E?(m=rc(d,"paddingLeft"),b=rc(d,"paddingRight"),c=rc(d,"paddingTop"),g=rc(d,"paddingBottom"),m=new U(c,b,g,m)):(m=V(d,"paddingLeft"),b=V(d,"paddingRight"),c=V(d,"paddingTop"),g=V(d,"paddingBottom"),m=new U(parseFloat(c),parseFloat(b),parseFloat(g),parseFloat(m))),d=uc(d),f.pixelWidth=e.width-d.left-m.left-m.right-d.right,f.pixelHeight=e.height-d.top-m.top-m.bottom-d.bottom):(f.pixelWidth=e.width,f.pixelHeight=e.height))));a.ra&&(a.b.style.visibility="visible")}}
h.f=function(){this.b&&(Wb(this.b,"click",this.Ra,!1,this),Wb(this.b,"mousedown",this.Ta,!1,this),Wb(this.b,"mouseover",this.Ua,!1,this),this.t.removeNode(this.b),this.b=null,this.v=!1);Fb(this.P);this.Ia=null;Nd.i.f.call(this)};
function Rd(a,b,c){if(a.ia||!a.ub)if(3==b.nodeType){var d=null;r(c)&&1<c.length&&!a.ia&&(d=Fa(c,1));c=Td(a,c);if(0!=c.length){var e=b.nodeValue,f=a.Nb?new RegExp("\\b(?:"+c+")","gi"):new RegExp(c,"gi");c=[];for(var g=0,k=f.exec(e),l=0;k;)l++,c.push(e.substring(g,k.index)),c.push(e.substring(k.index,f.lastIndex)),g=f.lastIndex,k=f.exec(e);c.push(e.substring(g));if(1<c.length){d=a.ia?l:1;for(e=0;e<d;e++)f=2*e,b.nodeValue=c[f],g=a.t.createElement("b"),g.className=a.Lb,a.t.appendChild(g,a.t.createTextNode(c[f+
1])),g=b.parentNode.insertBefore(g,b.nextSibling),b.parentNode.insertBefore(a.t.createTextNode(""),g.nextSibling),b=g.nextSibling;b.nodeValue=Fa(c,2*d).join("");a.ub=!0}else d&&Rd(a,b,d)}}else for(b=b.firstChild;b;)d=b.nextSibling,Rd(a,b,c),b=d}
function Td(a,b){var c="";if(!b)return c;r(b)&&(b=Aa(b,function(a){return!/^[\s\xa0]*$/.test(null==a?"":String(a))}));a.ia?r(b)?c=Ba(b,va).join("|"):(c=b.replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,""),c=va(c),c=c.replace(/ /g,"|")):r(b)?c=0<b.length?va(b[0]):"":/^\W/.test(b)||(c=va(b));return c}function Ud(a,b){for(;b&&b!=a.b&&!T(b,a.Ka);)b=b.parentNode;return b?za(a.O,b):-1}h.Ra=function(a){var b=Ud(this,a.target);0<=b&&this.dispatchEvent({type:Gc,N:this.c[b].id});a.stopPropagation()};
h.Ta=function(a){a.stopPropagation();a.preventDefault()};h.Ua=function(a){a=Ud(this,a.target);0<=a&&!(300>y()-this.qb)&&this.dispatchEvent({type:Fc,N:this.c[a].id})};function Vd(a,b){var c=new Ac(a),d=new Nd,e=new sd(null,null,!1),c=new Ec(c,d,e);e.d=c;e.wa(b);return c};/*
 Copyright 2013 Jason Leyba

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/
function Wd(){var a=n.TYPES;Xd(a);L("type-index")&&L("file-index")&&L("module-index")&&(Yd("file-index",a.files),Zd("type-index",a.types),Zd("module-index",a.modules,!0));$d();setTimeout(ka(ae,a),0);setTimeout(be,0)}var ce=["init"],de=n;ce[0]in de||!de.execScript||de.execScript("var "+ce[0]);for(var ee;ce.length&&(ee=ce.shift());)ce.length||void 0===Wd?de=de[ee]?de[ee]:de[ee]={}:de[ee]=Wd;
var fe=function(){var a="./";Ca(document.getElementsByTagName("script"),function(b){b=b.src;var c=b.length;return"dossier.js"===b.substr(c-10)?(a=b.substr(0,c-10),!0):!1});return a}();
function ae(a){function b(){var a=c[e.value];a&&(window.location.href=fe+a)}var c={},d=Da(Ba(a.files,function(a){var b="file://"+a.name;c[b]=a.href;return b}),Ba(a.types,function(a){c[a.name]=a.href;return a.name}));C(a.modules,function(a){c[a.name]=a.href;d=Da(d,a.name,Ba(a.types||[],function(b){var d=a.name+"."+b.name;c[d]=b.href;return d}))});a=L("searchbox");S(a,"submit",function(a){a.preventDefault();a.stopPropagation();b();return!1});var e=a.getElementsByTagName("input")[0];a=Vd(d,e);a.ab=15;
S(a,"update",b)}
function Xd(a){function b(a,b,c,d){S(a,"change",function(){b.style.height=kc(a.checked?c:0,!0);ge(d,a)})}if(L("sidenav")){L("sidenav-overview").href=fe+"index.html";var c=L("sidenav-types-ctrl"),d=Zd("sidenav-types",a.types),e=L("sidenav-modules-ctrl"),f=Zd("sidenav-modules",a.modules),g=L("sidenav-files-ctrl");a=Yd("sidenav-files",a.files);var k=yc(),l=lc(d).height/k+"rem",q=lc(a).height/k+"rem",k=lc(f).height/k+"rem";c.checked=he("dossier.typesList");g.checked=he("dossier.filesList");e.checked=
he("dossier.modulesList");d.style.height=kc(c.checked?l:0,!0);a.style.height=kc(g.checked?q:0,!0);f.style.height=kc(e.checked?k:0,!0);b(c,d,l,"dossier.typesList");b(g,a,q,"dossier.filesList");b(e,f,k,"dossier.modulesList")}}function ie(a,b){this.name=a;this.href=b||"";this.children=[]}
function je(a){function b(a){C(a.children,b);!a.href&&1===a.children.length&&a.children[0].children.length&&(a.name=(a.name?a.name+"/":"")+a.children[0].name,a.href=a.children[0].href,a.children=a.children[0].children)}var c=new ie("");C(a,function(a){var b=a.name.split(/[\/\\]/),f=c;C(b,function(c,k){if(c)if(k===b.length-1)f.children.push(new ie(c,a.href));else{var l=Ca(f.children,function(a){return a.name===c});l||(l=new ie(c),f.children.push(l));f=l}})});b(c);return c}
function Yd(a,b){var c=L(a),d=c.querySelector("i");if(!b.length)return d;var e=je(b),e=sb(Ab,{file:e,H:fe});kb(d);c.appendChild(e);return e}function Zd(a,b,c){a=L(a);var d=a.querySelector("i");if((b=sb(zb,{types:b,H:fe,Aa:!!c}))&&b.childNodes.length)return kb(d),a.appendChild(b),b;nc(a,!1);return d}
function be(){var a=document.getElementsByTagName("DETAILS");a.length&&"boolean"==typeof a[0].open||C(a,function(a){function c(){(d=!d)?a.setAttribute("open",""):a.removeAttribute("open");C(a.childNodes,function(a){1===a.nodeType&&"SUMMARY"!==a.tagName.toUpperCase()&&nc(a,d)})}var d=!0;a.setAttribute("open","");S(a,"click",c);c()})}function ge(a,b){window.localStorage&&(b.checked?window.localStorage.setItem(a,"1"):window.localStorage.removeItem(a))}
function he(a){return window.localStorage?!!window.localStorage.getItem(a):!1}function ke(a){return"dossier.visibility."+a}
function $d(){function a(){var a=window.localStorage;a&&!a.getItem("dossier.visibility")&&(a.setItem("dossier.visibility","1"),a.setItem(ke("public"),"1"),a.removeItem(ke("protected")),a.removeItem(ke("private")))}function b(a,b){var d=document.getElementById(a);if(d){var e=ke(b);d.checked=he(e);c(d,b);S(d,"change",function(){ge(e,d);c(d,b)})}}function c(a,b){a.checked?bc(f,b):dc(f,b)}function d(a){function b(){for(var a=[],e=d=f=s=0,k=c.length;e<k;++e){var l=c.shift();if("H3"===l.tagName)break;a.push(l);
T(l,"public")?(d++,g.mb++):T(l,"protected")?(f++,g.lb++):T(l,"private")&&(s++,g.jb++)}return a}if(a){var c=Ea(a.querySelectorAll(".wrap-details, h3")),d=0,f=0,s=0;do C(b(),function(a){T(a,"public")&&d?(jb(e("public",d),a),d=0):T(a,"protected")&&f?(jb(e("protected",f),a),f=0):T(a,"private")&&s&&(jb(e("private",s),a),s=0)});while(c.length)}}function e(a,b){return sb(yb,{visibility:a,count:b})}if(document.getElementById("show-public")){var f=document.getElementsByTagName("main")[0],g={mb:0,lb:0,jb:0};
a();b("show-public","public");b("show-protected","protected");b("show-private","private");d(document.getElementById("typedefs"));d(document.getElementById("instance-methods"));d(document.getElementById("instance-properties"));d(document.getElementById("static-functions"));d(document.getElementById("static-properties"));d(document.getElementById("compiler-constants"));nc(document.getElementById("visibility-controls"),g.mb||g.lb||g.jb)}};;init();})();
