java_test(
  name = "tests",
  srcs = glob(["*.java"]),
  deps = [
    "//src/java/com/google/javascript/jscomp:jscomp",
    "//test/java/com/github/jsdossier:util",
    "//third_party/java/closure_compiler:closure_compiler",
    "//third_party/java/guava:guava",
    "//third_party/java/jimfs:jimfs",
    "//third_party/java/junit:junit",
    "//third_party/java/truth:truth",
  ],
)
